### ISSUE TITLE
Upgrade to comet 0.34.29

### ISSUE THREAD

**Issue by ze97286** [cometbft/cometbft#1007]
Comet released an update to the 34.x which contains a bug fix to indexer and a few security fixes. We should consider if we want to use it. 

https://github.com/cometbft/cometbft/blob/v0.34.29/CHANGELOG.md#v03429

**Comment by lasarojc** [comment]
Hi @ze97286 
Did you meant to open this issue on a different repository perhaps?

**Comment by ze97286** [comment]
> Hi @ze97286 Did you meant to open this issue on a different repository perhaps?

omg :)
