### ISSUE TITLE
Batch commits to the state and block store

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#1040]
Currently, state is committed to the block and state store using asynchronous calls followed by a synchronous call at the end. 

We need to investigate whether explicitly batching them improves performance. In particular, consider the work done in :
https://github.com/tendermint/tendermint/pull/6067
https://github.com/tendermint/tendermint/pull/6018

and issue: https://github.com/tendermint/tendermint/issues/5888 

The goal of this is two fold:
 - Increase atomicity guarantees
 - Improve performance
DoD:
* [ ] Understand, from a DB perspective whether atomicity is actually increased or not
* [ ] Evaluate whether there are corner cases where the batch becomes very big and understand how the DB handles this underneath (memory vs. disk)
* [x] State is saved in batches with an indication on performance improvement

**Comment by jmalicevic** [comment]
This task has been completed but initial go benchmarking suggests that the performance is actually downgraded. The plan is to rerun the experiments once we change the key ordering during Q4 2023. This would then help make the final decision on whether this is to be merged or rejected.

**Comment by melekes** [comment]
> Understand, from a DB perspective whether atomicity is actually increased or not

Atomicity is increasing, as mentioned in https://github.com/tendermint/tendermint/pull/6018 because it is all or nothing in the case of the batch.

> Evaluate whether there are corner cases where the batch becomes very big and understand how the DB handles this underneath (memory vs. disk)

LSMs don't handle big batches very well ([1](https://github.com/cosmos/iavl/issues/619)). The ideal for `goleveldb` is ~ 100KB ([2](https://github.com/ethereum/go-ethereum/pull/15115)), which is more or less equal to our block part size (64kB).

Here are the results from running the Anton's benchmark on my local PC:

<details>
<summary>Benchmark</summary>
```go
func BenchmarkBlockStore_SaveBlockWithExtendedCommit(b *testing.B) {
	dbTypes := []dbm.BackendType{
		dbm.GoLevelDBBackend,
	}
	NTXs := int64(1024)

	for _, dbType := range dbTypes {
		state, bs, cleanup := makeStateAndBlockStoreSpecificBackend(dbType)
		b.Run(fmt.Sprintf("DBType:%s;NTxs:%d", dbType, NTXs),
			func(b *testing.B) {
				for i := 0; i < b.N; i++ {
					height := bs.Height() + 1
					block := state.MakeBlock(height, test.MakeNTxs(height, NTXs), new(types.Commit), nil, state.Validators.GetProposer().Address)
					validPartSet, err := block.MakePartSet(types.BlockPartSizeBytes)
					if err != nil {
						b.Error(err)
					}
					seenCommit := makeTestExtCommit(block.Header.Height, cmttime.Now())

					bs.SaveBlockWithExtendedCommit(block, validPartSet, seenCommit)
				}
			})

		cleanup()
	}

}

type cleanupFunc func()

func makeStateAndBlockStoreSpecificBackend(backendType dbm.BackendType) (sm.State, *BlockStore, cleanupFunc) {
	config := test.ResetTestRoot("blockchain_reactor_test")
	blockDB, err := dbm.NewDB("block", backendType, config.DBDir())
	if err != nil {
		panic(fmt.Errorf("error creating %s: %w", backendType, err))
	}
	stateDB, err := dbm.NewDB("state", backendType, config.DBDir())
	if err != nil {
		panic(fmt.Errorf("error creating %s: %w", backendType, err))
	}
	stateStore := sm.NewStore(stateDB, sm.StoreOptions{
		DiscardABCIResponses: false,
	})
	state, err := stateStore.LoadFromDBOrGenesisFile(config.GenesisFile())
	if err != nil {
		panic(fmt.Errorf("error constructing state from genesis file: %w", err))
	}
	return state, NewBlockStore(blockDB), func() { os.RemoveAll(config.RootDir) }
}
```
</details>

```
## batching / 1 MB block / goleveldb
155921071 ns/op
## NO batching / 1 MB block / goleveldb
134169606 ns/op
## batching / 10 MB block / goleveldb
1135896143 ns/op
## NO batching / 10 MB block / goleveldb
1096632817 ns/op
```

My recommendation is NOT to save the block in a single batch.
