### ISSUE TITLE
Switch to using unclog for CometBFT's changelog

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#105]
[unclog](https://github.com/informalsystems/unclog) is a tool to create changelogs from independent log entries, minimizing conflicts on the CHANGELOG.md file

This task consists in moving CometBFT to use unclog.

On version v0.37.x, the changelog will be truncated for a fresh start.
On main, changelog does no include the v0.37.x changes, which will be merged into main once v0.37.x is released.

**Comment by lasarojc** [comment]
Use unclog for 0.34 as well.

**Comment by thanethomson** [comment]
Done in #315.
