### ISSUE TITLE
RPC /dump_consensus_state router is not working

### ISSUE THREAD

**Issue by Jeongseup** [cometbft/cometbft#1050]
## Bug Report

After doing some chains upgrades, I experienced that chain's tendermint rpc endpoint wasn't working when querying  `/dump_consensus_state` path. However, when I query other paths (/status, /consensus_state), they work fine.

I mean that other route path( `/status`, `/consensus_state`) are working good

![image](https://github.com/cometbft/cometbft/assets/43164634/0a76a748-d496-407d-88a2-601dccf02c74)
![image](https://github.com/cometbft/cometbft/assets/43164634/d0ef84e5-8f52-4292-a939-beefc506d3d5)

 And `dump_consensus_state` handler is not working right now and the result is as follow
 
![image](https://github.com/cometbft/cometbft/assets/43164634/8d2f3b13-2d03-4a0d-a610-a6a87439140b)

```
# curl -m 5 -sS localhost:26657/dump_consensus_state
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
```

I found this issue when doing a chain upgrade for  Band(v2.5.2) and Cosmos(v10) 

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):

**node command runtime flags**:

Gaia(cosmos v10) uses cometbft core v0.34.29
Band(v2.5.2) uses cometbft core v0.34.28

(personally, I think the problem is being caused after v0.34.28)

### How to reproduce it

Just call the `https://<public-rpc-endpoint>/dump_consensus_state` and https://<public-rpc-endpoint>/status

### `dump_consensus_state` normal output and expriements 

Actually, we can get json data like that if it works fine

![image](https://github.com/cometbft/cometbft/assets/43164634/b838d391-b052-4562-9a1d-6dfb61a7f6a0)

Finally, i've been tested for about it with fixing some codes like bottom and then I got the problem was where to be caused by calling peer data.

so, If i modify some codes about calling peers, the `dump_consensus_state` router works fine! 

https://github.com/cometbft/cometbft/blob/v0.34.28/rpc/core/consensus.go#L51

```go 
// DumpConsensusState dumps consensus state.
// UNSTABLE
// More: https://docs.cometbft.com/v0.34/rpc/#/Info/dump_consensus_state
func DumpConsensusState(ctx *rpctypes.Context) (*ctypes.ResultDumpConsensusState, error) {
	// Get Peer consensus states.
	peers := env.P2PPeers.Peers().List()
	peerStates := make([]ctypes.PeerStateInfo, len(peers))
	// for i, peer := range peers {
	// 	peerState, ok := peer.Get(types.PeerStateKey).(*cm.PeerState)
	// 	if !ok { // peer does not have a state yet
	// 		continue
	// 	}
	// 	peerStateJSON, err := peerState.ToJSON()
	// 	if err != nil {
	// 		return nil, err
	// 	}
	// 	peerStates[i] = ctypes.PeerStateInfo{
	// 		// Peer basic info.
	// 		NodeAddress: peer.SocketAddr().String(),
	// 		// Peer consensus state.
	// 		PeerState: peerStateJSON,
	// 	}	
	// }
	// Get self round state.
	roundState, err := env.ConsensusState.GetRoundStateJSON()
	if err != nil {
		return nil, err
	}
	return &ctypes.ResultDumpConsensusState{
		RoundState: roundState,
		Peers:      peerStates}, nil
}
```
![image](https://github.com/cometbft/cometbft/assets/43164634/79a966a3-5e22-4eac-9ca4-ab83574c7d17)

**Comment by cason** [comment]
This is very likely caused by https://github.com/cometbft/cometbft/issues/863

**Comment by Jeongseup** [comment]
and also, if someone do `dump_consensus_state` query path over and over again, I think the node become dead.

**Comment by cason** [comment]
This should be fixed in  v0.34.29.

**Comment by cason** [comment]
> peerStateJSON, err := peerState.ToJSON()

In the original issue, this method was triggering in a recursive loop to produce the JSON encoded version of the peer state (a summary of the consensus state of every connected peer). The bug doesn't affect the consensus state (the state of the local consensus instance), that is why your workaround probably works.

**Comment by Jeongseup** [comment]
Wait for a while. I'm checking other chains with v0.34.29

**Comment by Jeongseup** [comment]
Thanks! @cason

In cometbft v0.34.29, the problem was resolved greatly, the dump_consensus_state query works fine.

I'll close this issue
