### ISSUE TITLE
Analyze, prototype and experiment easily applicable solutions to reduce bandwidth usage

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1058]
## Problem

The bandwidth consumption in CometBFT is high. In particular, this comes from the fact that the reactor of the mempool is a basic flooding gossip protocol (à la Bitcoin). Because the network topology is dense, it is very likely that a node receives a transaction multiple times from different neighbors. Notice that such a redundancy is useful to prevent byzantine or selfish nodes to stop the dissemination of a transaction in the network.

Some evidence of this redundancy is seen in #613

## Target audience

Consensus developers

## Upside

Small improvements could cut bandwidth usage in CometBFT by (at least) 25%, based on other results.

## Downside

There are many possible improvements to test. To mitigate the risk of spending too much time on discussing improvements, we will divide the improvements into two batches, one with quick wins and one with ideas that require further though and refinement.

- [x] #1086

For each of the approaches that are chosen on the brainstorm we will 

- prototype the approach
- experiment with improvements using e2e and fast prototyping
- experiment with the approaches that turned out promising in the QA infra
- document the solutions as ADRs

The remaining ideas will become part of #11 and if there is room to try these and other ideas on that issue, we will iterate on brainstorming and prototyping.

Consider if #1048 is pre-requisite for this task of if backlog.

## Definition of done

- Provide in the form of an ADR a new gossip protocol, or an improvement to the current one, that reduces the bandwidth of mempool transactions, as demonstrated by experiments on a testnet that resembles as close as possible to a real-world mainnet.
- Implement, test, and merge into main the solution proposed in the ADR.
- Protocols or ideas discussed but not implemented or prototyped should also be documented.

**Comment by hvanz** [comment]
Tentative list of improvements to the propagation protocol: 

1. For each transaction, keep track of the nodes that are known to have the transaction (currently it is only the senders)
1. Reply with TxAck instead of Tx itself if Tx is large.
1. Random sleep during gossip to allow receiving Tx before having to send it.
1. Send HaveTxId instead of Tx itself, depending on Tx size, to warn that Tx is not required.
1. Send HaveTxIdSet (BF) instead of Tx themselves, depending on the Tx set size, to let neighbors know which Txs are required.
1. Propose TxId instead of Tx and accept a block only when the Tx with TxId is known.
    - aka Content Addressable Transactions ([CAT](https://github.com/celestiaorg/celestia-core/blob/feature/cat/docs/celestia-architecture/adr-009-cat-pool.md)), in Celestia
    - also mentioned in the Narwhal and Tusk paper (page 4, right column)
1. Batch transactions (was removed, see[ tendermint#5796](https://github.com/tendermint/tendermint/issues/5796))
1. Attach to Txs message the list of peers that are known to have the txs
    - [draft implementation](https://github.com/cometbft/cometbft/tree/hvanz/mempool-send-peers-with-txs)
    - Note that this approach should use a Bloom filter on the list of peers to reduce the message size, and it needs to check for Byzantine behavior.

**Comment by lasarojc** [comment]
Output of discussing the tentative list of optimizations.

> For each transaction, keep track of the nodes that are known to have the transaction (currently it is only the senders)
   - Open an issue to discuss the approach to discuss the situation in which the same transaction can be sent several times to the same peer because the iterator used to navigate the list of pending transactions (the mempool) can be reset to the beginning of the list. There are two solutions for this problem:
       - Prevent the mempool implementation from resetting iterators to the beginning of the list
       - Store in the senders map the peers to which a node sends a transaction, which prevents sending the same transaction to a peer multiple times even when the mempool iterator is reset
   - Why is the code the way it is right now? Is it a deficiency in the iterator code or was it added to solve a bug?


> Reply with TxAck instead of Tx itself if Tx is large
   - The idea comes from a misunderstanding of the mempool behavior, which is now better defined [here](https://github.com/cometbft/knowledge-base/pull/13) 
   - another way of looking at it is as a duplicate of 4th approach in the list.
   - In any case, we are crossing this approach out of the list.
   
> Random sleep during gossip to allow receiving Tx before having to send it.
   - This is now better understood as a form of throttling, which may be implemented as a random sleep inside the `broadcastTx` routine or as quota on the amount of bytes sent within a time period.
   - Yet another approach would be skipping some transactions during the gossiping, which could lead to the fifo ordering of transactions not being respected.

**Comment by lasarojc** [comment]
Have opened issued #1147 to discuss the first point.

**Comment by lasarojc** [comment]
Have opened #1148 to investigate throttling

**Comment by lasarojc** [comment]
Have opened #1049 to investigate the effects of skipping transactions in the gossiping.

**Comment by cason** [comment]
> Have opened #1049 to investigate the effects of skipping transactions in the gossiping.

The wrong issue is linked here.

**Comment by p0mvn** [comment]
Hi! Are there any quick wins I could contribute to?

**Comment by lasarojc** [comment]
Reopening to handle back port into experimental branches

**Comment by adizere** [comment]
Fixed with the flurry of PRs mentioned above.
