### ISSUE TITLE
rollback set incorrect `LastHeightValidatorsChanged`

### ISSUE THREAD

**Issue by yihuang** [cometbft/cometbft#1074]
### Setup

**CometBFT version** all versions that support rollback

**Have you tried the latest version**: yes

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**node command runtime flags**:

**Comment by thanethomson** [comment]
Please complete the template here, or at least provide us with some information on the bug and how to reproduce it.

**Comment by arno01** [comment]
@yihuang (shot in the dark) could be missing https://github.com/cometbft/cometbft/pull/1610 maybe?

**Comment by yihuang** [comment]
Totally forgot about this, let me finish the PR tmr

**Comment by melekes** [comment]
Closing in favor of https://github.com/cometbft/cometbft/issues/2137 @yihuang let's coordinate there.
