### ISSUE TITLE
Write an abstract description of the mempool propagation protocol

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1081]
Describe the protocol used by the mempool for propagating transactions in the p2p network.

The existing propagation protocol is straightforward: it disseminates transactions by flooding the network.  This leads to a high message complexity, high bandwidth consumption and a high degree of redundancy (i.e., the same transaction is received multiple times by each node).

The goal is to analyze the protocol, in an abstract way, so that to establish its actual message complexity. This should provide insights of how the protocol can be improved and which are its inherent limitations.

**Comment by adizere** [comment]
https://github.com/cometbft/knowledge-base/pull/15
