### ISSUE TITLE
ADR-101: Implement gRPC `BlockResultsService`

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#1095]
We need an implementation of the `BlockResultsService` from ADR-101 on the `feature/adr101-pull-companion` branch.

**Comment by mzabaluev** [comment]
Implemented in #1168 (somehow the Closes magic word does not work)

**Comment by sergio-mena** [comment]
> somehow the Closes magic word does not work

I only works if the PR is open against `main`
