### ISSUE TITLE
namada issue with evidence processing

### ISSUE THREAD

**Issue by tzemanovic** [cometbft/cometbft#1107]
This has been resolved, but opening an issue for tracking purposes. It turned out that the issue was on our side. Many thanks to CometBFT team for identifying the issue!

## Bug Report

We had a problem in a test for https://github.com/anoma/namada/pull/1654 with what appeared to be the chain halting after processing evidence for double voting. The problem was that our test command runner was getting stuck on filled stdout buffer as we explicitly have to put the node runner to a background for it to keep processing the output.

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): 0.37.2

**Have you tried the latest version**: yes

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/anoma/namada

**Comment by sergio-mena** [comment]
Thanks a lot for filing this @tzemanovic !

As explained in the description, the problem has now been resolved with this patch:

```diff
diff --git a/tests/src/e2e/ledger_tests.rs b/tests/src/e2e/ledger_tests.rs
index f6392a900..681b382a1 100644
--- a/tests/src/e2e/ledger_tests.rs
+++ b/tests/src/e2e/ledger_tests.rs
@@ -4373,6 +4373,7 @@ fn double_signing_gets_slashed() -> Result<()> {
     let (_, res) = validator_1
         .exp_regex(r"Slashing [a-z0-9]+ for Duplicate vote in epoch [0-9]+")
         .unwrap();
+    let _bg_validator_1 = validator_1.background();
     println!("\n{res}\n");
     let processing_epoch = Epoch::from_str(res.split(' ').last().unwrap())
         .unwrap()
```
