### ISSUE TITLE
ABCI++ vote extensions & `FinalizeBlock`

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#12]
This is the continuation of the work started in tendermint/tendermint#9053: backport ABCI++ implementation, which lives in the v0.36.x branch.
Once this tracking issue is completed, the whole ABCI++ interface should be ready for QA process, and then release.

## Proposed Path to Done. Summary

The main idea behind this plan is to proceed in the same way as tendermint/tendermint#9053.
The main approach is:
* We will "follow" our work on v0.36.x. By "following a PR", I mean looking at that PR (similar work done for v0.36.x) and copying over only what makes sense. "git cherry-pick" turned out to be our best friend for "following" PRs in tendermint/tendermint#9053
* We will be considering only commits related to vote extensions and `FinalizeBlock`
* We will be skipping `PrepareProposal`/`ProcessProposal` related commits (as they are already in `main` via tendermint/tendermint#9053)

The work is structured very similarly to #9053. It consists of two main parts (further described below):
- [x] (1) Preliminary work
- [ ] (2) Core feature work

(1) and (2) can mostly proceed in parallel.

protobufs will be managed as in v0.37.x → They will evolve with the code

### (1) Preliminary Work

We could have two threads here, but as all these tasks serialized are shorter than the critical path in "Core Feature Work", there's no point

- [x] Create feature branch: `feature/abci++vef`
- [x] Restore CI on `feature/abci++vef` branch
- [x] e2e tests: port any improvements not included in the core work section (`git diff HEAD..v0.36.x -- test/e2e`) (tracking: https://github.com/tendermint/tendermint/pull/9426)

### (2) Core feature work 

We have three threads that can proceed in parallel:
- Vote extensions (*)
- `FinalizeBlock` (*)
- Spec and doc work

(*) Only when vote extensions and `FinalizeBlock` are done, can we proceed with the fourth part:

- Final adjustments
  - tasks here _could_ be further parallelized

#### Vote Extensions

- [x] Old vote extensions
  - Follow tendermint/tendermint#6646, then tendermint/tendermint#6885
  - Double-check integration of `PrepareProposal` -- vote extensions
    -  Check if there is something missing from tendermint/tendermint#7821 (or tendermint/tendermint#6915)
- [x] tendermint/tendermint#9835
  - First cherry-pick tendermint/tendermint#8031 (ignore spec part), 
  - Main part: follow tendermint/tendermint#8141
- [x] tendermint/tendermint#9846
  - follow tendermint/tendermint#8402
- [x] Vote extension propagation tendermint/tendermint#9852
  - follow tendermint/tendermint#8433
- [x] tendermint/tendermint#9861
  - Add activation logic: follow tendermint/tendermint#8547
- [x] tendermint/tendermint#9864
  - follow tendermint/tendermint#8587
- [x] tendermint/tendermint#9887

#### `FinalizeBlock`

- [x] tendermint/tendermint#9427  [Estimation: 4 days]
  -  Follow tendermint/tendermint#7798 (it's bulky, and might depend on other infra PRs, if yes cherry-pick them first)
- [x] Sync `FinalizeBlock` with spec
  - Description: follow tendermint/tendermint#7983

#### Final adjustments

Most of these tasks can be done in parallel, but they are quite short.

- [x] #10

#### Spec and doc work

Low risk, can proceed completely in parallel with the rest

- [x] #24
- [ ] #25

Original issue: tendermint/tendermint#9396

**Comment by adizere** [comment]
Closing this as it's pretty much done. The only item left is issue 25, which is tracked separately.
