### ISSUE TITLE
Replace usage of "we" in consensus timeouts explained

### ISSUE THREAD

**Issue by rootulp** [cometbft/cometbft#1223]
https://github.com/cometbft/cometbft/blob/cf230821c899f1f0cd3ef9cbbcc678ca01008d46/docs/core/configuration.md?plain=1#L516-L531

I have an uber nit comment regarding this section of the docs. It's not immediately clear to me what "we" refers to. I think "we" can be replaced with "an honest validator" which seems clearer to me.

**Comment by rootulp** [comment]
On second though, maybe the "honest" isn't strictly necessary because a malicious validator would still abide by these timeouts.

**Comment by lasarojc** [comment]
Thanks for the comment, @rootulp .
I think replaces "we" for "a validator should" would work here. It will make it all validators should, but cannot be force to.

**Comment by alijnmerchant21** [comment]
@rootulp thanks for the comment. This seems to be a language thing; we intend to do an overhaul for the entire docs. Anyways, this seems trivial, I could make quick changes to the verbose.

**Comment by alijnmerchant21** [comment]
PR - #1263 closes this issue.
