### ISSUE TITLE
chore: Bump Go version to v1.21

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#1245]
Since [Go v1.21 was released](https://go.dev/blog/go1.21), in order to keep up with their maintained releases, we should bump the minimum Go version on a few of our release branches:

**Remember to inform SDK and other users prior to bumping Go versions.**

- [x] #1244 
- [x] Bump the minimum Go version for v0.38 to Go v1.21
- [x] Bump the minimum Go version for v0.34 to Go v1.20 (since v1.19 is no longer maintained)

**Comment by lasarojc** [comment]
0.34 was bumped to 1.20 in commit 54d2a76cb72baf1a6efdbb7e44579be40cc37f4f
