### ISSUE TITLE
docs: Add logging guidelines

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#1249]
Given that there's such a mix of different perspectives/approaches to logging in the codebase, we should add some guidelines as to how to go about writing good log messages.

The best place I can think of for this right now is in the contributing guidelines, but if anyone has any other suggestions please let me know.

**Comment by melekes** [comment]
For some reason, issue was not closed automatically via https://github.com/cometbft/cometbft/pull/1250
