### ISSUE TITLE
Ensure smooth upgrades after removing genesis from kvstore.

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#1259]
The work done in PR#1017 will remove the genesis file from the database. We need to ensure that a node, upgrading to a version of CometBFT with this change can smoothly do so and retrieve the file from the new location. This should be automatic.

Additionally, we should delete the file from the database if it was persisted in a previous version. This operation needs to be automatically performed on boot. If we detect the genesis file in the database, we delete it and output a warning message to the operator that this information is no longer there. 

**Note** This can be merged only once we merge the PR removing the genesis file from the DB. 

DoD:

- [ ] Node boot up code is altered to check for the existence of the genesis file and deleting it
- [ ] Unit tests exist to test this behaviour. 
- [ ] Changelog entry

**Comment by andynog** [comment]
If we want to chunk during the upgrade then we will also need to do #1289 in order to have a `DOD` here

**Comment by jmalicevic** [comment]
This should cover the base case that we can merge and then release. Once we do the chunking we will update the upgrading path accordingly, if needed. For now I would keep that as a separate concern.
