### ISSUE TITLE
cli/genesis: allow operators to provide Comet with a hash of the genesis file to be verified on load 

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#1303]
### Summary

On load CometBFT stores the hash of the genesis file in the state database but verifies it against a recomputed hash of the genesis file itself. Operators often get a precomputed hash along with a genesis file. We can provide them with an optional `cli` parameter via which they pass this hash for Comet to double check that the genesis file was not corrupted.

### Proposal

- Introducing a new flag - `genesis_hash` to be passed via command line to CometBFT
- This flag is optional as it can increase the safety guarantees provided by comet but it might be cumbersome for operators to update their existing node boot-up procedures with an extra required flags. 
- If the flag is not provided the we log a warning to the operator.
- This hash has to be checked against the sha256 hash of the genesis file document iteself (after merging PR #1293 ). If there is a mismatch between the two hashes, the node will not boot. 
- Only when these two match, we store the hash of the genesis file in stateDB for checks further in the future. There should not be a scenario where there has been a hash stored already and it mismatches (a correct) hash provided by the operator. The only scenarios where this is possible - a corrupt initial genesis file or a operator giving the wrong hash. In any case, we have to log the error and not boot.

**Comment by glnro** [comment]
Upon initial exploration, there is a [flag to provide the genesis command](https://github.com/cometbft/cometbft/blob/main/cmd/cometbft/commands/run_node.go#L97) already implemented for `start`. The helper function [`checkGenesisHash`](https://github.com/cometbft/cometbft/blob/main/cmd/cometbft/commands/run_node.go#L130) hashes the genesis file and validates that it matches the genesis hash provided by the `--genesis_hash` flag. If the values mismatch, the error returned to the operator is misleading `Error: set min gas price in app.toml or flag or env variable: error in app.toml`, so this needs to be addressed.  Currently the flag is optional and no warning is provided if it is missing.

To summarize so far, points 1,2, and 4 are already implemented. 

On point 5, according to #1293 , on node start, within the scope of `LoadStateFromDBOrGenesisDocProvider` (which is called within the scope of [`NewNode`](https://github.com/cometbft/cometbft/blob/main/node/node.go#L138), which is [initialized and passed to the start command](https://github.com/cometbft/cometbft/blob/main/cmd/cometbft/main.go#L43-L46) called [just after](https://github.com/cometbft/cometbft/blob/main/cmd/cometbft/commands/run_node.go#L101) the optional genesis hash verification), if there is no existing genesis doc hash available in the stateDb, the genesis file is hashed, and that value gets stored.

First question, is point 5 specifying an additional requirement that if the genesis hash is passed in via the flag, and the hash has not already been set in the DB, that it must match the hash of the genesis doc before setting it? If so, technically both values have already been compared before `NewNode` has been called.

To follow up, in the case where the hash already exists in the DB, it seems that point 5 also specifies that a check should be made against the optionally provided hash. This requirement presents a challenge with respect to passing the genesis hash parsed from the flag so it can be accessed in the scope of `NewNode` and passed to `LoadStateFromDBOrGenesisDocProvider` where `stateDB.Get(genesisDocHashKey)` can be called and the hashes compared. It would be ideal if there were some sort of context passed in that we could set this in. However, the next obvious method would be adding a `GenesisHash` parameter to something like the Storage config. The alternative is changing the signature for `NewNode` which I don't think is appropriate for an optional flag where its use is likely a corner case for operators.

**Comment by andynog** [comment]
Seems that most of this is already present in the code, for the flag I think as @glnro mentioned the error for a mismatch needs to be fixed, and also, I think there's a warning that needs to be emitted if the flag is not used (I don't think this exists today). 

For #5, I think this is the workflow expected. 

- start node -> if hash flag provided compare with hash of the genesis in the config folder -> if not a match -> abort -> if match -> if no hash in DB, calculate from the genesis in config -> store in DB -> if hash in DB -> compare value from DB with hash of the file -> if it is a mismatch -> abort

But this way, you might need to calculate the hash from the file twice (hash flag <-> file) and (file <-> hash DB) since there's no mechanism to pass it around.

**Comment by jmalicevic** [comment]
We can also forego the check that exists and remove it, but jsut add the hash into the config struct to be verified in the start up function?

**Comment by mzabaluev** [comment]
> But this way, you might need to calculate the hash from the file twice (hash flag <-> file) and (file <-> hash DB) since there's no mechanism to pass it around.

Of course we should change the code to only hash the file once for all checks. One call to the `GenesisDocProvider` function should ever be made during the startup sequence, retrieving all information the node might need to validate the genesis against other data.

Seeing how equality is transitive, you might prefer to validate flag <-> hash in DB before loading the file and afterwards do one of the checks mentioned above, but that's optimization for a failure case :grin:
