### ISSUE TITLE
spec: ABCI spec refers to both `Evidence` and `Misbehavior` types

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#1326]
References to `Evidence` type, which is used inside CometBFT but not offered to the ABCI application:

- https://docs.cometbft.com/v0.37/spec/abci/abci++_basic_concepts#evidence
- https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#beginblock
- https://docs.cometbft.com/v0.37/spec/abci/abci++_basic_concepts.md#evidence (this link is broken)

References to `Misbehavior` type, which is the actual type offered to the ABCI application:

- https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#beginblock
- https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#prepareproposal
- https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#processproposal
- https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#misbehavior: mentions it has been used in ABCI, probably not true

The introduction of this new type has also to be mentioned in the https://docs.cometbft.com/v0.37/spec/abci/abci++_methods#data-types-introduced-or-modified-in-abci, as it was updated in ABCI++, with respect with ABCI.

**Comment by cason** [comment]
Could be part of  #24.

**Comment by sergio-mena** [comment]
> mentions it has been used in ABCI, probably not true

Actually, it was renamed for `v0.37.x`, IIRC

**Comment by andynog** [comment]
> > mentions it has been used in ABCI, probably not true
> 
> Actually, it was renamed for `v0.37.x`, IIRC

yes, according to the CHANGELOG https://github.com/cometbft/cometbft/blob/main/CHANGELOG.md#v0370
