### ISSUE TITLE
proto: protobuf renaming and versioning

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#1330]
We should publish our Protobuf definitions to the Buf registry. These should ideally be pushed via CI when we make changes to the protos from our release branches.

[We are not tracking here the issues taking care of publishing `tendermint` protobufs to the buf repository (`v0.34.x` to `v0.38.x`) because, (1) they are not trivial and (2) they are not blocking`v1.0`. The issue #1402, is in the backlog]

- [x] #94 
- [x] #95
- [x] #736 
- [x] #1530
- [x] #1504
- [x] #1555
- [x] #1561
- [x] #1834
- [x] #1403
- [x] #1649
- [x] #1650
- [x] #1672 (merge feature branch into `main`)
- [x] #1733
  - [x] #1726 
  - [ ] Find a solution for dependencies (gogoproto, etc.)
  - [ ] (if keeping a copy in our repo) Goal: the files should be the same (published vs. released from Github)
  - [ ] [stretch] ideally, automatically via CI when tagging releases or pre-releases (see the pre-release and release workflows in the `.github/workflows` folder).

**Comment by mzabaluev** [comment]
All tasks are done.
