### ISSUE TITLE
proto: Publish v0.34-v0.38 `tendermint` types to the `tendermint/tendermint` Buf repository

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#1402]
Tasks
- [ ] Find a solution for dependencies (gogoproto, etc.)
- [ ] If changes needed above make sure we can also commit the changes on our respective branches
   - Goal: the files should be the same (published vs. released from Github)
   - We can disregard any Buf guidelines (naming, etc) for the versions that are already released (`v0.34.x`,`v0.37.x`,`v0.38.x`)
- [ ] Once everything above solved: publish the result to the https://buf.build/tendermint/tendermint Buf repository

**Comment by andynog** [comment]
Hi @sergio-mena, I beileve it would be helpful to specify which Buf repository to make it clear e.g. 
`https://buf.build/cometbft/cometbft/` or
`https://buf.build/tendermint/tendermint`

**Comment by thanethomson** [comment]
I've manually published the `tendermint/tendermint` protos to the Buf registry on separate branches corresponding to the relevant version of CometBFT:

- **v0.38.x**: https://buf.build/tendermint/tendermint/ and https://buf.build/tendermint/tendermint/docs/v0.38.x
- **v0.37.x**: https://buf.build/tendermint/tendermint/docs/v0.37.x
- **v0.34.x**: https://buf.build/tendermint/tendermint/docs/v0.34.x

I'm not sure what's meant by "Find a solution for dependencies (gogoproto, etc.)". We specify gogoproto as a dependency in our `proto/buf.yaml` file and Buf is meant to resolve that dependency (see https://buf.build/cosmos/gogo-proto). So I'm going to close this as done for now.

It's probably not worth it at this point to automate the publishing of `tendermint` package protos - we can rather deal with that for `cometbft` package protos in the v1 series.
