### ISSUE TITLE
proto: Coordinate renaming/versioning changes with users

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#1403]
Tasks
   - [x] Communicate the changes
   - [x] Figure out what to adapt in the concerned projects (e.g., tendermint-rs)

DoD

- Teams with dependencies to CometBFT (SDK, ibc-rs, Hermes, ibc-go):
  - have visibility on the changes
  - cannot identify any showstoppers
  - are able to run some basic tests (or do code inspection) to ensure they can plan and execute the transition as smoothy as possible
- We have a coordination plan across all teams on release ETAs, needed integration tests, etc.

**Comment by melekes** [comment]
@sergio-mena are you currently working on this? maybe, if you don't mind, I can take over.

**Comment by sergio-mena** [comment]
We held a meeting in September to communicate the changes to the concerned teams (ibc-go, SDK, ibc-rs, hermes). This was the first task.
Second task is https://github.com/informalsystems/tendermint-rs/pull/1381, but that is non-blocking for cutting `v1`. I will continue on it next week.
