### ISSUE TITLE
replay missing begin block

### ISSUE THREAD

**Issue by forcodedancing** [cometbft/cometbft#1468]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
v0.37.2

**Have you tried the latest version**: no

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): 
- **Install tools**:
- **Others**:

**node command runtime flags**:

### What happened?

When replay with mock app, the original implementation misses the logic for `begin block`. 

### Anything else we need to know

As we can see https://github.com/cometbft/cometbft/blob/v0.37.2/consensus/replay_stubs.go here, the begin block is not handled.

We should add something like this:

```
func (mock *mockProxyApp) BeginBlock(req abci.RequestBeginBlock) abci.ResponseBeginBlock {
	mock.txCount = 0
	return *mock.abciResponses.BeginBlock
}
```

**Comment by cason** [comment]
Hey, thank you for your report.

Can you elaborate on why the lack of this method constitutes a bug? 

Have you identified a scenario where the lack of the proposed method produces an error or unexpected behavior?

**Comment by andynog** [comment]
Hi @forcodedancing, just following up on this issue. Did you get a chance to review what @cason posted above ? Just want to check if you had a chance to review and if you're OK with his explanation and if we should close this issue. 

Or if not clear or if you still have concerns, could you please provide additional information so we can still keep assessing it?
