### ISSUE TITLE
proto: Rename messages and services to satisfy buf lints

### ISSUE THREAD

**Issue by mzabaluev** [cometbft/cometbft#1530]
Change the names in the latest package versions of proto files to satisfy these [buf lint rules](https://buf.build/docs/lint/rules):

    - RPC_REQUEST_RESPONSE_UNIQUE
    - RPC_REQUEST_STANDARD_NAME
    - RPC_RESPONSE_STANDARD_NAME
    - SERVICE_SUFFIX

This will make the proto files satisfy the `DEFAULT` lint category.

**Comment by sergio-mena** [comment]
Closed by #1533
