### ISSUE TITLE
Use prepared SQL statements in PSQL indexer

### ISSUE THREAD

**Issue by mzabaluev** [cometbft/cometbft#1532]
The indexer implementation in [`state/indexer/sink/psql.go`](https://github.com/cometbft/cometbft/blob/111d252d75a4839341ff461d4e0cf152ca2cc13d/state/indexer/sink/psql/psql.go) executes SQL queries in loops, where the queries differ only in the bound parameter values.

The obvious approach to improve performance of the SQL queries is to compile SQL statements once and execute with the statement handles inside the loop body.

_Originally posted by @mzabaluev in https://github.com/cometbft/cometbft/pull/1531#discussion_r1369912843_

**Comment by andynog** [comment]
Hi @mzabaluev, this seems a nice improvement but I'd think this might be a low priority since we are focusing on the Data Companion solutions. But I've marked this as a good first issue because we might be help from the community on implementing it since it's mostly Postgresql related code.
