### ISSUE TITLE
Explicitly set a `MaxConcurrentStreams` for GRPC servers

### ISSUE THREAD

**Issue by rootulp** [cometbft/cometbft#1546]
### Summary

Context: https://github.com/celestiaorg/celestia-core/issues/1127

Explicitly set a `MaxConcurrentStreams` for GRPC servers.

### Problem Definition

https://github.com/grpc/grpc-go/security/advisories/GHSA-m425-mq94-257g suggests

> Along with applying the patch, users should also ensure they are using the grpc.MaxConcurrentStreams server option to apply a limit to the server's resources used for any single connection.

CometBFT has already bumped to https://github.com/cometbft/cometbft/blob/22af40641c58f565b6cc694c9e9871a381627309/go.mod#L36

but an explicit `MaxConcurrentStreams` hasn't been defined https://github.com/cometbft/cometbft/blob/22af40641c58f565b6cc694c9e9871a381627309/abci/server/grpc_server.go#L46

### Proposal

```diff
-	s.server = grpc.NewServer() 
+	// Explicitly set MaxConcurrentStreams to apply a limit to the server's resources used for any single connection.
+	// https://github.com/grpc/grpc-go/security/advisories/GHSA-m425-mq94-257g
+	s.server = grpc.NewServer(grpc.MaxConcurrentStreams(100))
```

We can replace `100` with whichever value you deem appropriate. `100` is the default client max concurrent streams. `math.MaxUint32` is the default server max concurrent streams.

Ref:
- https://github.com/grpc/grpc-go/blob/c76d75f4f95626e9e6c0008e6a6120d43747b519/internal/transport/defaults.go#L34
- https://github.com/grpc/grpc-go/blob/c76d75f4f95626e9e6c0008e6a6120d43747b519/internal/transport/http2_client.go#L343
- https://github.com/grpc/grpc-go/blob/c76d75f4f95626e9e6c0008e6a6120d43747b519/server.go#L177

**Comment by andynog** [comment]
Hi @rootulp, thanks for submitting the issue. We are evaluating it. Is Celestia using the ABCI gRPC server in different ways ? As far as I know you use the in-process server right ? 

Also, the a gRPC server (or RPC) should never be exposed publicly (only through a reverse proxy or Cloudflare that in this particular case should be patched and properly configured too).

**Comment by rootulp** [comment]
> As far as I know you use the in-process server right ?

Correct. The only two instances I found in celestia-core are:
1. https://github.com/celestiaorg/celestia-core/blob/4b925ca55acc75d51098a7e02ea1e3abeb9bab76/rpc/grpc/client_server.go#L22
2. https://github.com/celestiaorg/celestia-core/blob/4b925ca55acc75d51098a7e02ea1e3abeb9bab76/abci/server/grpc_server.go#L46 (abci and since we use in-process, I infer this isn't used). 

It's possible this issue isn't needed then.
