### ISSUE TITLE
e2e: Allow disabling PEX reactor

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1579]
## Feature Request

During experimentation it may be useful to disable peer discovery on the whole setup and only connect to peers specified in the `config.toml`

### Summary

Allow disabling the PEX reactor in the manifests.

### Problem Definition

When experimenting, restarting leads to a different overlay network being set every time, casting doubt on comparison results.

### Proposal

Allow disabling the PEX on manifests so that connections are only stablished to the peers specified in generated `config.toml`

**Comment by cason** [comment]
Please refer that this applies to end-to-end tests or qa-infrastructure.

We can disable PEX on regular nodes, there is a configuration key for that: https://github.com/cometbft/cometbft/blob/main/config/toml.go#L360

**Comment by lasarojc** [comment]
> Please refer that this applies to end-to-end tests or qa-infrastructure.
> 
> We can disable PEX on regular nodes, there is a configuration key for that: https://github.com/cometbft/cometbft/blob/main/config/toml.go#L360

Updated to reflect the limitation only on manifests.
