### ISSUE TITLE
Flaky TestProvider test

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1582]
## Bug Report

The modification of the prunning code has TestProvider test flaky.
The code was changed to address the flakiness but it wasn't enough, as shown in the following snippet from https://github.com/cometbft/cometbft/actions/runs/6796991125/job/18478177653?pr=1558

```
ok  	github.com/cometbft/cometbft/light	67.678s	coverage: 78.8% of statements
CometBFT running!
E[2023-11-08|10:34:21.264] Error serving server                         err="accept tcp 127.0.0.1:40299: use of closed network connection"
E[2023-11-08|10:34:21.264] Error starting gRPC server                   err="accept tcp 127.0.0.1:42083: use of closed network connection"
E[2023-11-08|10:34:21.264] Error starting privileged gRPC server        err="accept tcp 127.0.0.1:35771: use of closed network connection"
E[2023-11-08|10:34:21.267] Stopped accept routine, as transport is closed module=p2p numPeers=0
E[2023-11-08|10:34:21.267] Failed to save AddrBook to file              module=p2p book=/tmp/-_home_runner_work_cometbft_cometbft_light_provider_http_2218041770/config/addrbook.json file=/tmp/-_home_runner_work_cometbft_cometbft_light_provider_http_2218041770/config/addrbook.json err="rename /tmp/-_home_runner_work_cometbft_cometbft_light_provider_http_2218041770/config/write-file-atomic-06770805029005217365 /tmp/-_home_runner_work_cometbft_cometbft_light_provider_http_2218041770/config/addrbook.json: no such file or directory"
CometBFT running!
E[2023-11-08|10:34:40.807] Stopped accept routine, as transport is closed module=p2p numPeers=0
E[2023-11-08|10:34:40.807] Error serving server                         err="accept tcp 127.0.0.1:34245: use of closed network connection"
E[2023-11-08|10:34:40.807] Error starting gRPC server                   err="accept tcp 127.0.0.1:33719: use of closed network connection"
E[2023-11-08|10:34:40.807] Error starting privileged gRPC server        err="accept tcp 127.0.0.1:39465: use of closed network connection"
CometBFT running!
E[2023-11-08|10:34:50.919] Failed to prune blocks                       module=state err="failed to prune states to height 1: from height 1 must be lower than to height 1" targetRetainHeight=1 newRetainHeight=1
E[2023-11-08|10:35:00.353] Stopped accept routine, as transport is closed module=p2p numPeers=0
E[2023-11-08|10:35:00.354] Error serving server                         err="accept tcp 127.0.0.1:36331: use of closed network connection"
E[2023-11-08|10:35:00.354] Error starting gRPC server                   err="accept tcp 127.0.0.1:35409: use of closed network connection"
E[2023-11-08|10:35:00.354] Error starting privileged gRPC server        err="accept tcp 127.0.0.1:35013: use of closed network connection"
CometBFT running!
E[2023-11-08|10:35:19.900] Stopped accept routine, as transport is closed module=p2p numPeers=0
E[2023-11-08|10:35:19.900] Error serving server                         err="accept tcp 127.0.0.1:34243: use of closed network connection"
E[2023-11-08|10:35:19.900] Error starting gRPC server                   err="accept tcp 127.0.0.1:40419: use of closed network connection"
E[2023-11-08|10:35:19.900] Error starting privileged gRPC server        err="accept tcp 127.0.0.1:34339: use of closed network connection"
--- FAIL: TestProvider (78.20s)
    http_test.go:64: 
        	Error Trace:	/home/runner/work/cometbft/cometbft/light/provider/http/http_test.go:64
        	Error:      	Should be true
        	Test:       	TestProvider
FAIL
```

**Comment by jmalicevic** [comment]
@lasarojc ,can you add the PR that tried to fix the flakiness?

**Comment by jmalicevic** [comment]
The error : `failed to prune states to height 1: from height 1 must be lower than to height 1" targetRetainHeight=1 newRetainHeight=1` is actually also indicating of a bug I believe. In the old pruner code in 0.37.x there was [this check ](https://github.com/cometbft/cometbft/blob/f565f92a836459fc3d4ae1a0990b6d99f196cb3e/consensus/state.go#L1759) to make sure the from and to are different. In `main` ,when we implemented the pruner we deleted the `pruneBlocks` function from `consensus/state/execution.go` [with the check](https://github.com/cometbft/cometbft/blob/e58f2de68fc6d8ade38be4141bf5540ba2f0c486/state/execution.go#L764) and we did not add the check in the [pruner code] https://github.com/cometbft/cometbft/blob/83172f78d45e47a41281d6a935c6fbd3e79dbae8/state/pruner.go#L488)

**Comment by lasarojc** [comment]
> @lasarojc ,can you add the PR that tried to fix the flakiness?

That was #1467

**Comment by jmalicevic** [comment]
I was able to get the failure locally but my description above is not the reason teh test fails (i have it passing with the same message). What I am surprised about is, why is it even an error that the height is greater or equal to 1000? We do not have any constraint on that from what I can see. I understand why it should be `>= 10` but not why it should be `<1000`

**Comment by jmalicevic** [comment]
Also I am not sure that the fixes in #1467 are related to this particular test. The failures were occurring when looking for already pruned blocks. This failure is indicating we have a block that is higher than what we expect.

**Comment by lasarojc** [comment]
I see. I will likely have some cycles tomorrow and can help understand what is really going on.

**Comment by thanethomson** [comment]
> I understand why it should be >= 10 but not why it should be <1000

This seems to me to be the problem - why would we need to constraint it to be < 1000? Surely we're just testing that all the HTTP-based provider functionality works?

**Comment by lasarojc** [comment]
Right, it doesn't make sense to me either. I mean, it is expected to not be much larger than 10, but it could be.
This line should be removed.

In that sense, 
https://github.com/cometbft/cometbft/blob/a05b73ee7975919b65fd86afc1584cfa842e5f75/light/provider/http/http_test.go#L83
could also be adjusted to have a much larger jump, say +10000 rather than +1000

**Comment by lasarojc** [comment]
Sorry for the red herring. I got misled by the pruning error message but this test failure has nothing to do with the pruning changes.

**Comment by jmalicevic** [comment]
No worries, same here, but it helped us discover a potential flaw in pruning too so all good :D I am pushing a fix for this error message :D
