### ISSUE TITLE
Error in the introductory guides

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1583]
## Bug Report

The introductory `go.md` and `go-builtin.md` guides have a wrong example of `prepareProposal`, as noted [here] (https://github.com/cometbft/cometbft/pull/1384#discussion_r1342041056)

```
func (app *KVStoreApplication) PrepareProposal(_ context.Context, proposal *abcitypes.RequestPrepareProposal) (*abcitypes.ResponsePrepareProposal, error) {
   totalBytes := int64(0)
   txs := make([]byte, 0)

   for _, tx := range proposal.Txs {
     totalBytes += int64(len(tx))
     txs = append(txs, tx...)

       if totalBytes > int64(proposal.MaxTxBytes) {
         break
       }
     }

     return &abcitypes.ResponsePrepareProposal{Txs: proposal.Txs}, nil
 }
```

First, `txs` should be a slice of slices.
Second, the overflow check should be done before appending the transaction to `txs`.

The fix need to be back ported to 0.38 and 0.37.

**Comment by andynog** [comment]
Thanks @lasarojc for pointing this out. I'll take on this and fix the docs and backport it

**Comment by melekes** [comment]
I agree with @lasarojc [here](https://github.com/cometbft/cometbft/pull/1603#discussion_r1391319868) that it's an intro document and we shouldn't overwhelm devs with details. Simply relaying existing transactions without modifying them is enough, imho.
