### ISSUE TITLE
p2p: redoing a block request drops peer (slow links)

### ISSUE THREAD

**Issue by xloem** [cometbft/cometbft#1595]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
fe4894f4482b49c9bfe93382a2409f26c6f3f712 (v0.34.29)

**Have you tried the latest version**: yes/no
no

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/cosmos/gaia

**Environment**:
- **OS** (e.g. from /etc/os-release): RHEL 7.9 (fedora-like)
- **Install tools**: go 1.20.10 linux/amd64
- **Others**: I'm blocksyncing a node over a slow mobile phone, connecting to just one peer atm, just to get some test data, not to sync. I don't presently have a better system to test on. I have been trying different changes to the source files to run via this phone better.

**node command runtime flags**: gaiad start --x-crisis-skip-assert-invariants

### Config

```
max_num_outbound_peers = 1
send_rate = 76800
recv_rate = 640000
handshake_timeout = "400s"
dial_timeout = "200s"
chunk_request_timeout = "100s"
```

### What happened?
When I connect to peers, they are marked invalid after retrieving blocks, and dropped. A little diagnosis shows that this happens a certain way:
1. Many block requests are sent to the peer out of order.
2. Before the block that is next in height is received, request timeouts begin to be hit, because the blocks are delivered in reply so slowly.
3. When a request timeout is hit, the [requester object is reset](https://github.com/cometbft/cometbft/blob/fe4894f4482b49c9bfe93382a2409f26c6f3f712/blockchain/v0/pool.go#L632).
4. When the peer gets around to delivering a block after the timeout, [the comparison with the request](https://github.com/cometbft/cometbft/blob/fe4894f4482b49c9bfe93382a2409f26c6f3f712/blockchain/v0/pool.go#L543) then fails because it was reset, and the peer is [disconnected as invalid](https://github.com/cometbft/cometbft/blob/fe4894f4482b49c9bfe93382a2409f26c6f3f712/blockchain/v0/pool.go#L277).

### What did you expect to happen?
Whatever happens, the peer should not be disconnected as invalid for correctly delivering queued blocks when the local node is the slow one.

It looks to me like the peer's request object should not be reset if it may still have a block queued, but I have not fully understood the source at this time. The logic might be simplified if valid and helpful blocks were accepted whether or not they came from the most recently requested peer.

It might make sense to reset all timeouts associated with a peer whenever the peer delivers any block. It could also make sense to make the number of queued requests and the timeout time configuration parameters, and even advise the user on the number that were successful once a timeout is hit.

From the perspective of running a slow node against a single peer, it would be much more productive to issue the requests in sorted order somehow rather than randomly. As it stands, with many hundreds of requests queued the node only gets its next height pretty rarely before the peer is kicked due to this bug, despite receiving many many good blocks. It is quite easy to close the client in frustration, thinking nothing is happening, since there is only informational logging when the block for the next height comes in.

### How to reproduce it
Blocksync a node with one live peer that is very slow to communicate with. This could probably be simulated by pausing the peer with e.g. ^Z after connecting to it.

### Logs

```
7:51AM INF service start impl="Peer{MConn{93.115.25.106:26656} 7dd34d8d3880bc48eff3e47b941d06bd1941a962 out}" module=p2p msg={} peer={"id":"7dd34d8d3880bc48eff3e47b941d06bd1941a962","ip":"93.115.25.106","port":26656}
7:51AM INF service start impl=MConn{93.115.25.106:26656} module=p2p msg={} peer={"id":"7dd34d8d3880bc48eff3e47b941d06bd1941a962","ip":"93.115.25.106","port":26656}
7:51AM INF invalid peer blockHeight=17600139 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962
7:51AM ERR Stopping peer for error err="error with peer 7dd34d8d3880bc48eff3e47b941d06bd1941a962: invalid peer" module=p2p peer={"Data":{},"Logger":{}}
7:51AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"7dd34d8d3880bc48eff3e47b941d06bd1941a962","ip":"93.115.25.106","port":26656}
7:51AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"7dd34d8d3880bc48eff3e47b941d06bd1941a962","ip":"93.115.25.106","port":26656}
```
I added additional logging output (removed above) to see the cause of the issue. Below is an example from the time region above. The log statements I added show the bpr.reset() call after some block requests. When block 17600139 comes in, the request has been reset, and the peer is disconnected.
```
7:51AM INF requesting block height=17600190 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962
7:51AM INF requesting block height=17600139 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962
...
7:51AM INF v0 AddBlock blockHeight=17600190 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962                   
7:51AM INF requesting block height=17600221 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962                   
...
7:51AM INF resetting bpr height=17600139 module=blockchain oldblock=null oldpeer=7dd34d8d3880bc48eff3e47b941d06bd1941a962     
...
7:51AM INF v0 AddBlock blockHeight=17600139 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962
7:51AM INF invalid peer blockHeight=17600139 module=blockchain peer=7dd34d8d3880bc48eff3e47b941d06bd1941a962
```

### `dump_consensus_state` output

Not a consensus bug.

### Anything else we need to know

In engaging this issue I was surprised to note that the number of queued requests to a peer will rise significantly with the value of `maxTotalRequesters` in this file even if `maxPendingRequestsPerPeer` stays the same number.

I'm having some success working around this issue by dropping `maxTotalRequesters` and `maxPendingRequestsPerPeer` and raising `requestRetrySeconds`, although doing this requires recompilation.

**Comment by adizere** [comment]
Thank you @xloem for filing this issue report. Recent changes/refactoring have likely addressed this issue. Please upgrade to a newer version, and let us know if the problem is still there.
