### ISSUE TITLE
Terrible performance of psql indexer

### ISSUE THREAD

**Issue by k0marov** [cometbft/cometbft#1618]
### Setup

v0.38.0

**Have you tried the latest version**: yes

**ABCI app** kvstore modified to accept json as values. 

**Environment**:
Linux 

### Config 

indexer = "psql" 
psql-conn = {url of my local postgresql}

### What happened?

When I benchmark my app, indexing events takes a lot more time than expected: ~20 seconds for each block containing 5000 transactions. Every transaction is ~900 bytes in size. So 5MB of data takes 20 seconds for indexing (with indexer disabled or using "kv" indexer this indexing time period is not noticeable), This seems not right. 

### What did you expect to happen?

Transactions get indexed with acceptable speed. 

### How to reproduce it

I wanted to test the performance of psql indexer, so I modified the kvstore app to accept json values after the "=" character. 
In FinalizeBlock() I added tx events for each of the fields in the provided transactions. 
I suppose providing the full source code for that here is not helpful. 

Then, I ran a benchmark that executes transactions with random keys and values being random json objects with 20 string fields. Such objects are about 900 bytes in size. 

So for every transaction there was 20 tx events. 

And it turned out that the app was slowed down unacceptably. For every block containing 5000 transactions, the indexing added 20 seconds of waiting. This limits TPS to 200 tx/sec at max. 

### Logs

```
I[2023-11-15|15:50:22.258] received proposal                            module=consensus proposal="Proposal{86/0 (3AE8B9778CD667089C4862568EC2971DCA96A406465185DEB7949F98B170D464:78:8724A5D08004, -1) E5173B6F4A00 @ 2023-11-15T12:50:22.244325794Z}" proposer=901352D607C0FA0DB9840AD958BAAF9D395D69D1
I[2023-11-15|15:50:22.897] received complete proposal block             module=consensus height=86 hash=3AE8B9778CD667089C4862568EC2971DCA96A406465185DEB7949F98B170D464
I[2023-11-15|15:50:22.926] finalizing commit of block                   module=consensus height=86 hash=3AE8B9778CD667089C4862568EC2971DCA96A406465185DEB7949F98B170D464 root= num_txs=5000
I[2023-11-15|15:50:23.206] finalized block                              module=state height=86 num_txs_res=5000 num_val_updates=0 block_app_hash=
I[2023-11-15|15:50:23.206] executed block                               module=state height=86 app_hash=
I[2023-11-15|15:50:23.340] committed state                              module=state height=86 block_app_hash=
I[2023-11-15|15:50:25.133] Timed out                                    module=consensus dur=3s height=86 round=0 step=RoundStepPropose
I[2023-11-15|15:50:45.782] Timed out                                    module=consensus dur=-21.855864942s height=87 round=0 step=RoundStepNewHeight
I[2023-11-15|15:50:45.785] indexed block events                         module=txindex height=86
```

### Anything else we need to know

I guess that indexing is so slow because for every tx event I issue, CometBFT executes a separate call to PostgreSQL. Maybe all of events that are indexed in a block should be sent inside one big transaction? I'll be glad to make a pull request with such modification.

**Comment by thanethomson** [comment]
If you're using v0.38, I would recommend taking a look at the `v0.38.x-experimental` branch which includes an implementation of [ADR 101](https://github.com/cometbft/cometbft/blob/main/docs/architecture/adr-101-data-companion-pull-api.md). This interface was designed specifically to offload indexing to an external service such that it can be indexed optimally (which will eventually become the default for Comet, as indexing of events is an application-level concern).

**Comment by k0marov** [comment]
Thanks! Can you please estimate when this functionality will stop being experimental?

**Comment by melekes** [comment]
> If you're using v0.38, I would recommend taking a look at the `v0.38.x-experimental` branch which includes an implementation of [ADR 101](https://github.com/cometbft/cometbft/blob/main/docs/architecture/adr-101-data-companion-pull-api.md). This interface was designed specifically to offload indexing to an external service such that it can be indexed optimally (which will eventually become the default for Comet, as indexing of events is an application-level concern).

Will "Data Companion" allow us to remove built-in kv and Postgresql indexers eventually?

**Comment by thanethomson** [comment]
> Thanks! Can you please estimate when this functionality will stop being experimental?

It's going to land in Comet v1, for which we'll be cutting an alpha release in the next few weeks if all goes well. Final release will be early 2024.

If we get enough feedback, however, on the stability and performance of the API on the `v0.38.x-experimental` branch we'll consider releasing it as part of the non-experimental v0.38 series.

> Will "Data Companion" allow us to remove built-in kv and Postgresql indexers eventually?

Yes, that's one of the primary goals of the API. Technically the path to removing them should look something like:
1. Integrators start building out purpose-built, optimized data companions that handle indexing outside of Comet.
2. Applications start providing their own APIs for emitting application event data as it's committed.
3. Data companions' sources are switched out from just Comet to Comet + the application (i.e. the companions get application event data from the application instead of Comet, and they just get block/transaction data from Comet).
4. We can remove any notion of application events entirely from Comet, given that they're an application-level construct that the consensus engine shouldn't have to care about.

**Comment by melekes** [comment]
> I'll be glad to make a pull request with such modification.

please do 🙏
