### ISSUE TITLE
Upgrade to Go 1.19

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#174]
Following from #173, at what point should we consider upgrading the codebase and our tooling to use Go 1.19?

And in general, what are our criteria for updating to support a new version of Go? On the Rust side of development at Informal, we always update to the latest stable version of Rust the moment it's released.

PRs addressing this
* #206 
* #208 
* #360

**Comment by andynog** [comment]
The SDK updated to go 1.20 as of last week and on the README it says it requires 1.20+
https://github.com/cosmos/cosmos-sdk/commit/ad847c4e4d1d33a12f7409d482834e6522910177
