### ISSUE TITLE
storage: add version to each DB

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#1822]
### Summary

Add a version to each DB, so if/when the schema changes, we can rely on it

### Problem Definition

Currently, the DBs (block, evidence, state, light) are not versioned. If the schema changes, there's no way to check what version you're running besides parsing data. In #1814, I will have to assume the data format, but that's not ideal from multiple perspectives.

### Proposal

Add a version key-value pair to each DB (e.g., `version=1`). Upon a startup, check that the version in the code matches the one from the DB. If no version is found, assume 1 (initial version).

**Comment by sergio-mena** [comment]
I support this. Will also likely improve troubleshooting.
The only caveat from my side: the solution's design must take into account what happens with old versions of the software that predate this. We should try to avoid breaking those.
