### ISSUE TITLE
ABCI++ should expose evidence to application

### ISSUE THREAD

**Issue by SilentCicero** [cometbft/cometbft#1837]
### Summary

Presently, the ABCI application only provides metadata around slashing in finalize block, but does not provide the evidence itself. Things like equivocation evidence or light client attack evidence should be made available somehow to the application. This limits the context of the behavior, which also makes scoring or repeated scoring of the offence more difficult.

Right now, the only way to get this evidence is by injecting additional code into the client internals.

### Problem Definition

Equivocation evidence is not made present in the ABCI application.

### Proposal

Include equivocation evidence in the ABCI application under misbehavior.

**Comment by melekes** [comment]
> This limits the context of the behavior, which also makes scoring or repeated scoring of the offence more difficult.

Could you please explain this further? What information are you missing exactly?

**Comment by SilentCicero** [comment]
@melekes presently, the ABCI application interface gives you some facility in the block finalization stage to punish misbehavior from the validators. However, the evidence presented is not rich. It doesn't provide things like the literal equivocation evidence, just that equivocation has occurred.

Because of this, it would be ideal to fully expose the entirety of the equivocation evidence, as it may impact how the application would like to punish the validator.

The code in question is here:
https://github.com/cometbft/cometbft/blob/v0.38.x/abci/example/kvstore/kvstore.go#L201

Ideally, this area would provide more rich data. I understand you can always fork and break the ABCI app system and add this additional feature in, but ideally, just making it available through ABCI would be very easy to do and helpful.

Apologies in advance if I'm missing something or if there was some way to get that voting data, but I didn't see any.

**Comment by melekes** [comment]
To clarify, you want the actual `Vote`s exposed to the ABCI application, right?

**Comment by cason** [comment]
What is exported to the application via ABCI are [Misbehavior](https://docs.cometbft.com/v0.38/spec/abci/abci++_methods#misbehavior) instances. The (full) evidence has a method, defined on this [interface](https://github.com/cometbft/cometbft/blob/main/types/evidence.go#L24) that translates the evidence to a summary offered to the application.

This is not the only case in which we provide to the application a simplified version of a consensus field. Another example is [VoteInfo](https://docs.cometbft.com/v0.38/spec/abci/abci++_methods#voteinfo), a simplified version of a Commit vote.

I am not really a fan of this approach (as I find it complex), but this topic has been already discussed when specifying ABCI++ and the decision was to make the least consensus-specific information available to the application as possible.

Having said so, I think this is a valid request but it goes in the opposite direction as the one taken when evolving ABCI.

**Comment by sergio-mena** [comment]
@cason 100% agree

**Comment by melekes** [comment]
Closing for reasons explained in https://github.com/cometbft/cometbft/issues/1837#issuecomment-1904353543. @SilentCicero please let us know if we can help with anything else.
