### ISSUE TITLE
Backport batch signature verification work to v0.37.x

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#1839]
## Feature Request

If possible, it would be nice to get the batch verification speedups of these PRs [1](https://github.com/cometbft/cometbft/commit/2d1ada4d52dfcabb5fad8e6c1e683afce2eae1e6), [2](https://github.com/cometbft/cometbft/pull/1750) into v0.37.x

The motivation for this is the blocksync speedups mentioned in #1830.

However I totally understand if this is deprioritized in favor of other performance work, and anticipation of most cosmos chains upgrading to v0.38.x soon.

**Comment by melekes** [comment]
hey @ValarDragon 👋 When does Osmosis plan to upgrade to CometBFT v0.38?

**Comment by ValarDragon** [comment]
As far as I understand, upgrading to CometBFT v0.38 requires to update to SDK v50

As with everyone, were a bit hesitant to be the first to upgrade right now. In particular, we just had a bunch of issues in our last upgrade. To be fair 80% of the issues were oneof:
- problems that have existing in versions of the cosmos stack (not unique to Osmosis, just coming up now)
- bugs in our code
and unrelated to the new SDK/Comet version.

But were trying to take some time to get these stack issues / performance items mitigated well before moving onto SDK 50 / Comet v0.38. Right now I'd guess that this means March for upgrading unfortunately

**Comment by sergio-mena** [comment]
We can backport batch verification to `v0.37.x-experimental`, if that helps.

**Comment by melekes** [comment]
Closing due to no response.

**Comment by ValarDragon** [comment]
Sorry for the late reply, would like this to be backported if possible. If thats not ok, thats fine

**Comment by czarcas7ic** [comment]
We are backporting to our fork, so we should be good to go!

**Comment by adizere** [comment]
Hi @czarcas7ic if you're finding the optimizations helpful, we would be glad to bring them into mainline Comet eventually.
