### ISSUE TITLE
Sync missing state trees of past blocks when change pruning option to nothing

### ISSUE THREAD

**Issue by zsystm** [cometbft/cometbft#1875]
### Summary

When operating an archive node based on cometbft, if a state tree goes missing due to even a single mistake in adjusting the pruning option, it becomes very difficult to recover.

### Problem Definition

Currently, it seems that the only options are to sync from the beginning again or to restart the node with a snapshot from another archive node.

This is becoming a significant inconvenience.

### Proposal

I would like to suggest a feature where, if a state tree goes missing due to a configuration error during the operation of an archive node, the node could be restarted with the corrected settings, and a process would be added to sync the missing state tree.

I believe that this feature would greatly reduce the resources needed to operate an archive node and would have a positive impact on the ecosystem.

if it is make sense to you guys, I'll update more details on this proposal.

**Comment by melekes** [comment]
> I would like to suggest a feature where, if a state tree goes missing due to a configuration error during the operation of an archive node, the node could be restarted with the corrected settings, and a process would be added to sync the missing state tree.

And how exactly would that happen? I mean, syncing the missing state tree?

> I believe that this feature would greatly reduce the resources needed to operate an archive node and would have a positive impact on the ecosystem.

Could you explain further? If the bad experience is caused by `a configuration error`, which should not often happen, how will adding the proposed feature  `greatly` reduce the resources?

**Comment by cason** [comment]
Not sure if I understood what is a "state tree" here. This looks like as the way the application (e.g., by using the SDK) stores the state of an application. Comet does not manage the application storage, it only keeps track of the application hash (`app_hash` field returned by the application as in https://docs.cometbft.com/v0.38/spec/abci/abci++_methods#parameters-and-types-5).

**Comment by adizere** [comment]
Hi @zsystm thanks for reporting!

If this is still of interest, let us know with the additional details asked above. Closing as stale until further info comes through.
