### ISSUE TITLE
[Feature]: signal to application when sync vs consensus

### ISSUE THREAD

**Issue by tac0turtle** [cometbft/cometbft#1880]
### Summary

There are features we can implement to accelerate syncing and features that enable different sort of things in the application if we are aware of which state we are in, sync/replay or consensus. 

Some of the features to accelerate do not produce a hash on every block while syncing. Different levels of verification can be done here as well around other parts of the stack. 

For teams like berachain they run different operations when in sync/replay mode, currently they are attempting to hack it into abci to get the functionality they would like. 

### Problem Definition

The application is unaware if the node is replaying or consensus. 

### Proposal

Introduce a field in abci, it could be in FinalizeBlock, that would signify if a block is being replayed or if its part of consensus,

**Comment by facundomedica** [comment]
Would it make sense to do this by checking if the validator is present in `DecidedLastCommit` in `FinalizeBlock`?

**Comment by tac0turtle** [comment]
> Would it make sense to do this by checking if the validator's vote is present in `DecidedLastCommit` in `FinalizeBlock`?

do votes not appear when in replay mode?

**Comment by tac0turtle** [comment]
ah yea similar, sorry searched around and didnt see anything. Ill close this

**Comment by sergio-mena** [comment]
Yeah, some other teams have asked for this in the past (Vega, Vocdoni), so it's likely to happen in the short-to-mid term
