### ISSUE TITLE
Better docs or easier facility to remove transaction from cache

### ISSUE THREAD

**Issue by SilentCicero** [cometbft/cometbft#1898]
### Summary

I couldn't find an easy way either through looking at the docs or code to remove a transaction from the cache. Namely, I have a valid transaction at the CheckTx stage, which then gets declined at the PrepareProposal stage. It's not easy to tell the user/transactor, "hey, this transaction is not going to be included".

Instead, I had to use an application memory map `ignoreTxs` to ignore that transaction, and promt a special new error at CheckTx, which seemed to solve the issue.

Ideally, there would be some nice method or facility to remove that transaction from the cache. I didn't see one in any docs.

### Problem Definition

Have an easy method to remove a transaction from the cache that passes CheckTx initially.

### Proposal

Perhaps extend the req.Txs object include an `.Ignore()` method, which would then pull the tx out of the mempool or cache.

**Comment by lasarojc** [comment]
Could you clarify the scenario? Are you using the SDK? The SDK mempool? Assuming here that you are not using the SDK. 
If your transaction passed the CheckTx, it was added to the mempool and will at some point be offered to the application in PrepareProposal. At this point it is up to the application to decide if the transaction will be removed from the block proposal or not; if it removes the transaction, it has a chance to inform the app at this point or make a note to do it later.
Upon deciding the heigh, the transactions will be rechecked and if the particular tx is no longer good, the application has a chance to reject it and, again, make a note to tell the application later. Does this solve the problem for you?

**Comment by adizere** [comment]
Closing as stale.
