### ISSUE TITLE
TestTransportMultiplexAcceptNonBlocking is flaky

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#1914]
### Setup

Using the CI system

### Config

CI

### What happened?

The same code resulted in different results.  

### What did you expect to happen?

Tests should react the same way when run with the same code. 

### How to reproduce it

Work on comet for a bit and it seems this will pop up. 

### Logs

**failure**
https://github.com/cometbft/cometbft/pull/1906/commits/ed57549f488e8d89917dcd6d0bf8f6d915a01c12

**add a test godoc to fix**
https://github.com/cometbft/cometbft/pull/1906/commits/d2e490917192336ee9c435187c1e6497dd879020

### `dump_consensus_state` output

Not applicable

### Anything else we need to know

We should hunt flaky tests so they don't exist.  

flaky tests time usage * developers * hourly rate = cost of flaky tests

**Comment by faddat** [comment]
Is interesting.

So I have a link to a failure but I don't doubt that you ran it a thousand times. I guess what I can tell you is that I'm not sure that I fully understand what is making these tests flaky, for example, is it the test, or is it the underlying code. Some of it seems to do with timing and in the cases where it's just timing and nothing else. I'm tending toward blaming the test.

**Comment by sergio-mena** [comment]
Note that `master` is an abandoned branch, only present for developers' reference on retracted branches`v0.35.x` and `v0.36.x`. So no effort should be spend on fixing anything on `master`.

The current development branch is `main`, where those efforts should focus.
