### ISSUE TITLE
Can't clone repo

### ISSUE THREAD

**Issue by kellybasil185** [cometbft/cometbft#1919]
### Setup

**CometBFT version** (v0.38.0 and v1.0.0-alpha.1):

**Have you tried the latest version**: yes

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04.3

**Error message while installing:
 git clone https://github.com/cometbft/cometbft.git
Cloning into 'cometbft'...
remote: Enumerating objects: 175745, done.
remote: Counting objects: 100% (15953/15953), done.
remote: Compressing objects: 100% (1656/1656), done.
error: 4020 bytes of body are still expected0 MiB | 66.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

![image](https://github.com/cometbft/cometbft/assets/99088537/a3213495-3bc2-4128-bcf5-fee19ea91321)

-->

**Comment by faddat** [comment]
friend, that is your internet connection, not the repo.

Try like:

```bash
cd ~/
rm -rf cometbft
git clone https://github.com/cometbft/cometbft
```

**Comment by cason** [comment]
I can confirm that 

` git clone https://github.com/cometbft/cometbft.git`

works in my setup. Can you confirm that the error is still present?

**Comment by faddat** [comment]
@cason as someone with a sometimes so-so internet connection, I can say with certainty that what @kellybasil185 is experiencing is due to his internet connection flaking out in the middle of the download.

**Comment by melekes** [comment]
@kellybasil185 please let us know if you're still experiencing issues. Thanks 🙏
