### ISSUE TITLE
TestNodeNewNodeDeleteGenesisFileFromDB is flaky

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#1927]
## Bug Report

TestNodeNewNodeDeleteGenesisFileFromDB is flaky

### Setup

CI

### Config

CI

### What happened?

I added a godoc to make this pass

### What did you expect to happen?

Adding a godoc should not make this pass.

### How to reproduce it

Work on comet

### logs

#1925

**Comment by melekes** [comment]
Heads up. I will close individual test issues in favor of one tracking issue.
