### ISSUE TITLE
perf: Blocksync is double calling types.Block.ValidateBasic at costs to sync speed

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#1964]
## Feature Request

Block sync is double-calling types.Block.ValidateBasic, which re-hashes every transaction in a block. In a 100 block CPU profile sync on Osmosis, over a period with especially large blocks, we found that this was the cause of some notable overhead. (18 seconds out of 185 seconds over all processes, at least 70s of which were in non-blocking operations) Under normal block sizes, this time is lower but still high/worth speeding up. (4.1 seconds for 100 blocks)

![image](https://github.com/cometbft/cometbft/assets/6440154/05295faf-c2cf-4dd6-a22c-b24320dde813)

We should not be double verifying this.

### Summary

We are double verifying block hashes in block sync by calling this in two different spots: 
[ValidateMsg here](https://github.com/cometbft/cometbft/blob/main/internal/blocksync/reactor.go#L233-L237), which calls types.BlockFromProto which calls validate basic, and [types.BlockFromProto right here](https://github.com/cometbft/cometbft/blob/main/internal/blocksync/reactor.go#L245)

### Problem Definition

Speed up block sync

### Proposal

Do some mild API or order of operations changes to reuse the `types.BlockFromProto` result and only compute it once.

**Comment by faddat** [comment]
gonna check this out.

**Comment by faddat** [comment]
Got it :).

I think that this will make your flame graph much happier.

**Comment by melekes** [comment]
Thanks @ValarDragon ❤️ Definitely something we should fix
