### ISSUE TITLE
Consider exporting error for `ErrTimedOutWaitingForTx`

### ISSUE THREAD

**Issue by rootulp** [cometbft/cometbft#2014]
## Context

Celestia maintains a fork of CometBFT in [celestia-core](https://github.com/celestiaorg/celestia-core). We're considering exporting an error so that downstream consumers can use it rather than checking for an error based on string. See https://github.com/celestiaorg/celestia-core/pull/1169

## Problem

https://github.com/cometbft/cometbft/blob/00e5270ccdcc3fe45fe742006320c6977ee11b98/rpc/core/mempool.go#L148 defines an ad-hoc error that can't be used by downstream consumers. Ideally this error was exported from CometBFT so that downstream consumers can use it in `errors.Is`

Celestia-core can workaround this by exporting it but that introduces a divergence from this repo.

## Proposal

1. Export an error for `ErrTimedOutWaitingForTx`. Basically https://github.com/celestiaorg/celestia-core/pull/1169
2. If there are other un-exported errors, consider exporting them.

**Comment by melekes** [comment]
Hey @rootulp 👋 We already have an issue for this: https://github.com/cometbft/cometbft/issues/1140. If you want to help upstreaming the above changes, let us know (feel free to open a PR).

**Comment by distractedm1nd** [comment]
@melekes The referenced error is not a named error, so the already merged PR to export errors from mempool does not include it. Is the issue you linked only for exporting errors or should I bring it up there as well?
