### ISSUE TITLE
Community call 1/11/2024: Databases & db perf

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#2023]
Please correct any of these items if they're wrong:

* sqlite is off the table for now
* there's a desire to move to a single kv store:
  * goleveldb - informal will optimize and champion this kv store
    * Pros
      * most chains already use this
    * Cons
      * goleveldb seems to have a scary performance drop as the number of keys and values increases      
  * pebbledb - notional will optimize and champion this kv store
    * Pros
      * seems fastest in the widest variety of real world situations
    * Cons
      * when there are not many keys or the values or small, goleveldb is faster    
   
    * for users of  rocks, the migration is built into pebble (I've done it and it works but of course this is not a guarantee)
* badger, bolt, and cleveldb are safe to drop but only if there's a migration path because we don't want to disturb legacy users
* flaky test detection work was helpful and if I did stuff like that in the future, that'd be a good thing
* **query** best way to test relative db perf, in an exclusively comet context?  (eg: instead of doing benchmarks only in the comebft-db library)

thanks and again -- if any of that is wrong -- please let me know

**Comment by adizere** [comment]
This is excellent! I'd only add that we care about having easily reproducible and comparable results. So we want to tackle https://github.com/cometbft/cometbft/issues/63 towards being able to make a clear assessment of "X is best than Y as a storage backend". More specifically, first step would likely be this one:  https://github.com/cometbft/cometbft/issues/46

**Comment by faddat** [comment]
thanks for the feedback!

**Comment by adizere** [comment]
Hey @faddat did you have a look at the recent [report on storage we wrote](https://github.com/cometbft/cometbft/blob/main/docs/references/storage/README.md) ? We introduced this in #2596.

The report is not so much about DB performance, but storage efficiency.

**Comment by adizere** [comment]
Closing with #2596. We need to consider what would be good next steps.
