### ISSUE TITLE
spec: Clearly document when an app is expected to persist state

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#203]
Per a recent conversation with @hdevalence regarding the ABCI `InitChain` request, it isn't 100% clear to app developers as to what to do with multiple such `InitChain` requests in the case that the interaction between the node and the app fails before the first `Commit` call for the first block.

We should clarify in the spec that our crash-recovery model requires both the app and CometBFT to crash together, and that the app is expected to persist state only upon calling `Commit`.

This should be clear in the specs on all release branches.

**Comment by jmalicevic** [comment]
Closed by #469
