### ISSUE TITLE
[ABCI]: replace int64 with uint64 where possible 

### ISSUE THREAD

**Issue by tac0turtle** [cometbft/cometbft#2059]
### Summary

Throughout the years there have been a few attempts to [migrate tendermint (now cometbft) to uint64](https://github.com/tendermint/tendermint/issues/731). Some of these attempts fell through due to the amount of changes. This issue is not about the repo but about ABCI. It would be nice to have all the values that can not be negative be transitioned to uint64. We in the Cosmos SDK, do overflow and underflow checks in order to work with ABCI. This isnt a problem today but a quality of life improvement would be to change those values to uint64

### Problem Definition

ABCI uses int64 instead of uint64, this forces applications to handle negative cases or the application opts to use int64. In the Cosmos SDK we are aiming to use uint64 every where we can, for this to happen we need to be defensive when writing translations between int64 and uint64. 

### Proposal

Migrate all values in ABCI which use int64 to use uint64 if they do not need negative numbers.

**Comment by adizere** [comment]
Hey @tac0turtle we discussed this briefly in the team. There's hesitation to move to uint, on the same grounds as the prior decision documented here: https://blog.cosmos.network/choosing-a-type-for-blockchain-height-beware-of-unsigned-integers-714804dddf1d

**Comment by tac0turtle** [comment]
i guess tendermint and comet will be the only consensus protocol in blockchain written with ints. When this came up in the past with the previous comet team even they were shocked int64 is used. 🤷

**Comment by tac0turtle** [comment]
sorry wrong button. this shouldnt bother us in the Cosmos sdk pre soon as comet is abstracted enough

**Comment by adizere** [comment]
Closing as not planned. We might reconsider later.
