### ISSUE TITLE
Change the default number of test runs for all releases to 5

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#2071]
I've reduced the time for a test run from max of 15 minutes to max of 210 seconds, without impact on the efficacy of tests. 

I suggest that we run all tests five times for each PR coming into main until tests reliably pass.  We want to be able to use CI's green check mark as a reliable indicator.

Currently we've got an issue with tests flaking out.

I think that a simple way to resolve this would be to replicate this PR:

* https://github.com/cometbft/cometbft/pull/2005 

But we could use github's `cron` feature.  This way, there'd be some certainty provided for downstream users that **if run repeatedly** the tests work.

**Comment by melekes** [comment]
I agree, but we also want to continue merging PRs, and fighting flaky tests will drastically slow us down (we're a very small team, unfortunately). That said, I appreciate all your work 🙏 Let's work together to fix the remaining flaky tests eventually.
