### ISSUE TITLE
PBTS: do we need the `Proposal` when the proposed block received a Polka?

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#2119]
_Originally posted by @cason in https://github.com/cometbft/cometbft/pull/2018#discussion_r1458778006_:

      A note to remember: we are forcing a `Proposal` to be received to run the prevote logic. While this is necessary when POLRound == -1, it might not be otherwise.

The PBTS-enabled consensus code adds the requirement of receiving and accepting a `Proposal` to precommit a block:

https://github.com/cometbft/cometbft/blob/1733219c2fec4be370b672081f8daf84b768a0e9/internal/consensus/state.go#L1619-L1621

This requirement is not present in the original code, in the `main` branch,  where the absence of a valid proposal (`cs.Proposal`) does not cause the node to precommit nil. The reason for which is that a node may realize that a proposal block has become valid, because it received a Polka, in the case the `blockID` in the following code:

https://github.com/cometbft/cometbft/blob/1733219c2fec4be370b672081f8daf84b768a0e9/internal/consensus/state.go#L2374-L2376

What happens here is that the node starts "looking" for this block,  by updating its `cs.ProposalBlockParts` field. There are two possibilities to consider here:

1. The node received a `Proposal` for a block that doesn't match the `blockID` that became valid. This happens when a Byzantine proposer produces multiple proposals in a round. This is not the case considered int this issue, since the `cs.Proposal` should be set, probably for a different block, but the code doesn't care.
2. The node has not received any valid `Proposal`, so it is not building any block. This is the scenario addressed here.

The general point here is that if we received a Polka for a block, it does not matter the (first valid) `Proposal` we received, not even if we have not received any `Proposal`. This block has been deemed valid by `2/3+` validators, so there is no reason for not precommiting it. Note that we use the same rationale in PBTS when we receive a `Proposal` backed by a Polka in a `POLRound`: we don't check the block time again, as it was accepted by a quorum of validators.

With this in mind, this additional check added to the `precommit` round step does not make sense:

https://github.com/cometbft/cometbft/blob/1733219c2fec4be370b672081f8daf84b768a0e9/internal/consensus/state.go#L1625-L1628

While it is probably the only reason for requiring `cs.Proposal != nil` to get to this point. My proposal is then:

- [x] Remove the `cs.Proposal != nil` condition to precommit a block (`cs.enterPrecommit`)
- [x] Remove the `cs.Proposal.Timestamp.Equal(cs.ProposalBlock.Header.Time)` check at the same step

**Comment by sergio-mena** [comment]
For the record, I had the concern that, if we remove the checks for `nil` we might risk calling `ExtendVote` with a `nil` block. After synchronous discussion with @cason , I'm 100% convinced this is not a problem here, because of the (weird) implementation of `HashesTo`.
