### ISSUE TITLE
err="Trying to commit a discarded txn"

### ISSUE THREAD

**Issue by arivarasanka** [cometbft/cometbft#2126]
### Discussed in https://github.com/cometbft/cometbft/discussions/2125

<div type='discussions-op-text'>

<sup>Originally posted by **arivarasanka** January 25, 2024</sup>
Hi,

I had a blockchain Application implemented in Tendermint. For official reasons, I had to change it to cometBFT. But when I try to implement the cometBFT version, I am getting the following error.

> node3  | E[2024-01-25|11:24:02.484] client error during proxyAppConn.CommitSync  module=state err="Trying to commit a discarded txn"
> node3  | E[2024-01-25|11:24:02.485] CONSENSUS FAILURE!!!                         module=consensus err="failed to apply block; error commit failed for application: Trying to commit a discarded txn" stack="goroutine 252 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:800 +0x46\npanic({0x115a980?, 0xc011a1e960?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc000147180, 0x3)\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1779 +0xda5\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc000147180, 0x3)\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1681 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1616 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc000147180, 0x3, 0x0)\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1654 +0xc5f\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc000147180, 0xc004befd40, {0xc014a323c0, 0x28})\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:2323 +0x1d4d\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc000147180, 0xc004befd40, {0xc014a323c0?, 0xc005e17c08?})\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:2055 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc000147180, {{0x171b840, 0xc004a40a88}, {0xc014a323c0, 0x28}})\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:928 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc000147180, 0x0)\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:835 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 148\n\t/home/arivarasan/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:397 +0x10c\n"

One of my observations is that, after this error, the CheckTx function is called, but not the FinalizeBlock function. So, no blocks are formed after this error but transactions are received and checked. I can not understand what is happening here. Let me know for more details.

**Comment by faddat** [comment]
If I were you what I would do is actually try to find the source of the error message, I'm happy to help with it but basically what you should be doing is trying to figure out under what circumstances you might see that error message.

Are you actively using ABCI Plus Plus?

One other thing is that I did notice that you're using a deprecated version of the software.

I would strongly recommend that if you're using the 38 series, that you use v0.38.5

**Comment by arivarasanka** [comment]
@faddat Thank you. I just wanted to know if I am missing something obvious. I am investigating further and I will ask you if and when I have something specific.

**Comment by faddat** [comment]
sure :).

I think the obvious item is the version of comet, and after you've tried a newer comet let us know if the issue is still happening.

**Comment by cason** [comment]
> err="failed to apply block; error commit failed for application: Trying to commit a discarded txn"

This error is produced by the application, not by CometBFT. Are you using the SDK? If so, the error is probably produced by them.

**Comment by arivarasanka** [comment]
Thank you so much for all your comments. It was a silly bug. I had committed the transactions in FinalizeBlock() Function, but CometBFT has added a commit at the return statement of the Commit() function too, which I didn't notice. I made it nil and the code it working fine now.
