### ISSUE TITLE
CVEs for security

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#2131]
So I think that, is widely used enough that we should really be looking to third party vulnerability distribution systems, like cve.

This could eliminate certain very serious conflicts of interest that I believe that we saw in the reporting of P2P storms. The CVE program is to my knowledge run by the United States department of commerce and distributes alerts much more widely than we can. Given that we do have such a large user base for the software, I believe that this is a good step forward.

Please note that the conflict that I'm speaking of has absolutely nothing to do with financial matters except of course for wasted time. I am talking about a conflict of interest well I mean even with severity rating, there is simply no difference between the last two security issues on this repository, they can both stop chains.

![Screenshot_20240125-154233](https://github.com/cometbft/cometbft/assets/7142025/5125ce63-3ea3-4db8-9254-f5c1620bedc1)

I really don't know whose interests are served by presenting these issues as materially different in terms of risk profile but that's pretty much got to be the case, I can't think of any other reason why they would be so dramatically different.

So let's begin to file CVE, which will have greater reach and ... Well, you know -- likely the department of commerce is more credible than the group currently determining severity.

**p2p storms wasn't triaged correctly, and if we're to keep using CometBFT, we need to stop pretending as I strongly doubt a low severity issue would be driving the development agenda**

### note

countless attempts to contact both Informal Systems and Amulet concerning the lack of understanding demostrated by both teams have failed.

The Notional name was added to the p2p-storms related security report containing 1/18 of the items we reported without Notional's approval.

We have, and desire, no affiliation with:

* https://github.com/cometbft/cometbft/security/advisories/GHSA-hq58-p9mv-338c

**Comment by adizere** [comment]
Great idea to look into CVE for better distribution, we'll raise it with our funding agency and do what we can. Closing the issue as it does not depend on our team, but the interchain stack-wide security process.

Re: other remarks, you're off track (again) by making unfounded accusation & harassment (again). I'm trying hard not to ban you, stop.
