### ISSUE TITLE
request for free software integration: coderabbit.ai

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#2153]
## Feature Request

I've been using coderabbit.ai at quicksilver and berachain, and I LOVE it.

Specifically, it provides summaries of PR's that are easy to review and can also make suggestions based on the contents of a PR.

### Summary

integrate the FOSS version of coderabbit.ai on cometbft and cometbft-db

### Problem Definition

Coderabbit.ai seems like it is entering "unfair advantage" territory and I'd like us to have that. 

### Proposal

hit up https://coderabbit.ai and let's use the version that costs $0 available to open source projects.

**Comment by adizere** [comment]
Would be down to pilot using this. I noted SDK team is also using it, will ask them for feedback.

**Comment by melekes** [comment]
> personally been ignoring it... it’s just too noisy
