### ISSUE TITLE
p2p: Switch.OnStop uses stale and already mutated PeerSet.List() which could have data race consequences due to a leaky abstraction of using .List()

### ISSUE THREAD

**Issue by odeke-em** [cometbft/cometbft#2158]
## Bug Report
The code in p2p/Switch.OnStop invokes sw.peers.List() per https://github.com/cometbft/cometbft/blob/f4d73cd5a091a997d1f040850710b6937e650125/p2p/switch.go#L251 
and if we look at the code for .List() https://github.com/cometbft/cometbft/blob/f4d73cd5a091a997d1f040850710b6937e650125/p2p/peer_set.go#L153-L156 which returns a copy of the slice while under a lock but after handing it over, it is no longer under a lock and is modified by .Remove() which causes .OnStop() to read stale data.

I found this problem while working on the correct fix for https://github.com/cometbft/cometbft/issues/2157 in which the correct way to shorten a slice is to ensure you insert a nil at the last element before reslicing to ensure that there are no references to it and that the backing array can be garbage collected i.e.

```go
endItem := slice[len(slice)-1]
slice[len(slice)-1] = nil // nil it so that it'll be garbage collected
```

I can reliably reproduce this issue when I apply the fix for the referenced issue

## Remedy
Check and ensure that the peer is non-nil.

**Comment by odeke-em** [comment]
And indeed, the data race is exposed in https://github.com/cometbft/cometbft/actions/runs/7692838534/job/20960454814?pr=2159 in which this code uses a stale version of the peerSet's list in https://github.com/cometbft/cometbft/blob/940378cf06ca1452c161a821cbe6ea1516268425/p2p/switch.go#L276-L281

**Comment by cason** [comment]
Indeed, we need to return a _copy_ of the list of peers here.

This method is actually called in several parts of the `p2p` package and needs to be reconsidered.
