### ISSUE TITLE
PBTS: should synchrony parameters be adaptive?

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#2184]
Original discussion: https://github.com/tendermint/spec/issues/371.

### Summary

The issue here is the possibility that the application configures bad (e.g., very conservative) time bounds, resulting in a chain that will halt as proposals will be rejected by all or most of correct nodes. This situation is hard to deal because the synchronous parameters are consensus parameters, which require committing blocks to be updated. Which might become unfeasible if consensus cannot progress due to bad parameters.

There are two synchronous parameters considered by PBTS: `PRECISION` and `MSGDELAY`. `PRECISION` should not be a problem here, as it restricts malicious nodes from proposing timestamps in the future. The `MSGDELAY` parameter, in its turn, restricts malicious nodes from proposing timestamps "too much in the past". The diagram below can be helpful to understand the use of these parameters to validate proposed timestamps:

![](https://github.com/cometbft/cometbft/raw/feature/pbts/spec/consensus/proposer-based-timestamp/diagram.png)

By setting a `MSGDELAY` parameter that is unrealistic (too low), a chain might end up in a situation in which correct validators reject proposals because their timestamps are deemed "too much in the past" because the observed propagation delay for proposals is larger than the configured `MSGDELAY` parameter.

### Adaptive `MSGDELAY`

The general idea is that we should increase the `MSGDELAY` parameter adopted by PBTS when we fail to accept proposals in multiple rounds, which may indicate that the value chosen for this parameter was inadequate. 

A possible analogy here is `timeout_propose`, the maximum expected delay for a proposed value (proposal and full block) to reach correct validators. Once a round fails on reaching a decision, the next round considers an increased delay `timeout_propose(round - 1) + timeout_propose_delta`, which is linearly increased until it represents the actual delay for delivering full proposals to correct validators. The same concept could be adopted for the `MSGDELAY` parameter.

The [original issue](https://github.com/tendermint/spec/issues/371) several approaches for adaptive synchronous parameters for PBTS. They include a round from which adaptations start being adopted, how we adapt the values (linearly, exponentially) etc. The implemented version (this [PR](https://github.com/tendermint/tendermint/pull/7739)) adopted an exponential increasing of `MSGDELAY` when more than `10` rounds are needed to decide on a value.

### Open questions

1. Do we need adaptive synchrony parameters?
2. If so, how and when we increase the value of `MSGDELAY`?
3. How we specify/document this approach, making it clear to external components which synchrony parameters were used to validate the timestamp of a given block

### Definition of Done

- [x] Mechanism to relax `timely` verification under certain circumstances is defined
- [x] #2432

Documentation:
- [x] #2452
   - ADR 112 describes the implementation of this mechanism
   - ~[PBTS runbook](https://github.com/cometbft/cometbft/blob/feature/pbts/docs/tools/proposer-based-timestamps-runbook.md) is updated accordingly~
   - [PBTS documentation](https://github.com/cometbft/cometbft/blob/feature/pbts/docs/core/proposer-based-timestamps.md) is updated accordingly
- [x] PBTS spec: #2318

**Comment by sergio-mena** [comment]
This also has to do with discussions we had with the dYdX team last summer. Their argument being that, if PBTS was to be implemented as an ABCI++ application, the PBTS `timely` predicate, if specified without an adaptive mechanism, would not fulfill `PrepareProposal`-`ProcessProposal`'s  coherence and determinism requirements.
Such discussion led to [RFC 105](https://github.com/cometbft/cometbft/blob/main/docs/references/rfc/rfc-105-non-det-process-proposal.md).

**Comment by sergio-mena** [comment]
This is an attempt to summarize our discussion during today's meeting on this subject (attendees @ancazamfir, @lasarojc, @glnro, @josef-widder):

We have extensively discussed the need for MSGDELAY parameter
* If we remove it, byzantine proposer can set block timestamps arbitrarily in the past up to the timestamp of the previous block
* Assume a relatively big value for MSGDELAY (e.g., 12 seconds for a chain with average block time of 6 seconds)
  * if we have a streak of several byzantine proposers proposing timestamps just 1 ms after the previous block, we may deviate from "real time" by more that 12 seconds at some point (>MSGDELAY).
  * it's true that if $f<1/3$ holds, this detachment of the chain from real time will be temporary (until an honest proposer proposes a block with a timestamp read from its synchronized clock)
* The main problem is that, MSGDELAY allows for simple and elegant formulas and properties to be expressed in the spec, as something can be said about _each_ block
  * However, if we need adaptive MSGDELAY, we can't guarantee strong properties in the spec or implement them in the code

Right toward the end of the meeting, a proposal was made
* @josef-widder said that a compromise would be to still be able to keep the formulas and properties as they are in the spec, but state that the hold for round 0 only
* If that is done on the spec side, then why not just implementing that (simpler than the solution implemented in 2022):
  * We use the spec's formulas for _timely_ in round 0
  * We remove MSGDELAY from the formulas for _timely_ in any round r > 0

What do folks think about this proposal for the spec/implementation? (@cason)

**Comment by josef-widder** [comment]
On the spec side, we should then have two sets of properties
- decision in round 0: `b.time` not too much in the future and not too much in the past
- decision in round >0: `b.time` not too much in the future

We should also add a paragraph to explain the scenario that 
- Byzantine proposers may slow down the progress of `b.time`: with every block the time in the block could just grow 1ms/6sec (assuming blocktimes of 6 seconds) if the decision is postponed to round 1
- this could accumulate if there are multiple byzantine proposers in successive heights (all going to round 1)
- but with the first correct successful proposer, we are back to having b.time synchronized to NTP time, again

**Comment by ancazamfir** [comment]
> * Byzantine proposers may slow down the progress of `b.time`: with every block the time in the block could just grow 1ms/6sec (assuming blocktimes of 6 seconds) if the decision is postponed to round 1

same (1ms/6sec) in round 0 if `MSGDELAY > blocktime`.

In general a byzantine proposer could:
- for round >0 can go back in time to  `time(h-1) + 1ms`
- for round 0 is `~min( time(h-1) + 1ms, time.now - MSGDELAY`)

It would be nice to have some plots showing worst block times with a network with `f` pbts-byzantine proposers.

**Comment by lasarojc** [comment]
Didn't get this piece

> for round 0 is ~min( time(h-1) + 1ms, time.now - MSGDELAY)

do you mean that it can go back in time to these values? If so then it should be max instead of min, correct?

**Comment by ancazamfir** [comment]
> Didn't get this piece
> 
> > for round 0 is ~min( time(h-1) + 1ms, time.now - MSGDELAY)
> 
> do you mean that it can go back in time to these values? If so then it should be max instead of min, correct?

yes it is max, good catch

**Comment by cason** [comment]
Just to mention that this discussion has happened here: https://github.com/tendermint/tendermint/issues/7947

**Comment by cason** [comment]
>     * for round 0 go back to: `~latest( time(h-1) + 1ms, time.now - MSGDELAY`)

This is actually wrong, right? As it assumes that the propagation delay will be 0. Namely, if a Byzantine proposer sets `ts = time.Now() - MSGDELAY` and the `Proposal` takes `D` time to get to a given node, we have


```
ts = time.Now() - MSGDELAY
proposalReceiveTime = time.Now() + D
ts >= proposalReceiveTime - MSGDELAY - PRECISION
time.Now() - MSGDELAY >= time.Now() + D - MSGDELAY - PRECISION
D <= PRECISION
```

Since we are not considering `PRECISION` in the first two definitions, this is bet on the best (or maybe worst) case of clock skew.

**Comment by cason** [comment]
I agree, however, that by dropping the check considering `MSGDELAY`, one can just set `ts = block[h-1].Time + iota`.

**Comment by cason** [comment]
> but state that they hold for round 0 only

What worries me regarding this approach is that a proposal at round 0 can be rejected for many reasons (e.g., timeout propose), not only because of a bad timestamp.

If we are to adopt this approach, I would say to use a `LIMIT_ROUND > 0`, from which we just drop the second verification.

**Comment by cason** [comment]
A completely different approach to this discussion is the following.

We don't change the spec, we don't make `MSG_DELAY` adaptive (increasing over rounds) nor ignore it from round `X`.
Instead, we add a kind of "circuit breaker" to prevent chains from fully halting in the case where a bad value of `MSG_DELAY` is configured. 

We thus allow nodes to run in a mode where PBTS is fully or partially (`MSG_DELAY` ignored) disabled. In case of liveness issues due to bad parameters, validators must be restarted with this circuit breaker flag set. This allows for restoring the operation of a chain until a better value for `MSG_DELAY` is found and configured.

The negative aspect of this proposal is that any validator could decide not to run the full timestamp validation algorithm. As there is a way to _locally_ disable the timely check.

**Comment by sergio-mena** [comment]
> validator could decide not to run the full timestamp validation algorithm

That can be the case with any solution, as they can change the CometBFT code. So I don't see it as a drawback of this proposal.

**Comment by cason** [comment]
> > validator could decide not to run the full timestamp validation algorithm
> 
> That can be the case with any solution, as they can change the CometBFT code. So I don't see it as a drawback of this proposal in particular.

True. Moreover, the chain needs some form of social consensus so that `2/3+` of the voting power operates in this form or "rescue mode". Then, once the problem is solve, they are also expected to restore the regular operation (disabling this "rescue mode").

**Comment by cason** [comment]
In terms of documentation, we could add this workaround to this PBTS runbook (debugging instructions):

https://github.com/cometbft/cometbft/blob/feature/pbts/docs/tools/proposer-based-timestamps-runbook.md

**Comment by cason** [comment]
To document the decision adopted, it recalls the original solution from https://github.com/tendermint/spec/issues/371.

The decision is to make `MSGDELAY` parameter adaptive, so it should be represented as `MSGDELAY(r)`, where `r` is the consensus round. The adaptation, in the case, is represented by the relation `MSGDELAY(r+1) > MSGDELAY(r)`. Where `MSGDELAY(0)` is the original value, set by the application via the associated consensus parameter.

Differently from the original solution, however, and for the sake of simplicity, we don't plan to establish a first round (it was 10 back there) when the adaptation starts, i.e.,  round`r*` such that if `r >= r*` then `MSGDELAY(r+1) > MSGDELAY(r)`.

An open question, and this is more implementation related, is how to increase `MSGDELAY(r)` over rounds. A suggestion presented by some operators, was to use a 10% increase per round. More formally 

     MSGDELAY(r) == MSGDELAY(0) * (1.1)^r

This exponential increment is slow, for instance, `MSGDELAY(8) ~  2.1 * MSGDELAY(0)`. And should be enough to address bad values for `MSGDELAY` parameter configured by unwary users or operators.
