### ISSUE TITLE
[Bug]: Account sequence mismatch

### ISSUE THREAD

**Issue by evyatar-tres** [cometbft/cometbft#2189]
Posted originally on cosmos-sdk

Is there an existing issue for this?

    I have searched the existing issues

What happened?

A bug happened! :)
I'm working with cosmos SDK (REST) interface to query transactions and ran into a wierd problem over dydx
Hi, I'm looking at a transaction done 10 days ago over the blockchain, and I get zero logs with an error:
"account sequence mismatch, expected 15, got 14: incorrect account sequence"

RPC_ADDRESS = "dydx-mainnet-full-rpc.public.blastapi.io"
RPC_ADDRESS/tx?hash=0x4802C19868A79FA8AFC6FF42443FAD1BF92673AC59F1A7E6F7910BE541B79D33&prove=true

I have noticed over mintscan that there are two transactions posted, on two consecutive blocks
the first one succeeded and the second one failed:

reference: mintscan:
/dydx/tx/4802C19868A79FA8AFC6FF42443FAD1BF92673AC59F1A7E6F7910BE541B79D33?height=6335280
/dydx/tx/4802C19868A79FA8AFC6FF42443FAD1BF92673AC59F1A7E6F7910BE541B79D33?height=6335281

When the API iterates over, it returns the first transaction only, causing some mayhem and missing indexed transactions

Suggestion: return both from the SDK?
Cosmos SDK Version

cosmos_sdk_version "v0.47.4"
How to reproduce?

links in the description :)

also can try this:
https://dydx-mainnet-full-lcd.public.blastapi.io/cosmos/tx/v1beta1/txs?limit=30&page=0&events=message.sender%3D%27dydx16pj5gljqnqs0ajxakccfjhu05yczp9870tkh0z%27&orderBy=2

and see that you receive only the wrong tx

Referred to here:
https://github.com/cosmos/cosmos-sdk/issues/19282

**Comment by melekes** [comment]
What is your application? `account sequence mismatch, expected 15, got 14: incorrect account sequence`-  is this coming from your application?

**Comment by evyatar-tres** [comment]
@melekes Yes, this is coming from the cosmos-sdk
the apllication details can be found here:

https://dydx-mainnet-full-lcd.public.blastapi.io/cosmos/base/tendermint/v1beta1/node_info

**Comment by andynog** [comment]
This message is from the SDK side, as mentioned above, usually it happens when you send successive messages, the client (wallet or relayer) that is sending the message usually needs to retrieve the sequence from the node to send the tx and sometimes it might send the same sequence number in successive messages. It's hard to troubleshoot this without having more context, but this is usually a SDK issue. Also curious about the memo "Dec 23 Chorus rebate" which might be triggered by a wallet ?

**Comment by adizere** [comment]
yes, it is a race condition in submitting the transactions, it most likely happens because
- you are submitting tx too fast in a sequencer
- the node you're submitting to is slow, or falling behind the rest of the network

**Comment by andynog** [comment]
Hi @evyatar-tre, I believe we answered your questions and this is not a CometBFT issue. If that's OK we will close this issue. Thanks!
