### ISSUE TITLE
mempool: panic when app's CheckTx returns an error while rechecking

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#2225]
Thanks @p4u for reporting this bug!

### Setup

**CometBFT version**: from v0.38 and up

### What happened?

Comet panics with the message "recheck cursor is not nil before resCbFirstTime", which is found in this line: https://github.com/cometbft/cometbft/blob/1f430f51f0e390cd7c789ba9b1e9b35846e34642/mempool/clist_mempool.go#L313

Briefly, when we are using a local ABCI client and the app's `CheckTx` method returns a non-nil error, the rechecking process is broken at [this line](https://github.com/cometbft/cometbft/blob/1f430f51f0e390cd7c789ba9b1e9b35846e34642/mempool/clist_mempool.go#L679), leaving `recheckCursor` and `recheckEnd` in an inconsistent state.

#### These are the steps to reach the panic line:
- Rechecking is started by `recheckTxs`, which:
  - sets `recheckCursor` to the first element of the transaction list `txs`
  - for every element in `txs`, it sends a CheckTx request to the app. We are using a local client, so the call to `proxyAppConn.CheckTxAsync` is synchronous, meaning that it will the `CheckTx` method on the app and immediately call the `globalCb` callback to process the response.
  - If the app's `CheckTx` returns an error, the function `recheckTxs` [returns](https://github.com/cometbft/cometbft/blob/1f430f51f0e390cd7c789ba9b1e9b35846e34642/mempool/clist_mempool.go#L679) without finishing the rechecking process and leaving `recheckCursor` with a non-nil value. `recheckCursor` is set to nil again only in `resCbRecheck`, when it's equal to `recheckEnd`.
- A `CheckTx` request of type `CHECK_TX_TYPE_CHECK` is sent to the app for a new tx; a response is handled by `globalCb`, which will panic because `recheckCursor` is not nil.

### Notes

On previous versions of CometBFT, `CheckTxAsync` didn't return an error, so this problem didn't exist. And when this new behaviour was introduced, [the documentation](https://github.com/cometbft/cometbft/blob/main/spec/abci/abci%2B%2B_basic_concepts.md?plain=1#L392-L424) was not updated.

**Comment by p4u** [comment]
I've opened a hotfix PR (#2228) to tackle an immediate panic issue.

However, a deeper solution is warranted, particularly concerning how the mempool processes the errors introduced recently. There's currently ambiguity in determining when to use CheckTxResponse.Code=1 versus returning an error. The critical question is: what role does returning an error play? 

In any case, encountering an error during a transaction's execution should not halt the recheck cursor's progression. Therefore, this PR should be valid and it directly addresses our problem.

**Comment by cason** [comment]
> when this new behaviour was introduced, [the documentation](https://github.com/cometbft/cometbft/blob/main/spec/abci/abci%2B%2B_basic_concepts.md?plain=1#L392-L424) was not updated.

Are we addressing this?

I agree with the previous comment that there is no proper semantic for `CheckTx` returning an error. Since this was introduced recently and we don't have a defined semantics, we should ignored returned errors...
