### ISSUE TITLE
mempool: LRUTxCache.Reset could benefit from using the map clearing idiom to reduce CPU & RAM pressure

### ISSUE THREAD

**Issue by odeke-em** [cometbft/cometbft#2243]
If we look at this code https://github.com/cometbft/cometbft/blob/f92bace913312bbca2ca7e14ca2dcf35eec227e3/mempool/cache.go#L56-L62

we can see that .Reset simply takes a lock then allocates a fresh map by discarding the previous one.

## Suggestion
We can reduce on CPU & RAM pressure by using the map clearing idiom aka
```go
func (c *LRUTxCache) Reset() { 
 	c.mtx.Lock() 
 	defer c.mtx.Unlock() 
  
        for key := range c.cacheMap {
             delete(c.cacheMap, key)
 	}
 	c.list.Init() 
 } 
```

which in performance wisdom is a known and accepted Go idiom for reducing CPU & RAM pressure by reusing the map.

**Comment by melekes** [comment]
https://tip.golang.org/ref/spec#Clear

**Comment by odeke-em** [comment]
@melekes clear was introduced in Go1.21, is every user of this repository already upgraded to that very recent Go version?
