### ISSUE TITLE
Improve validation of blocks during block sync when using BFT Time

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#2279]
Can we change the way we validate the`Time` field of blocks committed by block sync?

The options are the following:
- Do not validate them at all, since in PBTS we don't have an a posteriori validation of block times
- Validate blocks produced while using BFT Time in the same way as currently in main. Do not validate block times from the height at which PBTS is enabled.
- And we have to consider the infamous corner case of the genesis block or, more generally, the first height of the blockchain.

**Comment by cason** [comment]
> Do not validate them at all, since in PBTS we don't have an a posteriori validation of block times

In PBTS we still validate that times are monotonically increasing.

**Comment by cason** [comment]
> Validate blocks produced while using BFT Time in the same way as currently in main.

This is the current approach.

**Comment by cason** [comment]
> we have to consider the infamous corner case of the genesis block or, more generally, the first height of the blockchain.

Also tackled.

**Comment by cason** [comment]
I would say that #2205 has addressed this topic. The current implementation is as follows:

https://github.com/cometbft/cometbft/blob/382911ca28c30e6b565261103753a5b10c26dcfb/internal/state/validation.go#L120-L136
