### ISSUE TITLE
PBTS: Address latest comments on #2231

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#2326]
#2231 was merged to enabled depending PRs to be further worked, but there are some improvements raised by later reviews that should be addressed, probably the most important being the need for extending the UTs.

**Comment by lasarojc** [comment]
relates to #2324

**Comment by sergio-mena** [comment]
@mzabaluev that is not possible, as 0 means "disabled", on both "enable height" fields.

@cason @lasarojc an alternative, which I am thinking of (I'm angry it didn't occur to me earlier), would be adding booleans in the structs rather than the wrapper. The boolean set to false, meaning "disregard"

**Comment by cason** [comment]
> Adding booleans in the struct rather than wrapping the values. The boolean set to false, meaning "disregard"

But to set a value, you have to configure the new height and set the corresponding boolean to true?

**Comment by sergio-mena** [comment]
@cason yes that's the idea. Similar to the bitarray that @mzabaluev proposed in another comment

**Comment by lasarojc** [comment]
The only pending comment, added here by @mzabaluev , will be handled in the context of #2063 (it was added as a task there)
