### ISSUE TITLE
docs: configuration manual

### ISSUE THREAD

**Issue by greg-szabo** [cometbft/cometbft#2351]
## Feature Request
Add a configuration manual to the documentation so people (especially node operators) have a reference manual to turn to when setting up their nodes.

### Summary
A reference manual for the different configuration entries helps create an optimal configuration for node operators. It also allows developers to add more in-depth knowledge about the different entries than what the `config.toml` comment section allows.

### Problem Definition
The `config.toml` comment section is not enough space for describing the configuration entries.

### Proposal
Write a reference manual and add to it as we add new features.

**Comment by cason** [comment]
If find this effort really important.

But I wonder whether you should split the work in several PRs. This is on main, we can have stale versions that are not in the documentation website.

**Comment by cason** [comment]
Stretch goal:

- [ ] Ensure the updated information in `config.toml.md` is added to the `toml.go` template (decide if separate issue should be opened for this)
