### ISSUE TITLE
Unit Tests should more closely resemble real world deployments and circumstances

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#2355]
## Bug Report

Many unit tests are quite unrealistic -- when comet is used in production, it is not generally used to make groups of 4-5 nodes, but instead, validator sets are more commonly 50-200.

```go
// TestPEXReactorRunning tests that the PEX reactor is able to connect to other peers.
func TestPEXReactorRunning(t *testing.T) {
	N := 10
	switches := make([]*p2p.Switch, N)

	// directory to store address books
	dir, err := os.MkdirTemp("", "pex_reactor")
	require.NoError(t, err)
	defer os.RemoveAll(dir)

	books := make([]AddrBook, N)
	logger := log.TestingLogger()

	// create switches with more detailed logging
	for i := 0; i < N; i++ {
		switches[i] = p2p.MakeSwitch(cfg, i, func(i int, sw *p2p.Switch) *p2p.Switch {
			books[i] = NewAddrBook(filepath.Join(dir, fmt.Sprintf("addrbook%d.json", i)), false)
			books[i].SetLogger(logger.With("pex", i))
			sw.SetAddrBook(books[i])

			sw.SetLogger(logger.With("pex", i))

			r := NewReactor(books[i], &ReactorConfig{})
			r.SetLogger(logger.With("pex", i))
			r.SetEnsurePeersPeriod(250 * time.Millisecond)
			sw.AddReactor("pex", r)

			return sw
		})
	}

	// Connect switches to each other
	for i, sw := range switches {
		for j, otherSw := range switches {
			if i != j {
				addr := otherSw.NetAddress()
				err := books[i].AddAddress(addr, addr)
				require.NoError(t, err)
				err = sw.AddPersistentPeers([]string{addr.String()})
				require.NoError(t, err)
			}
		}
	}

	// Start all switches
	for _, sw := range switches {
		sw := sw // create a new variable for the closure
		err := sw.Start()
		require.NoError(t, err)
		defer func(sw *p2p.Switch) {
			require.NoError(t, sw.Stop()) // use the new variable here
		}(sw)
	}

	// Wait for a predefined time to allow connections to establish
	time.Sleep(5 * time.Second)

	// Check the connections
	for i, sw := range switches {
		outbound, inbound, _ := sw.NumPeers()
		logger.Info("Switch connections", "switch", i, "outbound", outbound, "inbound", inbound)
		if outbound+inbound < N-1 {
			t.Errorf("Switch %d has %d outbound and %d inbound connections, expected at least %d",
				i, outbound, inbound, N-1)
		}
	}
}
```

Discovered by: https://github.com/cometbft/cometbft/pull/2005

the above test originally used four nodes, but I modified it to use ten.  Ideally, we would use 100-200 nodes, to mirror the most common production deployments.

100 transactions does not make Comet break a sweat, so we should never test with 100 randomly generated transactions.

Instead, unit tests should be refactored, where possible, to simulate situations where there are 50-200 nodes, and when a tx count is involved, it should be 500+.  We should then improve the underlying code so that Comet can pass these more rigorous tests.

At present, when these values are adjusted to resemble actual problem scenarios, tests fail, so it cannot be too surprising that we are having some scaling issues. 

### Setup

CI

**node command runtime flags**:

### What happened?

Tests did not resemble the real world, and made no attempt to

### What did you expect to happen?

Tests can't perfectly resemble the real world, but we can get mcuh closer than where we are today.

**Comment by melekes** [comment]
Realistically, we can’t adjust every test to run 100-200 instances, as we aim to keep tests fast both locally and in CI. However, we do prioritize testing large deployments. That’s why we have nightly tests and quality assurance processes in place before each major release, where we deploy a 120-node network across multiple clusters to ensure everything works smoothly at scale.
