### ISSUE TITLE
PBTS: Update Consensus Params in SDK

### ISSUE THREAD

**Issue by glnro** [cometbft/cometbft#2384]
In addition to ensuring Synchrony Params are added to the SDK's consensus module params, #2063 introduced an additional Consensus Parameter which will include the feature flags/enable height for both Vote Extensions and PBTS (for chains that opt to initialize with BFT Time or will need to upgrade to PBTS). 

Acceptance Criteria
- [ ] Introduce Synchrony Params
- [ ] Introduce Feature Params
- [ ] Refactor ABCI/Vote Ext Enable Height to Feature Params

**Comment by cason** [comment]
We are depending on SDK, issue opened: https://github.com/cosmos/cosmos-sdk/issues/19603
