### ISSUE TITLE
error adding vote / failed to process message error logs

### ISSUE THREAD

**Issue by czarcas7ic** [cometbft/cometbft#2395]
## Bug Report

![Screenshot 2024-02-20 at 10 21 57 PM](https://github.com/cometbft/cometbft/assets/40078083/cfe0faf4-2ab5-445c-b0b7-0b2b9879fedc)

This occurs in the following err check https://github.com/osmosis-labs/cometbft/blob/490dd752eb8a1a934542f70fdc8960594e06973b/consensus/state.go#L890-L899

Wanted to report here that we get this error fairly often, and wanted to ensure the comet team was tracking, and if there are plans to fix in a future upgrade.

This is on cometbft v0.37.4 on current Osmosis mainnet.

**Comment by ValarDragon** [comment]
Is there any chance were skipping log lines? There should be another line right before each of these prints explainign why we failed to add it I think:
https://github.com/osmosis-labs/cometbft/blob/62a97f2c9713c716ef203052eb32069f917737f9/internal/consensus/state.go#L2148-L2154

**Comment by cason** [comment]
> This occurs in the following err check https://github.com/osmosis-labs/cometbft/blob/490dd752eb8a1a934542f70fdc8960594e06973b/consensus/state.go#L890-L899

Not sure it was there. Since there are some fields missing.

**Comment by cason** [comment]
In debug node you should see the reason in more detail. Most of the "trivial" reasons are not exported to the caller, they are handled inside `tryAddVote`.
