### ISSUE TITLE
Docs: Add information about changes to key layout in UPGRADING.md

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#2406]
### Summary

Add database key layout changes to upgrading guidelines to explain behaviour done in #2327

**Comment by jmalicevic** [comment]
@melekes , @sergio-mena , do you think this will be needed now that #2327 introduces v2 as only experimental?

**Comment by sergio-mena** [comment]
@jmalicevic I would defer this issue until a second layout becomes official (i.e., non-experimental)

**Comment by jmalicevic** [comment]
Closing until we decide a new layout will be officially supported.
