### ISSUE TITLE
State store should be able to unmarshal the old version of ConsensusParams protobuf from the DB

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#2438]
V1 introduces FeatureParams and deprecates ABCIParams, as fields of ConsensusParams.
As part of the change, `ABCIParams.vote_extensions_enabled_height` was replaced by `FeatureParams.vote_extensions_enabled_height`

This issue is open to ensure that networks upgrading from v0.38 to v1 and which have set an enabling height before the migration, do the right thing and move the value from one field to the other.

**Comment by lasarojc** [comment]
Through manual testing I have verified the following sequence of steps, which is problematic.

- Start a chain at version v0.38.0 and set `ABCIParams.vote_extensions_enabled_height` to X
- On height Y < X, upgrade to v1. 
   - During the restart, the value of `ABCIParams.vote_extensions_enabled_height` is ignored and `FeatureParams.vote_extensions_enabled_height` is set to 0
- Once height X is reached and other nodes enable VE, the test node rejects the VE, as locally it is disabled.
- If all nodes upgrade at once, the value of X is lost to all nodes and if this upgrade happens after X, VE are disabled, which is not allowed by the spec.

## DoD

- Code to migrate the value from ABCIParams to FeatureParams is provided
- The run described above is no longer, VE enabling happens as expected at height X, irrespective of when the upgrade happens, and VE enabling is not reverted.
-

**Comment by sergio-mena** [comment]
Closed by #2462
