### ISSUE TITLE
privval: DO NOT require extension signature from privval if vote extension is disabled

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2439]
Refs #2357 

https://github.com/cometbft/cometbft/blob/914e9d7f5e01101198d848be53e7d18e7afacaaa/types/vote.go#L436-L441

Currently, we require an extension signature from the privval EVEN IF vote extensions are disabled. I.e., if the app is not using vote extensions, validators are signing (through HSM or `FilePV`) empty `Vote.Extension` (plus other fields like height and round). Seems like a waste of computing resources. Refs https://github.com/iqlusioninc/tmkms/pull/857#issuecomment-1957368608

**Comment by cason** [comment]
>  if the app is not using vote extensions

If the application has enabled vote extensions (which is optional) and is not actually using it.

**Comment by melekes** [comment]
After discussion with @sergio-mena, we've decided to add a boolean flag `signExtension` to `SignVote`, which indicates if privval needs to sign extension bytes or not.

```
SignVote(chainID string, vote *cmtproto.Vote, signExtension bool) error {
```

```
// SignVoteRequest is a request to sign a vote
message SignVoteRequest {
  cometbft.types.v1beta1.Vote vote     = 1;
  string                      chain_id = 2;
  bool sign_extension = 3;
}
```

**Comment by cason** [comment]
Do we have a solution for this problem for v0.38.x? See #2711.

**Comment by melekes** [comment]
> Do we have a solution for this problem for v0.38.x? See #2711.

The only possible solution is to not check extension signature if vote extensions are disabled. But this would change the default behavior (always check).
