### ISSUE TITLE
mempool: CListMempool.Flush invokes a read-lock meanwhile it performs write/mutating operations; inadequately tested because there will be data races too

### ISSUE THREAD

**Issue by odeke-em** [cometbft/cometbft#2443]
## Bug Report
Noticed in a code audit that this code is erroneously invoking a read-lock meanwhile it performs write/mutating operations

https://github.com/cometbft/cometbft/blob/4ce0277b35f31985bbf2c25d3806a184a4510010/mempool/clist_mempool.go#L221-L229

which also means that this mempool implementation is not properly tested because it clearly invokes mutating code here https://github.com/cometbft/cometbft/blob/4ce0277b35f31985bbf2c25d3806a184a4510010/mempool/clist_mempool.go#L136-L147

**Comment by hoanguyenkh** [comment]
thank you, i have a PR here -> https://github.com/cometbft/cometbft/pull/2497
