### ISSUE TITLE
QA/PBTS: Run 200-nodes test with v0.38.x's saturation point

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#2460]
The goal is to gather some metrics (specifically `ProposalTimestampDifference`) so that the PBTS squad can set default values. This is an auxiliary testnet run, not part of the regular QA process.

Test settings:
- Run on `feature/pbts` branch
- PBTS enable height: 1
- Run QA 200-node TC, but only with v0.38.x saturation point (r=200, c=2)
- Run the experiment (90 secs each) 4-5 times, or just run the experiment for 3-4 mins
- Using latency emulation

**Comment by sergio-mena** [comment]
@hanz You'll probably need to run it off `feature/pbts`. As we will use this run to "justify" that the feature branch is stable enough to merge it into `main` (and backport it to `v1.x`)

**Comment by cason** [comment]
After internal discussions we propose a new distribution of buckets for this metric: #2479.

**Comment by cason** [comment]
Can you collect also `QuorumPrevoteDelay` and `FullPrevoteDelay`  metrics, so we can understand their meaning and significance?

**Comment by faddat** [comment]
How are we defining saturation point?

**Comment by cason** [comment]
> How are we defining saturation point?

Measure latency and throughput with increasing load. Find the point where latency increases substantially without gains in throughput. Take a point a little before this saturation happens.

**Comment by faddat** [comment]
@cason this is really good stuff. This approach could lead to the resolution of some longstanding issues in comet/cosmos.  Very supportive of this.

**Comment by hvanz** [comment]
Closed as part of #2480
