### ISSUE TITLE
ABCI 2.0: Docs and tutorials

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#25]
Tasks:
  - [x] #544
  - [x] Revisit the following files
    - [x] See if tendermint/tendermint#7660 is still relevant
    - [x] `getting-started.md` [small, 0.5 days]
    - [x] `indexing-transactions.md` [small, 0.5 days]
    - [x] `abci-cli.md` (review only) [small, 0.5 days]
    - [x] `what-is-tendermint.md` (ABCI section) [small, 0.5 days]
    - [x] `go-built-in.md and go.md` (same changes) [medium, 2 days]

Stretch goal:
- [x] #2853
 
DoD:
  - [x] The doc is updated, and proof-read
  - [x] No references of `BeginBlock`, `DeliverTx`, `EndBlock` can be found (except if the text is explicitly referring to them as obsolete)
  - [x] (Strech) The new tutorial is complete and included in doc

Original issue: tendermint/tendermint#9918

**Comment by adizere** [comment]
@andynog should we close this, or something left ("Improve the ABCI v2 tutorial vote extensions logic regarding curse words") ? thanks!

**Comment by andynog** [comment]
I believe @sergio-mena wanted to have some improvements in the vote extensions logic for the tutorial so he added this item as a reminder to implement that. I think he wanted to keep it under this tracking issue. I can open an issue to have that implemented.

**Comment by sergio-mena** [comment]
This has been open for so long that I'd favour closing it and extracting the improvements to the current tutorial into a "tech-debt-related" issue.
We _do_ need to improve the way we use vote extensions in the tutorial, as people as supposed to be using it as a model and there _are_ some limitations in the way we are using vote extensions in the tutorial.

**Comment by alijnmerchant21** [comment]
Agreed. There should have been better implementation of VE; specially how comet uses `VerifyVoteExtension`.

**Comment by cason** [comment]
>  Improve the ABCI v2 tutorial vote extensions logic regarding curse words

So, it is possible that we are having a workshop on ABCI++ during Cosmoverse. The plan, to still be confirmed, is that I am running it. In this case, I will take a look on this tutorial and improve it in order to use in this workshop.

I'd suggest, as @sergio-mena mentioned, to open a new issue on that and to close this one.

**Comment by alijnmerchant21** [comment]
On a side note @cason please use magic words as curse words. Was kinda funny last time I demoed. 😂

**Comment by andynog** [comment]
@cason , I opened this https://github.com/cometbft/cometbft/issues/4162, please feel free to work on it for your tutorial. 

But I will go ahead and close this one as per @sergio-mena feedback. Thanks

**Comment by andynog** [comment]
All in scope completed.
