### ISSUE TITLE
PBTS: merge branch `feature/pbts` into `main`

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#2516]
- Merge branch `feature/pbts` back onto `main`.
- Delete the feature branch.

**Comment by sergio-mena** [comment]
## Intro

This comment reports on performance comparison between the tip of `feature/pbts` and `v0.38.x`.

The plots reported here are:

* baseline: the QA results from our last official QA process (`v0.38.x`, check [here](https://github.com/cometbft/cometbft/blob/v0.38.5/docs/qa/CometBFT-QA-38.md) all the data)
* pbts_smoke: 200-node run, performed under the same conditions as the baseline (`c=1,r=400`). This was run off the tip of `feature/pbts` as of 2023-03-01 (hash: fede9dbd2)

This is not an official QA process. The goal is to show enough evidence that the system's performance has not degraded w.r.t. our last official release (`v0.38.x`) when running it on a big network (200 nodes) with TX load close to `v0.38.x`'s saturation point.

## Plots

### Average Mempool Size

#### PBTS branch (`feature/pbts`)
![avg_mempool_size](https://github.com/cometbft/cometbft/assets/15381133/64295d97-202f-4a11-b1df-f4351f911946)

#### Baseline (`v0.38.x`)
![avg_mempool_size_bl](https://github.com/cometbft/cometbft/raw/v0.38.5/docs/qa/img38/200nodes/avg_mempool_size.png)

### CPU

#### PBTS branch (`feature/pbts`)
![cpu](https://github.com/cometbft/cometbft/assets/15381133/1ff48970-77b3-4d62-94d8-b1f04773e42f)

#### Baseline (`v0.38.x`)
![cpu_bl](https://github.com/cometbft/cometbft/raw/v0.38.5/docs/qa/img38/200nodes/cpu.png)

### Memory

#### PBTS branch (`feature/pbts`)
![memory](https://github.com/cometbft/cometbft/assets/15381133/183bb47e-bb52-47cb-a930-8f33a60a686e)

#### Baseline (`v0.38.x`)
![memory_bl](https://github.com/cometbft/cometbft/raw/v0.38.5/docs/qa/img38/200nodes/memory.png)

### Block Rate

#### PBTS branch (`feature/pbts`)
![block_rate_regular](https://github.com/cometbft/cometbft/assets/15381133/8a348136-735b-4dd9-9600-6d42ed44aeef)

#### Baseline (`v0.38.x`)
![block_rate_bl](https://github.com/cometbft/cometbft/raw/v0.38.5/docs/qa/img38/200nodes/block_rate.png)

### Transaction Rate

#### PBTS branch (`feature/pbts`)
![total_txs_rate_regular](https://github.com/cometbft/cometbft/assets/15381133/27117d3e-036a-4e8e-ad68-358e4d95ece6)

#### Baseline (`v0.38.x`)
![total_txs_rate_bl](https://github.com/cometbft/cometbft/raw/v0.38.5/docs/qa/img38/200nodes/total_txs_rate.png)

### Rounds reached

#### PBTS branch (`feature/pbts`)
![rounds](https://github.com/cometbft/cometbft/assets/15381133/b6a93081-8351-4e5e-a64a-521770dfe622)

#### Baseline (`v0.38.x`)
![rounds_bl](https://github.com/cometbft/cometbft/raw/v0.38.5/docs/qa/img38/200nodes/rounds.png)

## Conclusions

* No noticeable differences in metrics w.r.t `v0.38.x` (other metrics not shown here have also been compared). Only observation is a slight decrease in memory used.
* **We are good to merge `feature/pbts` back into `main`**

**Comment by sergio-mena** [comment]
For reference, this diff was used to generate the PBTS plots above
```diff
diff --git a/scripts/qa/reporting/prometheus_plotter.py b/scripts/qa/reporting/prometheus_plotter.py
index fbc62050f..5df5f8c9b 100644
--- a/scripts/qa/reporting/prometheus_plotter.py
+++ b/scripts/qa/reporting/prometheus_plotter.py
@@ -16,7 +16,8 @@ from urllib.parse import urljoin
 from prometheus_pandas import query
 
 #release = 'v0.37.0-alpha.2'
-release = 'v0.38.0-alpha.2'
+#release = 'v0.38.0-alpha.2'
+release = 'v1.0_pbts_smoke'
 path = os.path.join('imgs')
 prometheus = query.Prometheus('http://localhost:9090')
 
@@ -47,10 +48,11 @@ ext_window_size = dict(seconds=200)
 
 #left_end = '2023-05-25T18:18:04Z' #CMT v0.38.0-alpha.2 - ve baseline
 #left_end = '2023-05-30T19:05:32Z' #CMT v0.38.0-alpha.2 - ve 2k
-left_end = '2023-05-30T20:44:46Z' #CMT v0.38.0-alpha.2 - ve 4k
+#left_end = '2023-05-30T20:44:46Z' #CMT v0.38.0-alpha.2 - ve 4k
 #left_end = '2023-05-25T19:42:08Z' #CMT v0.38.0-alpha.2 - ve 8k
 #left_end = '2023-05-26T00:28:12Z' #CMT v0.38.0-alpha.2 - ve 16k
 #left_end = '2023-05-26T02:12:27Z' #CMT v0.38.0-alpha.2 - ve 32k
+left_end = '2024-03-01T16:05:57Z' #CMT v0.38.0-alpha.2 - pbts
 
 useManualrightEnd = False
 if useManualrightEnd: 
@@ -121,9 +123,9 @@ queriesVExtension= [
     (( 'rate(' + fork + '_consensus_total_txs[20s])*60', time_window[0], time_window[1], '1s'), 'total_txs_rate',    dict(ylabel='TXs/min',           xlabel='time (s)', title='Rate of transaction processing', legend=False, figsize=(10,6), grid=True), True),
 ]
 
-#queries = queries200Nodes
+queries = queries200Nodes
 #queries = queriesRotating
-queries = queriesVExtension
+#queries = queriesVExtension
 
 
 for (query, file_name, pandas_params, plot_average) in queries:

```
