### ISSUE TITLE
privval: support arbitrary message signing

### ISSUE THREAD

**Issue by tac0turtle** [cometbft/cometbft#2517]
### Summary

With complex usecases being thought of every day, some of these use cases require the validator to sign more data than what only comet has. The current option is to force users to only use the file system. Being that comet is one of the only systems with remote signers, we believe that comet should try to adopt a way for an application to request remote signers to sign over something 

### Problem Definition

providing a seamless ux for node operators and not countless keys to manage, comet should expose a arbitrary message to sign for remote signers. it does not need to be exposed to the application in the same way abci is since this can be gotten from the node. 

### Proposal

add a new message type to sign arbitrary messages to privval

The current use case we are trying to build is to use randao and kzg which requires the validators signature

**Comment by cason** [comment]
Are you considering some limit for the size of the "arbitrary message" or byte array to sign?

Or we have the assumption that the client of the remote signer is always benign?

**Comment by tac0turtle** [comment]
remote signers are trusted parties, so think its benign.

**Comment by cason** [comment]
We are not backporting this change to v0.38.x because we deem it is a breaking change.

Please re-open this issue if this constitutes a problem.
