### ISSUE TITLE
The new node is unable to join the network, throwing an error "auth failure: secret conn failed"

### ISSUE THREAD

**Issue by luketheart** [cometbft/cometbft#2601]
### Setup

**CometBFT version**: v0.37.2

**Have you tried the latest version**: no

**ABCI app**: https://github.com/artela-network/artela

**Environment**:
- **OS**: 22.04.3 LTS (Jammy Jellyfish)
- **Install tools**:
- **Others**:

**node command runtime flags**: artelad start

### Config

[p2p]

laddr = "tcp://0.0.0.0:26656"
seeds = "5c4ea81ac7b8a7f5202fcbe5fe790a6d6f61fb22@47.251.14.108:26656,f809f4fd17a9cf434b059af3e86262bbac3cb809@47.251.32.165:26656"
persistent_peers = ""
upnp = false

max_num_inbound_peers = 40
max_num_outbound_peers = 10
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0s"
send_rate = 5120000
recv_rate = 5120000
pex = true
seed_mode = false
handshake_timeout = "20s"
dial_timeout = "3s"

### What happened?
Artela is a chain built on the Cosmos SDK and CometBFT. It is currently running on the testnet. I set up a new node on a VPS and configured it with seed nodes to join the network and catch up from the first block. However, when the node starts dialing the seed nodes, the handshake fails during the shareEphPubKey process. The ReadMsg returns an error: i/o timeout, or connection reset by peer. 
Occasionally, it is able to connect to nodes and start syncing blocks.

### Logs
4:05PM INF service start impl=Node module=server msg={}
4:05PM INF Starting pprof server laddr=localhost:6060 module=server
4:05PM INF service start impl="P2P Switch" module=p2p msg={}
4:05PM INF service start impl=Evidence module=evidence msg={}
4:05PM INF serve module=rpc-server msg={}
4:05PM INF service start impl=StateSync module=statesync msg={}
4:05PM INF service start impl=PEX module=pex msg={}
4:05PM INF service start book=/root/.artelad/config/addrbook.json impl=AddrBook module=p2p msg={}
4:05PM INF service start impl=Reactor module=blockchain msg={}
4:05PM INF service start impl=BlockPool module=blockchain msg={}
4:05PM INF service start impl=ConsensusReactor module=consensus msg={}
4:05PM INF Reactor  module=consensus waitSync=true
4:05PM INF Saving AddrBook to file book=/root/.artelad/config/addrbook.json module=p2p size=0
4:05PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
4:05PM INF No addresses to dial. Falling back to seeds module=pex
4:05PM INF starting API server... module=api-server
4:05PM INF serve module=api-server msg={}
4:05PM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.29.12.151:36668->47.251.14.108:26656: i/o timeout" module=p2p seed={"id":"5c4ea81ac7b8a7f5202fcbe5fe790a6d6f61fb22","ip":"47.251.14.108","port":26656}
4:05PM INF New websocket connection module=rpc-server protocol=websocket remote=127.0.0.1:44478
4:05PM INF service start impl=wsConnection module=rpc-server msg={} protocol=websocket remote={"IP":"127.0.0.1","Port":44478,"Zone":""}
INFO [03-13|16:05:47.290] Gasprice oracle is ignoring threshold set threshold=2
4:05PM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.29.12.151:46508->47.251.32.165:26656: i/o timeout" module=p2p seed={"id":"f809f4fd17a9cf434b059af3e86262bbac3cb809","ip":"47.251.32.165","port":26656}
4:05PM ERR Couldn't connect to any seeds module=p2p
4:05PM INF Starting peer-to-peer node instance=artela/linux-amd64/go1.20.3 module=geth
4:05PM INF HTTP server started auth=false cors=* endpoint={"IP":"127.0.0.1","Port":8545,"Zone":""} module=geth prefix= vhosts=*
4:05PM INF WebSocket enabled module=geth url=ws://[::]:8546
INFO [03-13|16:05:55.301] New local node record                    seq=1,708,339,406,188 id=c817eaad4065abff ip=127.0.0.1 udp=0 tcp=30303
4:05PM INF Started P2P networking module=geth self=enode://540d0a307534fc8d24eb6647344e889799fa0bd267854b21f704d40559bc10a583edb8488242aa6f5cf90e4b15c2c51cdb5eec4e0d2d79bc784aeb636886d133@127.0.0.1:30303?discport=0
4:06PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
4:06PM INF No addresses to dial. Falling back to seeds module=pex
4:06PM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.29.12.151:56576->47.251.14.108:26656: i/o timeout" module=p2p seed={"id":"5c4ea81ac7b8a7f5202fcbe5fe790a6d6f61fb22","ip":"47.251.14.108","port":26656}
4:06PM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.29.12.151:35084->47.251.32.165:26656: i/o timeout" module=p2p seed={"id":"f809f4fd17a9cf434b059af3e86262bbac3cb809","ip":"47.251.32.165","port":26656}
4:06PM ERR Couldn't connect to any seeds module=p2p
4:06PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
4:06PM INF No addresses to dial. Falling back to seeds module=pex

**Comment by melekes** [comment]
Do you have access to the seed nodes that drop connections? If yes, could you provide their logs as well?

**Comment by luketheart** [comment]
There are too many debug-level logs, approximately a few hundred megabytes per minute, most of which about voting information. What keywords should I use to filter the logs?

**Comment by melekes** [comment]
> What keywords should I use to filter the logs?

`Stopping peer for error`

**Comment by luketheart** [comment]
Thank you @melekes. 
During the attempt to connect the new node, the seed node did not filter any errors related to "Stopping peer for error".
It's strange that when I set the log level to debug and restart the seed node, it can be connected. It became unconnectable after running for approximately an hour. Could it be that after running for an extended period, the number of connected peers reaches its limit or encounters other restrictions, resulting in the failure of new connections?

**Comment by melekes** [comment]
> Could it be that after running for an extended period, the number of connected peers reaches its limit or encounters other restrictions, resulting in the failure of new connections?

The seed node is supposed to disconnect from a peer once it shares the known addresses.

**Comment by cason** [comment]
> Could it be that after running for an extended period, the number of connected peers reaches its limit or encounters other restrictions, resulting in the failure of new connections?

There is a maximum number of incoming connections that a seed node keeps. But at the same time, if the node is configured as a seed node, it has a routine to periodically disconnect from peers. So it eventually should have slots for accepting new connections.

**Comment by luketheart** [comment]
Thanks for the help guys @melekes @cason , now I have a better chance of successfully connecting to specific nodes. I'll mark this issue as closed for now. If there are any further findings, I'll promptly update the team.
