### ISSUE TITLE
Cosmos SDK: provide an API for accessing `state` and `store`

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2610]
### Summary

The latest version of Cosmos SDK imports `state` and `store` packages (which in v1 are internal, meaning can't be imported outside of CometBFT).

### Problem Definition

Previously, the way to test something on a testnet for a single validator was by modifying the `genesis.json` file and skipping blocksync as indicated in https://github.com/cometbft/cometbft/issues/1679. A new solution was developed because exporting `genesis.json` can take minutes and requires lots of RAM. Instead of modifying the `genesis.json` file, Cosmos SDK directly modifies the chain's state and updates the store: https://github.com/cosmos/cosmos-sdk/blob/main/server/start.go#L729. For that, it needs access to `state` and `store` packages, which are currently internal.

### Proposal

Either create a subset of API needed for ^ or completely reexport `state` and `store` packages.

**Comment by tac0turtle** [comment]
thank you, let us know if we can help

**Comment by itsdevbear** [comment]
@melekes any update on this guy?

**Comment by tac0turtle** [comment]
gentle ping, we cant move forward with comet integration in the sdk for the next release. If there is an expected timeline it would be good to know so we can share with ibc, cosmwasm, and other teams waiting on the release
