### ISSUE TITLE
PBTS: Allow Application to Set BlockTimestamp

### ISSUE THREAD

**Issue by itsdevbear** [cometbft/cometbft#2655]
### Summary

Useful in cases where the application logic relies on block times adhering to some property. 

### Proposal

Create a "PreparePrepareProposal" hook of some kinda.

**Comment by adizere** [comment]
hey Dev, thanks for opening this!

is it fair to say that the underlying concern you'd like to address is ensuring that CometBFT produces blocks at a predictable (ideally fixed) rate, say 1 block every 5 second. so even if blocks are empty, Comet should produce a block every 5 seconds, say.

this model was discussed by the previously team (ref https://github.com/tendermint/tendermint/issues/5911) and it's part of a broader block timeouts UX improvements -- discussion here https://github.com/cometbft/cometbft/discussions/2266

**Comment by itsdevbear** [comment]
yeah @adizere you got it!

**Comment by cason** [comment]
So, the underlying goal here is consensus to wait until the time returned by the application before proposing the block?

**Comment by lasarojc** [comment]
What if prepareProposal also let the block time to be modified? And prepareProposal could just wait to return when it decides the time is good

**Comment by itsdevbear** [comment]
^ this behaviour would actually work for us very well

**Comment by itsdevbear** [comment]
We should be able to do this in a similar way to how we did the timeout commit.
