### ISSUE TITLE
docs: typo Byzantine Consensus Algorithm in specs

### ISSUE THREAD

**Issue by sc0Vu** [cometbft/cometbft#2664]
## Bug Report

![image](https://github.com/cometbft/cometbft/assets/10494397/1e98f7ce-839b-4577-8793-194bd1718003)

In the Byzantine Consensus Algorithm in specs Proposals section, I think the word `iff` supposed to be `if`.

> A proposal at (H,R) is composed of a block and an optional latest PoLC-Round < R which is included "iff" (here) the proposer knows of one. This hints the network to allow nodes to unlock (when safe) to ensure the liveness property.

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):

**Have you tried the latest version**: yes/no

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**node command runtime flags**:

**Comment by cason** [comment]
iff == if and only if
