### ISSUE TITLE
State sync from local snapshot

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#27]
As this issue contained tasks that take more than 2 weeks collectively, it has been split into two parts:

- [x] #28
- [x] #29

Original issue: tendermint/tendermint#9946

**Comment by JayT106** [comment]
@sergio-mena Many online projects need this feature leading ASAP (including us, the Cronos chain). Before the p2p protocol can run efficiently. I think this will be a short-term solution for solving the unstable statesync problem.

**Comment by tac0turtle** [comment]
yes please, every validator would like to have this

**Comment by adizere** [comment]
Closing this with the remark:
- on the problem & solution design space, our latest understanding is in #801 ADR 104.
- on the implementation side, we have not implemented anything as this work became deprioritized when it was found out that a quicker and more appropriate solution belongs in the SDK.
    - potential followup: #884
