### ISSUE TITLE
Renaming Tendermint to CometBFT in branch v0.34.x

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#280]
Some files present in branch `v0.34.x` contain multiple references to Tendermint/Tendermint Core:

- CHANGELOG.md (updated in main by #130)
- CODE_OF_CONDUCT.md (updated in main by #252)
- CONTRIBUTING.md (updated in main by #252)
- README.md (updated in main by #252)
- SECURITY.md (updated in main by #252)
- STYLE_GUIDE.md (updated in main by #148)
- UPGRADING.md (updated in main by #252)

The following files have no correspondence in the `main` branch:

- release_notes.md
- PHILOSOPHY.md
- CHANGELOG_PENDING.md

Should we maintain them in `v0.34.x` branch?

Follows from #93.

**Comment by jmalicevic** [comment]
`CHANGELOG_PENDING.md` can be removed as we are using unclog for the changelog now.
`PHILOSOPHY.md` will be added by #190 . 
`Release_notes`, can be edited before cutting a release but add a todo item somehere maybe?

**Comment by cason** [comment]
> CHANGELOG_PENDING.md can be removed as we are using unclog for the changelog now.

#105 doesn't mention the v0.34.x branch though.

**Comment by lasarojc** [comment]
> > CHANGELOG_PENDING.md can be removed as we are using unclog for the changelog now.
> 
> #105 doesn't mention the v0.34.x branch though.

We didn't change to use unclog for 0.34 as we were going for a minimal change. It is a very simple change, so we might as well do it. Do you concur, @thanethomson @sergio-mena ?

**Comment by sergio-mena** [comment]
> Do you concur, @thanethomson @sergio-mena ?

If it is a simple change I'd say go for it, since improvements to the changelog don't risk introducing regressions

**Comment by lasarojc** [comment]
Thane has implemented the use of unclog, so CHANGELOG_PENDING.md does not exist anymore on 0.34.

**Comment by cason** [comment]
#322 should address most of the tasks.

**Comment by lasarojc** [comment]
Anything pending here?

**Comment by thanethomson** [comment]
Doesn't look like it. If something else comes up we can reopen this issue.
