### ISSUE TITLE
spec(gossip): Specifies the gossip layer of consensus as a CRDT 

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft#2818]
Ref: #2581

**Comment by cason** [comment]
We could create a `spec/research` dir and add this spec  as `consensus-crdt` in this directory.

**Comment by andynog** [comment]
> We could create a `spec/research` dir and add this spec  as `consensus-crdt` in this directory.

I think it is a good idea as long as we have a README in the spec/research that topics in this folder are from a research nature and the implementation might happen or not according to the evolution of this research

**Comment by adizere** [comment]
deprioritized
