### ISSUE TITLE
types: figure out where the extra 10 bytes in `MaxCommitSigBytes` are coming from

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2838]
https://github.com/cometbft/cometbft/pull/2765#discussion_r1568503909

`types/block.go`:

```go
MaxCommitSigBytes int64 = 131 + 10 // where's the 10 from?
```

## Definition of done

- [ ] Add a comment in the code explaining what do the 10 extra bytes serve

**Comment by andynog** [comment]
Don't know why it's `+10`, total now is `141` because it was `109` but with `bls` it has to accommodate `32` more since it can be `96` now as opposed to `64` before (`96 - 64 = 32`) so it would have been more clear if you had 
```
MaxCommitSigBytes int64 = 109 + 32
```
😉

**Comment by andynog** [comment]
This PR might also give some pointers about this https://github.com/cosmos/cosmos-sdk/pull/18551/files something to do computing the size of the proto?

**Comment by andynog** [comment]
Hi @melekes, is there any action item that we should do here? Is the expectation to figure it out and document it, or do you expect any code changes for this? Please let me know if I can help. Thanks !

**Comment by melekes** [comment]
> Hi @melekes, is there any action item that we should do here? Is the expectation to figure it out and document it, or do you expect any code changes for this? Please let me know if I can help. Thanks !

figure it out and document it, yes

**Comment by melekes** [comment]
Closing in favor of https://github.com/cometbft/cometbft/issues/3628
