### ISSUE TITLE
Lower allocation overhead of metrics in peer.Send

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#2840]
### Summary

In Memory profiles of full nodes, we see large amounts of heap allocation in p2p.send coming from Prometheus logging, that is ~entirely duplicate work. 
![image](https://github.com/cometbft/cometbft/assets/6440154/b4547d5e-6d43-4465-a923-92169ec20c4e)

This is coming from these lines: https://github.com/cometbft/cometbft/blob/b8466398aacfc6f491ac54e741fce6750fa1cb9e/p2p/peer.go#L284-L292

We should be able to have the labels already cached (or at minimum the peer ID label cached) in the existing peer.Metrics instance.

### Problem Definition

Lower heap allocation and time overhead of sending something to peers. I have no idea how much this is a dominant term in wall clock time, though I do see recv time and send time routinely in CPU profiles.

### Proposal

Cache the peer ID label in p.metrics.PeerSendBytesTotal, so this is re-done on every packet send

**Comment by cason** [comment]
There is a cache though: https://github.com/cometbft/cometbft/blob/d27732ad9a992e321e440417a2a8220f90fe0044/p2p/metrics.go#L43

**Comment by cason** [comment]
But it doesn't apply to channel ID (which is immutable after startup) and to peer ID (this changes over time, so a cache would be good).

But in general, have per peer ID metrics looks an overkill to me.

**Comment by ValarDragon** [comment]
That makes sense! I'm down for deleting per peer id metrics as well

**Comment by cason** [comment]
> We should be able to have the labels already cached (or at minimum the peer ID label cached) 

I am wondering why we need to cache the peer ID. It is a string, so are you sure we are creating copies here?

**Comment by ValarDragon** [comment]
Lets measure after that gets in! The memory overhead is coming from the prometheus `With` and `Add` calls I believe, so the creation of the PeerId as a string isn't the issue

**Comment by cason** [comment]
Updated the PR. It is covering both send and receive side metrics.

**Comment by ValarDragon** [comment]
I think we should re-open this issue. I think from the issue we were leaning towards just removing these peer metrics entirely. Or should I make a new issue for that?

**Comment by cason** [comment]
Adding here the comment that indicates the next step to improve this overhead:

https://github.com/cometbft/cometbft/pull/2851#discussion_r1571202734

**Comment by adizere** [comment]
Beside #3298, what is left to close this issue?
