### ISSUE TITLE
Add lru cache for loading commit from blockstore

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#2844]
### Summary

Whenever a peer is lagging by more than 1 block, we load the commit for the height they were on and send them the whole commit (per code comment. Admittedly I haven't looked long, but I don't see how it's currently sending the whole commit vs just a single vote from it). [Source](https://github.com/cometbft/cometbft/blob/d27732ad9a992e321e440417a2a8220f90fe0044/internal/consensus/reactor.go#L885)

Loading the commit requires doing a db read and a proto unmarshal. [Source](https://github.com/cometbft/cometbft/blob/main/store/store.go#L331) In benchmarks we see the proto unmarshal taking a large number of heap allocations, and this is likely duplicate work. (Unmarshalling the same block commit)

We should keep a small LRU cache for height to unmarshalled commit to reduce the memory pressure here. I suspect the same maybe helpful for block parts as well. 

In v37 we saw that this was around 70GB of heap allocation on a query serving node over 1-2 hours. (Will paste memprofile later)

I do not know the total system impact it has, but a 70GB ram allocation is very high. 

### Proposal

Add a simple lru cache in blockstore for loading commit and block parts

**Comment by cason** [comment]
Definitely. This LRU cache can be implemented at the store, in my opinion, so no need for code changes in the reactor.

**Comment by cason** [comment]
The `gossipDataRoutine` was recently refactored (https://github.com/cometbft/cometbft/pull/2663). 

We load block parts [here](https://github.com/cometbft/cometbft/blob/d27732ad9a992e321e440417a2a8220f90fe0044/internal/consensus/reactor.go#L853). If the peer is still lagging behind in the next iteration, we load another block part. Although block parts are not stored together, so we have to load them one by one ([source](https://github.com/cometbft/cometbft/blob/d27732ad9a992e321e440417a2a8220f90fe0044/store/store.go#L253)).
