### ISSUE TITLE
enterPrecommit is almost always double verifying the block

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#2854]
### Summary

enterPrecommit almost always runs `ValidateBlock`, however in most cases this is duplicate logic as we have already prevoted the block. We only enter a lock after this line! This is the line where we run validate block: https://github.com/cometbft/cometbft/blob/main/internal/consensus/state.go#L1667

I suggest that we change this line [here](https://github.com/cometbft/cometbft/blob/main/internal/consensus/state.go#L1667), to be one of two things:
- Only validate the block after checking some cache for whether we have already validated this block.
- Check  "did we prevote this block", and only ran ValidateBlock if we did not.

 ### Problem Definition

We see we have duplicate VerifyBlock logic on synced full nodes:
![image](https://github.com/cometbft/cometbft/assets/6440154/f7f980ec-e6b9-4155-9299-99c003db4651)

This operation is expensive, especially in consensus critical contexts!

### Proposal

I think that making a cache for checking if we've already validated a block is better, as it seems easier to also avoid extra redundant validations for `finalizeCommit`. I haven't read that logic, but guessing by how all 3 of these validate block calls are pretty similar in the amount of time spent, I'm guessing its a redundant ValidateBlock as well.

**Comment by cason** [comment]
We had a discussion at some point regarding the multiple validations of the same block. I found this comment:

https://github.com/cometbft/knowledge-base/pull/14#issuecomment-1708062228

**Comment by cason** [comment]
A similar discussion also here: https://github.com/cometbft/cometbft/pull/1391

**Comment by cason** [comment]
We need to separate the validation of a block by the state-machine/blockchain, and the validation of a block by the application. The first validation, whether a block can be appended to the blockchain, could indeed be cached.

**Comment by ValarDragon** [comment]
Just checked, we are indeed also doing an extra validate Block call in FinalizeCommit, that would be mitigated with a simple cache :)

**Comment by ValarDragon** [comment]
Ah we are actually double validating the block in FinalizeCommit -- though this one is super easy to fix using ApplyVerifiedBlock:
![image](https://github.com/cometbft/cometbft/assets/6440154/19029008-7156-4959-b1cc-66c12e0f9ba5)

**Comment by sergio-mena** [comment]
Hi @ValarDragon @cason chiming in here

First of all, the caching mechanism that @ValarDragon is proposing shouldn't be hard to do, and would probably do the trick. So this is still and option.

However, going through @cason's old comments on the algorithm's `valid(v)` (which were made in the context of non-deterministic `ProcessProposal`, i.e., [RFC 105](https://github.com/cometbft/cometbft/blob/main/docs/references/rfc/rfc-105-non-det-process-proposal.md)) I think we can go further if we agree that the following is true:

* `valid(v)` can be thought of consisting of two parts: CometBFT-valid and App-valid. The former being `ValidateBlock`, the latter being `ProcessProposal`.
* The modifications made to the Tendermint algorithm in RFC 105 are correct (in particular, the calls to `valid(v)` that were removed

If we agree this is true, then we can conclude that CometBFT-valid can just be called _where and only where_ App-valid is called; without affecting the algorithm's correctness.

If I didn't terribly miss anything in my reasoning, then the solution I would implement here is aligning `ValidateBlock` with `ProcessProposal`; IOW calling `ValidateBlock` only when we call `ProcessProposal`.

@cason what do you think?

**Comment by sergio-mena** [comment]
@ValarDragon I just posted #2960 for review. We need to wait for @cason to come back from vacation (he's back next Mon). I would like to have his opinion on correctness.
In the meantime, do you think you folks could measure if this PR improves the performance and how much? Thanks!

**Comment by ValarDragon** [comment]
Ah your right, that would argue that we can safely remove those two calls! That sounds good to me, will try to get it tested on mainnet soon! (@czarcas7ic is working on some automation for this, so that way we can also be getting benchmarks that adapt for the fixes we've already gotten in as well!)

From my understanding though, this would save those calls and be a notable time reduction!

**Comment by cason** [comment]
The change in #2928 is nonetheless really relevant.

**Comment by cason** [comment]
> @cason what do you think?

I added my comments/concerns to https://github.com/cometbft/cometbft/pull/2960.

**Comment by sergio-mena** [comment]
Following @cason's observations and comments, and an internal discussion, this is how we agreed to move forward:
* We keep the part where we align the checks in `enterPrecommit`
* But we revert the hunks that are removing the defensive panics
* And, in order to keep the performance improvement that motivated this issue initially, we'll add a cache in memory as @ValarDragon was suggesting
