### ISSUE TITLE
spec: Improve ABCI spec to clearly explain error returns

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#2907]
- [ ] Improve ABCI spec to clearly explain the difference between error codes (inside ) and errors returned by the ABCI calls themselves
- [ ] Fix some error conditions on abci/example/kvstore/kvstore.go

**Comment by hvanz** [comment]
I just noticed this comment explaining the difference between error codes and errors in methods. I think that for app developers it's quite difficult to find, so better to put it clearly in the docs or spec. https://github.com/cometbft/cometbft/blob/main/abci/client/client.go#L21-L23

**Comment by andynog** [comment]
Thanks for the pointer @hvanz, I'll take a look at that.

**Comment by andynog** [comment]
I've added the additional information about ABCI error to the tutorial in docs since it might be easier to find than the spec and we have also code in the kvstore example so it made more sense to add to the docs.

**Comment by sergio-mena** [comment]
I added a comment to the PR. We still need to fix the "Errors" paragraph we have in the spec, as it's explaining errors, but not mentioning the non-recoverable ones.
