### ISSUE TITLE
Effects of a nil `Sha256Checksum` in a `ChecksummedGenesisDoc`

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#2938]
The `GenesisDocProvider` is a type alias for a func
https://github.com/cometbft/cometbft/blob/ce68e90dadb89c3162b8b549dfc3da3c10ec0aa8/node/setup.go#L55

When the logic was implemented, I believe that the expectation was that this `GenesisDocProvider` was going to be 'provided' using `DefaultGenesisDocProviderFunc`, which calculates the sha256 checksum from the jsonBlob of the genesis file content
https://github.com/cometbft/cometbft/blob/ce68e90dadb89c3162b8b549dfc3da3c10ec0aa8/node/setup.go#L59

The problem is that this provider could come from a custom provider. For example, the Cosmos-SDK has a different genesis signature and it needs to pass it's own provider logic, something like:
```
	appGenesisProvider := func() (node.ChecksummedGenesisDoc, error) {
		appGenesis, err := genutiltypes.AppGenesisFromFile(cmtCfg.GenesisFile())
		if err != nil {
			return node.ChecksummedGenesisDoc{}, err
		}
		gen, err := appGenesis.ToGenesisDoc()
		if err != nil {
			return node.ChecksummedGenesisDoc{}, err
		}
		return node.ChecksummedGenesisDoc{GenesisDoc: gen}, nil
	}
```
which returns a `func() (ChecksummedGenesisDoc, error)` that can be used in a `node.NewNode()` as the `GenesisDocProvider`, e.g.
```
tmNode, err := node.NewNode(
		context.TODO(),
		...
		appGenesisProvider,
		...
	)
```

but this might cause issues in 
https://github.com/cometbft/cometbft/blob/ce68e90dadb89c3162b8b549dfc3da3c10ec0aa8/node/setup.go#L573

because the `Sha256Checksum` field is not validated (look at the example above (`return node.ChecksummedGenesisDoc{GenesisDoc: gen}`) so it will be nil. 

It will fail when trying to save it in the `stateDB` here because a `nil` value cannot be saved on the database
https://github.com/cometbft/cometbft/blob/ce68e90dadb89c3162b8b549dfc3da3c10ec0aa8/node/setup.go#L606

and there is other logic in this function that relies on a `Sha256Checksum`, so in my opinion, we might need to account for that in the code or at least add more tests. I agree that in part this is caused by a integrator not adding the checksum (maybe we need to add some more information to the docs to say that is expected), but at the same time as a defensive measure we might need to ensure we can handle this scenario and that it will not cause other issues in the future.

**Comment by sergio-mena** [comment]
Can you come up with a failing unit test that demonstrates the problem?

**Comment by alesforz** [comment]
> Can you come up with a failing unit test that demonstrates the problem?

Check #3526.
