### ISSUE TITLE
Lower default flush timeout

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#2988]
### Summary

This issue is based on conversations with @melekes , and experimentation in production done on both Osmosis and Injective.

After you "send a message to a peer", it doesn't actually send until either:
* You hit a 64kb chunk of total messages to send
* `flush_throttle_timeout` elapses

The default flush_throttle_timeout is `100ms`. Both osmosis and injective have found great success in performance lowering this to `10ms`, and have not tested lower values.

On the given profile I'm looking at, of an Osmosis synced-to-tip full node at `10ms`, we see that 70% of outbound packets are stuck waiting for `flush_throttle_timeout`! 

![image](https://github.com/cometbft/cometbft/assets/6440154/80b5319d-50f3-47b7-99e0-550a8ad53665)

We argue this by looking at the ratio of the top call from SendRoutine (happens on timer timeout), vs call from .Write() which only writes to file if you hit buffer size. This is a time ratio of 56s in top-level flush, to 23s in the .Write() call. IMO this suggests it is worth lowering this buffer timeout much further. (To be honest, I'm unclear if we have any evidence this flush timeout is even helpful)

One nuance that could be happening, but I think is unlikely, is that during consensus time we always hit the buffer size, and only do flush timeouts during idle periods. I think its unlikely for consensus time, because we saw that lowering this flush timeout had direct impacts on validators staying synced/ getting votes propogated to the network. (E.g. when there is no blockparts or many mempool txs filing the buffer)

### Problem Definition

We wait far too long on networks, vs flushing faster.

### Proposal

Lower default flush timeout from 100ms to 5ms

**Comment by sergio-mena** [comment]
I am reproducing below the data reported by the Injective team for a value of 10ms for both `flush_throttle_timeout` and `peer_gossip_sleep_duration`. Posting here to further document this change (thanks to the Injective team for sharing this).

> Hey, we’ve observed that validator uptime is significantly degraded as block size increases. The majority of our validators did not sign on blocks that exceeded 100KB.
>We changed:
>  &nbsp; `flush_throttle_timeout` from 100ms to 10ms
>  &nbsp; `peer_gossip_sleep_duration` from 100ms to 10ms
> in config.toml and we observed significant performance improvements. Block time is reduced and assume it’s due to the fact that we reach prevote and precommit sooner and/or missed consensus rounds are no longer taking place.
>Additionally, missed blocks on validators almost reached zero on those that made the change. The average missed blocks on validators was around ~15K and went down to 50 upon making these changes (see screenshots). We’re progressively asking validators to apply these changes and monitoring the network.
>Meanwhile, we’re running more tests to find the optimal value as 10ms was randomly chosen.



![telegram-cloud-photo-size-4-6043983863216193761-y](https://github.com/cometbft/cometbft/assets/15381133/c4677a01-4cb4-4ba8-ba1f-cbdffcf33a5b)

![image](https://github.com/cometbft/cometbft/assets/15381133/ecb93a4b-31fd-4dbb-b5bc-f0d817074409)

**Comment by sergio-mena** [comment]
@ValarDragon Do you folks happen to have similar graphs for `flush_throttle_timeout` set to 5 ms? If yes, if would be great to post them here 🙏

**Comment by ValarDragon** [comment]
We have data points for individual validators who upgraded, not network wide unfortunately(so no graphs)
