### ISSUE TITLE
Bandwidth optimization

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#30]
Inspired by tendermint/tendermint#9880  but expanded here.

High-level tracking issue for general bandwidth optimization efforts.

CometBFT-based networks consume large amounts of bandwidth. 
This results in high operational costs for the network operators (typically, the validators). 
We need to reduce the bandwidth consumption of the solution while maintaining its core properties, in terms of correctness, progress and fault-tolerance.

Several strategies to reduce the bandwidth usage in CometBFT have been proposed by CometBFT developers and community members. 
While some of these ideas are simple to implement, others require much larger efforts, implying impactful modifications on the protocol. 
This results in a dilemma when looking for a solution. We also note that there is currently no general strategy to validate a solution, whether it would be through local tests, or by collecting information from the operators. 
A third concern comes from the fact that while there are clear quick wins, it seems also necessary to prepare a long term effort. 
The subject of improving bandwidth usage in peer-to-peer systems is vast, with decades of efforts in research and practical solutions. 

This issue tracks our efforts in addressing a large spectrum of approaches to reduce bandwidth usage in CometBFT. 
We prioritize the work based on their impact on use cases, on the effort needed to implement it, and on how it helps pave the way for future improvements. 
The main problem is subdivided as listed next. Note that some of the problems/solutions might overlap.

```[tasklist]
### Preliminary work
- [ ] #1048
- [ ] #1076
- [ ] #1081
```

```[tasklist]
### Short term goals
- [ ] #1058
- [ ] #1060
- [ ] #1059
- [ ] #1061
```

```[tasklist]
### Long term goals
- [ ] #11
- [ ] #2027
- [x] Feasibility study to replace the current gossip protocol
- [ ] #3297
```

## Previous efforts

- Investigate what kind of data is consuming the most bandwidth
   - https://github.com/tendermint/tendermint/pull/9706 ([Rendered RFC](https://github.com/cometbft/cometbft/blob/main/docs/rfc/tendermint-core/rfc-027-p2p-message-bandwidth-report.md))
   - #26
   - #734 
   -Changes from tendermint/tendermint#9760, released in  v0.34.25, testing for backwards compatibility in tendermint/tendermint#9928

## Related, but not covered by this issue.

- [ ] Investigate protocol change options for more substantial bandwidth optimization
    - [ ] #13
    - [ ] #14 

# References
- https://github.com/tendermint/tendermint/issues/9575 (efforts toward bandwidth improvements in Q4-2022)

**Comment by hvanz** [comment]
With the finalization of the DOG protocol (#3297) we can close this issue on bandwidth optimization of transaction propagation of the mempool. Note that optimization of block proposals (#13) and votes (#14) are covered in separate issues.
