### ISSUE TITLE
Remove dependency from `minio/sha256-simd` library

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#3071]
The dependency to this library was introduced by https://github.com/cometbft/cometbft/pull/2765.

It is present on `main` and `v1.x` branches (which is still unreleased).

We should at the moment stick to the standard `crypto/sha256` library, with the same purpose.

The adoption of `minio/sha256-simd` was proposed in https://github.com/cometbft/cometbft/pull/2909, but at the moment we are not planning to switch to this non-standard library, as summarized in the following comment:

> We discussed about this in our internal meeting today. These are the conclusions:
> 
> 1. We currently don't have performance data that shows an obvious gain in the production setups where CometBFT is used
> 2. We could gather such performance data ourselves as a due-diligence activity, but we don't have cycles ATM
> 3. There is an ongoing longer term solution, described in #2241, whereby an app can have CometBFT use custom hashing logic.
>     * This longer term solution will render our efforts in point 2 unnecessary
> 
> Therefore, we will:
> 
> * Use this issue to move all imports of `minio/sha256-simd` (BLS-related code) to `crypto/sha256`
> * Wait for #2241 to be completed so that users can do what is suggested in this issue on app-side code

_Originally posted by @sergio-mena in https://github.com/cometbft/cometbft/issues/2909#issuecomment-2107944974_

**Comment by cason** [comment]
Ideally we should adopt `crypto/tmhash`, our own lib, which is currently a wrapper to `crypto/sha256`. And in a second moment, allow for multiple implementations of this libraries, via build option of something similar.

https://github.com/cometbft/cometbft/pull/2909#issuecomment-2100811221

**Comment by andynog** [comment]
I agree that we should revert the additional library added in the BLS key, as we don't have enough benchmarking tests to justify the need for the minio library to make BLS signatures feasible. 

Since BLS is optional to build with a flag, I believe it would be appropriate to encapsulate the logic under tmhash and work towards a solution that allows tmhash to be modular and utilize different crypto hashing libraries.
