### ISSUE TITLE
API support to query mempool transactions by transaction hash

### ISSUE THREAD

**Issue by charithabandi** [cometbft/cometbft#3079]
### Summary

API support to query mempool transactions by transaction hash

### Problem Definition

Currently the only way to check if a transaction is in the mempool and retrieve raw Tx bytes corresponding to a TxHash is by going through all the mempool transactions, computing the Tx hashes and verifying the Tx Hash. We have observed that, this is a potential DDOS vector, and a single client can bring down the node, by querying for the transaction repeatedly as the hash computations are pretty expensive and hog down CPU drastically.  This also impacts the block times significantly.

![image](https://github.com/cometbft/cometbft/assets/45089429/38acaf6d-86bd-4367-8c45-47b0bc710146)

Exposing this API brought down the block times singnificantly
![image](https://github.com/cometbft/cometbft/assets/45089429/9aebd523-62b7-4c94-b0bc-650bac29b391)

### Proposal

Mempool already has the infrastructure to support Tx lookups using the TxHash, It just need to be exposed.
```golang
	// Concurrent linked-list of valid txs.
	// `txsMap`: txKey -> CElement is for quick access to txs.
	// Transactions in both `txs` and `txsMap` must to be kept in sync.
	txs    *clist.CList
	txsMap sync.Map
```

**Comment by andynog** [comment]
Hi @charithabandi, thanks for submitting this issue. Just for clarification, are you talking about using the RPC endpoint `/unconfirmed_txs` ? If so, is the idea to provide a way to do something like `unconfirmed_txs?hash=[tx_hash]` ? and you get a response confirming if the tx is in the mempool?

I can't find the code for that profiling image you attached above, could you please provide more details or point in the code what are you referring to ?

**Comment by charithabandi** [comment]
![Screenshot 2024-05-16 at 10 16 23 AM](https://github.com/cometbft/cometbft/assets/45089429/a222f9e6-2c03-4b2d-986f-f401f4133b4b)
If it's of any use, here is the snippet of our API and the changes we made to avoid this issue

**Comment by melekes** [comment]
Done in https://github.com/cometbft/cometbft/pull/3109
