### ISSUE TITLE
Execute on the v0.38 release QA plan and capture the results

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#31]
Tasks:

  - [x] Capture v0.37 baseline metrics (Optional, to do only if existing v0.37 metrics can't be reused)
  - [x] Improve files with intructions as the tests are run
    - [x] #878
  - [x] qa: Capture v0.38 pre-release metrics
    - [x] #841
    - [x] #842
  - [x] #843
  - [x] Validate that there's no meaningful, substantial regression from v0.37 to v0.38
    - Fix all major issues found

DoD:

  - Report is reviewed and merged
  - No major bugs standing on `v0.38.x`

Original issue: tendermint/tendermint#9921

**Comment by lasarojc** [comment]
@sergio-mena , are we good to close this?

**Comment by sergio-mena** [comment]
@lasarojc I think so, not sure why I didn't close this
