### ISSUE TITLE
Add callback for publishing pending transactions from mempool

### ISSUE THREAD

**Issue by mmsqe** [cometbft/cometbft#3108]
### Summary

Add [PublishEventPendingTx](https://github.com/mmsqe/cometbft/blob/4d00e28bcfec05a0405489cdf7ff91883c744bbf/types/event_bus.go#L171) in EventBus

### Problem Definition

Currently we rely on [EventTx](https://github.com/mmsqe/cometbft/blob/4d00e28bcfec05a0405489cdf7ff91883c744bbf/types/events.go#L23) for [newPendingTransactions](https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub), but transactions are published after they are mined in a block. There is no way to subscribe to pending transactions.

### Proposal

1. add callback for new transaction that added to the mempool
2. publish pending tx event for each newly inserted transaction

**Comment by andynog** [comment]
Hi @mmsqe, usually the events are triggered from the state package, after a block has been committed. Emitting events for each transaction added to the mempool might be a new use case. I see that in your fork you seem to have implemented that though. 

Using the `/unconfirmed_txs` endpoint not an alternative ?  I think it's more a pull that push behavior but just trying to understand better the use cases for implementing a new model.

**Comment by mmsqe** [comment]
Thanks @andynog, you mean long poll that block until new data available and return the response, which works similar as real-time push for web socket subscribe right? But `/unconfirmed_txs` is just normal API which won't block, client need keep pulling.

**Comment by andynog** [comment]
yes, the mempool txs are not correlated with new block events, so you would need to keep polling for data on that endpoint.

**Comment by hvanz** [comment]
The mempool does not use the event bus and we actually don't want to add this dependency. It goes against our effort of making the mempool and other components more modular. It would be better to understand the use case for issue so we can find an alternative implementation.

**Comment by cason** [comment]
The transactions that are added to the mempool are transactions that have been accepted by the local instance of the application using the ABCI `CheckTx` method. This is the best point, in the current architecture, to identify when new transactions are available, and multiple applications use this information for their own goals (e.g., derive some information, produce some order, compute something from all transactions accepted). Adding a listener there for new transactions is a way to go.

But, from what I understand, you want to retrieve this information (new transactions) using a RPC endpoint or other solution listening to the events produced by Comet's event bus. While this adds some overhead, to produce all those events, there is actually no restriction against implementing such a solution, provided that, as already happens with all other events produced in this bus, slow (or no) readers do not impact performance, namely, block the ordinary operation of the mempool.

@hvanz comment above is relevant from a modularity point of view. But from #3111, it appears that the goal is to provide this as an optional behavior that, for all effects, is implemented outside the mempool. We may discuss where in the code/logic we should publish this event, but a priori I don't have anything against this solution.
