### ISSUE TITLE
Could use pointer for `service.BaseService`

### ISSUE THREAD

**Issue by islishude** [cometbft/cometbft#3265]
I see there are many pointer dereference

`xxx.BaseService = *service.NewBaseService(logger, "xxx", xxx)`

I think cometbft can just the pointer of `service.BaseService`.

```go
type Node struct {
	*service.BaseService
}
```

in the cosmos-sdk, it has the same feature in base app package, and it uses pointer.

```go
type SimApp struct {
	*baseapp.BaseApp
}
```

**Comment by cason** [comment]
We probably could do that, but what are actually the benefits?

**Comment by islishude** [comment]
> I see there are many pointer dereference

the thing is that.
