### ISSUE TITLE
[docs] Remove validator set change query from block_search endpoint examples

### ISSUE THREAD

**Issue by dasanchez** [cometbft/cometbft#3266]
Hi! The `block_search` endpoint has examples listed here:
* https://github.com/cometbft/cometbft/blob/main/docs/guides/app-dev/indexing-transactions.md#querying-block-events
* https://docs.cometbft.com/v0.37/rpc/#/Info/block_search

They list both a `val_set.num_changed > 0` and a `valset.changed > 0` query, but neither seems to work with Gaia `v17.2.0` (CometBFT `v0.37.6`).
Are these queries still active, or have they been deprecated?

A delegation went through at height 6884760 in the ICS testnet, triggering a valset change:
```
curl -s "https://rpc.provider-sentry-01.ics-testnet.polypore.xyz/block_results?height=6884760" | jq '.result.validator_updates | length'
1
```

If I try to search for that block using the `valset.changed>0` query with `block_search`, I don't get the 6884760 block in the results:
```
curl -s "https://rpc.provider-sentry-01.ics-testnet.polypore.xyz/block_search?query=\"block.height>6884759%20AND%20block.height<6884761\"" | jq '.result.total_count' 
"1"

curl -s "https://rpc.provider-sentry-01.ics-testnet.polypore.xyz/block_search?query=\"block.height>6884759%20AND%20block.height<6884761%20AND%20valset.changed>0\"" | jq '.result.total_count'
"0"
```

Thanks!

**Comment by melekes** [comment]
Thanks for flagging this 👍 We don't have a key like that in CometBFT (at least not presently).

For Cosmos SDK events, please see https://docs.cosmos.network/v0.50/learn/advanced/events and https://docs.cosmos.network/v0.50/build/modules/staking#events.
