### ISSUE TITLE
add new method `TryAddTx` to mempool reactor

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#3296]
This new method will serve as a single point of access to the mempool reactor for incoming transactions. 

Currently to add a transaction we call `CListMempool.CheckTx(...)` directly, either from the `broadcast_tx_*` RPC endpoints or from the `Receive(...)` method in the reactor. The goal of `TryAddTx` is to have a single method in the reactor where in the future we can put common logic for adding transactions, such as handling errors or sending new messages. In particular, this refactoring will be needed by the implementations of mempool lanes and the DOG protocol.

**Comment by cason** [comment]
Can we get some context regarding the expected behavior of this introduced primitive?

**Comment by hvanz** [comment]
@cason I updated the description.
