### ISSUE TITLE
Remote signer client should have ability to manage multiple private keys

### ISSUE THREAD

**Issue by islishude** [cometbft/cometbft#3299]
### Summary

The remote signer client can manage multiply private key, so that a validator don't need to run multiple nodes at once.

### Problem Definition

A chain can't allow validator to stake more than X.

if someone wants to stake more than the value, he needs to run multiple nodes.

Because current remote signer interface is just for single private key manager.

In the Ethereum, it has the same feature, the validator client, which can manage multiple private key.

But it can not implement in the cometbft client.

### Proposal

Update the PrivValidator interface

```go
type PrivValidatorV2 interface {
	// GetPubKey returns the public key of the validator.
	GetPubKey() ([]crypto.PubKey, error)

	// SignVote signs a canonical representation of the vote. If signExtension is
	// true, it also signs the vote extension.
	SignVote(chainID string, pubKey crypto.PubKey, vote *cmtproto.Vote, signExtension bool) error

	// SignProposal signs a canonical representation of the proposal.
	SignProposal(chainID string, pubKey crypto.PubKey, proposal *cmtproto.Proposal) error

	// SignBytes signs an arbitrary array of bytes.
	SignBytes(pubKey crypto.PubKey, bytes []byte) ([]byte, error)
}
```

Add query string to the `priv_validator_laddr = "tcp://127.0.0.1:26665?v=2"` configuration to allow v2 upgrade in a place.

**Comment by melekes** [comment]
What's the issue with running multiple instances of https://github.com/iqlusioninc/tmkms? Operational complexity?
