### ISSUE TITLE
v0.38 release plan

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#33]
Was tendermint/tendermint#9428

The primary focus of the v0.38 release will be rolling out ABCI++ vote extensions and `FinalizeBlock` functionality.
  * [ ]  #12
      * [x]  We need to improve our QA process during Q4 in order to reduce the amount of manual work involved
  * [x] #66
  * [x] #39
  * [x] #595
  * [x] Cut first alpha release
  * [x] Cut release candidate
  * [x] docs: Enable build for `v0.38.x` branch
  * [x] #31 
    * [x] Capture v0.37 baseline metrics (Optional, to do only if existing v0.37 metrics can't be reused)
    * [x] qa: Capture v0.38 pre-release metrics
    * [x] Validate that there's no meaningful, substantial regression from v0.37 to v0.38
  * [x] Execute on the QA plan for integration with the Cosmos SDK
  * [x] Cut final v0.38.0 release
  * [x] Either remove priority mempool or forward port the PR associated to #39 to main and v0.38.x (if exists)
  * [x] https://github.com/cometbft/cometbft/pull/423
  * [x] #571

### Deprioritised from this release:

  * [ ]  Operators should have more control over bandwidth consumption
    * [ ]  Investigate where Tendermint bandwidth is being consumed (perhaps capture this in an RFC as an articulation of the problem space)
    * [x]  Find short-term wins/low-hanging fruit where bandwidth consumption can be reduced (ideally in Q4 of 2022)
* [ ] #54

**Comment by elmatrwy** [comment]
> Was tendermint/tendermint#9428
> 
> The primary focus of the v0.38 release will be rolling out ABCI++ vote extensions and `FinalizeBlock` functionality.
>   * [ ]  #12
>       * [x]  We need to improve our QA process during Q4 in order to reduce the amount of manual work involved
>   * [x] #66
>   * [x] #39
>   * [x] #595
>   * [x] Cut first alpha release
>   * [x] Cut release candidate
>   * [ ] docs: Enable build for `v0.38.x` branch
>   * [x] #31 
>     * [x] Capture v0.37 baseline metrics (Optional, to do only if existing v0.37 metrics can't be reused)
>     * [x] qa: Capture v0.38 pre-release metrics
>     * [x] Validate that there's no meaningful, substantial regression from v0.37 to v0.38
>   * [ ] Execute on the QA plan for integration with the Cosmos SDK
>   * [ ] Cut final v0.38.0 release
>   * [x] Either remove priority mempool or forward port the PR associated to #39 to main and v0.38.x (if exists)
>   * [x] https://github.com/cometbft/cometbft/pull/423
>   * [x] #571
> 
> 
> ### Deprioritised from this release:
> 
>   * [ ]  Operators should have more control over bandwidth consumption
>     * [ ]  Investigate where Tendermint bandwidth is being consumed (perhaps capture this in an RFC as an articulation of the problem space)
>     * [x]  Find short-term wins/low-hanging fruit where bandwidth consumption can be reduced (ideally in Q4 of 2022)
> * [ ] #54

Thankyou

**Comment by elmatrwy** [comment]
Thankyou

**Comment by melekes** [comment]
Closing since v0.38 is out.

> Investigate where Tendermint bandwidth is being consumed (perhaps capture this in an RFC as an articulation of the problem space)

tracking issue: https://github.com/cometbft/cometbft/issues/30
