### ISSUE TITLE
release v0.37.7

### ISSUE THREAD

**Issue by dynst** [cometbft/cometbft#3301]
It's been a few months and the [v0.37.x branch](https://github.com/cometbft/cometbft/commits/v0.37.x/) has accumulated 13 different performance improvements since v0.37.6 was tagged, it'd be great to have a release that includes them.

**Comment by melekes** [comment]
I'd like https://github.com/cometbft/cometbft/pull/3196 to be included as well.

**Comment by adizere** [comment]
We're about to release v1-rc1, once we do that we can do patch releases on 0.38 and 0.37 as well. So this will likely happen in July, hope this timeline works.

**Comment by adizere** [comment]
Scheduled for this week.
