### ISSUE TITLE
p2p: more peers connect than the maxInbound / maxOutbound set

### ISSUE THREAD

**Issue by czarcas7ic** [cometbft/cometbft#3315]
While working on the same geographical region peering PR, I was able to recreate an issue that some of our node operators have complained about. With 0 inbound peers set and 1 outbound peer set as the max, my n_peers connected would jump to 25 when I started the node. This was on the osmo/v0.37.4 branch, which is not too divergent from mainline. After tracing it down, I found out that we are respecting the number of peers to dial in the ensurePeers logic branch, but the bug occurs here:

https://github.com/cometbft/cometbft/blob/f4c622fe597f925df9d7cd2842b726eab915aa98/p2p/pex/pex_reactor.go#L370-L385

This logic branch disregards any user defined max limits and dials peers here. In my branch i just commented out this entire logic branch and the limits were once again respected, but made an issue here to discuss what the real desired solution is. Sadly Reactor doesn't have access to user configs as it stands so it's not as simple as checking if we are at the max number of peers already.

**Comment by czarcas7ic** [comment]
Eddie from freshSTAKING helpfully pointed me to this issue that I was unaware of https://github.com/cometbft/cometbft/issues/486

Feel free to close this issue and we can work off that one. I am happy to implement a solution, just would like to know what direction we want to go with this prior to taking time to work on it with tests etc.

**Comment by cason** [comment]
The solution is not hard, but I never found much time to deal with it.

Essentially, if we could signalize to `ensurePeersRoutine` that it has to run `ensurePeers` immediately, instead of waiting for the next interval (30s), we would have solved this problem for _regular nodes_.

For nodes in _seed mode_, the behavior is a little more complex.
