### ISSUE TITLE
Cache constructing and marshalling proposal.ToProto

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#3413]
### Summary

We observed during a period of very large blocks on osmosis (5MB), `proposal.ToProto` within gossipDataRoutine, ended up taking large amounts of system resources. (Presumably our outbound consensus channel was filled?) 

This call here: https://github.com/cometbft/cometbft/blob/main/internal/consensus/reactor.go#L1245 (but at the v0.37.x code location ofc)

The node spent .7% of total system CPU time in proto marshalling the proposals, and another .8% for making heap copies of it after (the p2p wrapper for it requires a copy on stack, then push-to-heap)

We could make this fast if this failure mode is correct (e.g. just  cache the p2p-ready version of proposal, already in the p2p-wrapper format, after doing it once. (And eventually marshalled cref #3185 ))

But this is really suspicious to me, and I have never seen this take time in any other profile ever before. (And other parts of gossipDataRoutine took extremely long). So I think the real questions are:
- were we busy waiting? If so (simply) we can not busy-wait
- Understand why the outbound data channel (size 100) got full

I'm at a loss for why the outbound data channel would have gotten full though

**Comment by ValarDragon** [comment]
Actually going to re-write this issue as "Prevent busy waiting when Consensus SendQueue full"

**Comment by cason** [comment]
In any case, marshalling a `Proposal` shouldn't be slower than marshalling, say, a `Vote`. It is pretty trivial.
