### ISSUE TITLE
Clarify the breaking nature of v1 upgrade

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft#3416]
### Summary

Suppose a team is upgrading from v0.38 to v1. 

What do they need to know when it comes to the breaking nature of this upgrade? Do validators need to coordinate? Do they need to migrate their config.toml? Do the answers depend?

Ref: https://github.com/kwilteam/kwil-db/pull/760

### Proposal

Let's provide more guidelines regarding upgrading to v1. Consider:

- We do a very good job of detailed guidelines in https://github.com/cometbft/cometbft/blob/main/UPGRADING.md. Let's make sure this doc answers the questions in the KwillDB PR linked above.
- Let's make sure upgrading guidelines are discoverable, either/ both from docs.cometbft.com as well as from other places (main readme.md, a blog post, X thread).

**Comment by andynog** [comment]
I'll take this on.

Another suggestion is to include a migration guide as part of the documentation. Perhaps a `Migrations` section under `Reference Documentation` would be a good approach, especially if the instructions for migrating from `v0.38` to `v1` are extensive.

The IBC team already has numerous documents about migrations on their documentation site, so this is a compelling idea.
https://ibc.cosmos.network/v8/migrations/sdk-to-v1/
