### ISSUE TITLE
Genesis file validation doesn't check the validators' `PubKey` type.

### ISSUE THREAD

**Issue by alesforz** [cometbft/cometbft#3514]
### Context
The function validating the genesis file:
https://github.com/cometbft/cometbft/blob/63ef074cc945cc9bd3ca7ce0d8c1ed1ba8cdbf2a/types/genesis.go#L69
does not check if each validator uses a `PubKey` type that we accept, that is, it appears in `genesis.ConsensusParams.Validator.PubKeyTypes`.

Consequently, we incorrectly allow a chain to start even if a validator uses an unsupported `PubKey` type.

### The Change
Add a check that, for each validators in the genesis, makes sure that their key type is contained in the list `genesis.ConsensusParams.Validator.PubKeyTypes`.

**Comment by frankie-mur** [comment]
Hey team, could I give this a shot? First time contributor project looks very interesting :)

**Comment by cason** [comment]
Good catch. But are you sure we don't check this somewhere on the `node` package/implementation?

**Comment by alesforz** [comment]
> Good catch. But are you sure we don't check this somewhere on the `node` package/implementation?

Looking at the `node` pkg, my understanding is that [BootstrapState](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/node/node.go#L158) and [NewNode](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/node/node.go#L279) call [LoadStateFromDBOrGenesisDocProvider](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/node/setup.go#L577) which in turn calls `ValidateAndComplete`, i.e.,  the offending function missing the check I mention in the issue's description.

Inside `LoadStateFromDBOrGenesisDocProvider` we can follow the path [`stateStore.LoadFromDBOrGenesisDoc`](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/node/setup.go#L628) -> [`MakeGenesisState`](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/state/store.go#L279) to see that we call [`ValidateAndComplete`](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/state/state.go#L304) again (which doesn't do the check), then [`NewValidator`](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/state/state.go#L316) and [`NewValidatorSet`](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/state/state.go#L318), neither of which verify the `PubKey` type. 

Am I missing other steps in the workflow that could do the missing check?

**Comment by alesforz** [comment]
> Good catch. But are you sure we don't check this somewhere on the `node` package/implementation?

Another point: if a validator puts a _syntactically_ incorrect `PubKey` type (e.g., a random or misspelled string) our custom [json library](https://github.com/cometbft/cometbft/blob/main/libs/json/doc.go) returns an "unknow type" error [here](https://github.com/cometbft/cometbft/blob/b47d18ea417ad0873c2adf78b491d785d1012dc2/libs/json/decoder.go#L229) (I confirmed this behavior in unit tests). So we check this corner case.

However, if the validator puts a correct `PubKey` type, just not supported by the chain to be started, then the validation is successful, which is erroneous behavior.

**Comment by sergio-mena** [comment]
@frankie-murthanks for offering to help us with some issues. This one is already assigned to @alesforz, so I'm afraid that re-assigning it now would cause us some disruption.

If you really want to help us with useful stuff, please take a look at #1140. If you're up for it, you can pick up one of the packages that aren't completed yet and post a PR exporting the errors occurring in that package. You can check PRs for completed packages to get inspiration on what we're trying to do here.
