### ISSUE TITLE
chore (indexer): Fix break statements 

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#3546]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
main, v1.x, v0.38.x, v0.37.x

### Description

In many places within the kv indexer we have loops that should be interrupted when the enclosing context is completed. The code however does not break from the loop, rather just from the select. 

This was partially fixed by @melekes  in https://github.com/cometbft/cometbft/issues/2647 but still remains in some places. 

It is present in older versions as well so should probably be backported to all the versions that are still supporting non critical bug fixes.

**Comment by cason** [comment]
Is this issue the same as https://github.com/cometbft/cometbft/issues/3544?

**Comment by jmalicevic** [comment]
Ah @alesforz was faster. Duplicate of #3544
