### ISSUE TITLE
refactor(config): Remove genesis hash from config

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#3547]
## Genesis hash saved in config file but read-only

#1324 saves the genesis hash in the config file to check it against the has from the DB. However, its sole purpose is to [forward](https://github.com/cometbft/cometbft/blob/fbca5acef2a4410d28c3b11baf364dd4c788190c/node/node.go#L295) this config flag to be checked on node boot-up against the hash of the genesis file if it is the first boot or the hash stored in the DB if the node has already read in a genesis file before. The user is NOT supposed to put the hash into the config file manually.  We decided at the time to not break any APIs and apply this approach.

Upon further discussion, we chose this to be a suboptimal way of doing things and bad UX. The flag should be passed as an argument, even if APIs are being broken. 

Once a PR is open, we should however check whether we are causing major breaking changes for some users and let them know that this update is coming.

**Comment by sergio-mena** [comment]
I would be best if this could make it to `v1.x` before cutting `v1.0.0`
