### ISSUE TITLE
docs: clarify the meaning of `VoteExtensionsEnableHeight == 0`

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#3601]
It means disabled, but the documentation and code comments (that also play the role of documentation, for instance for protobufs) do not make this information clear enough.

**Comment by andynog** [comment]
we have some information here, but agree that we could clarify the implications of having a `0` value

https://docs.cometbft.com/v1.0/spec/abci/abci++_app_requirements#featureparamsvoteextensionsenableheight

**Comment by sergio-mena** [comment]
> -1 or something might have been clearer [instead of 0 as disabled value]

Not possible, as the disabled value needs to be the golang zero value.
