### ISSUE TITLE
e2e: nightly failures on v1.x due to cometbft-db image upgrade

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#3640]
## Bug Report

The e2e nightly tests on `v1.x` are currently failing as seen [here](https://github.com/cometbft/cometbft/actions/runs/10259122301) 

While troubleshooting the failures, I've bi-sect the latest changes merged into `v1.x` and found out the error started happening after [this PR](https://github.com/cometbft/cometbft/pull/3599/files) was merged.

In workflow run logs, there is an error:

```
validator01  | ERROR: failed to create node: unknown db_backend boltdb, expected one of badgerdb,goleveldb,memdb,pebbledb,rocksdb
```

tracing back, noticed that the `generator` on `v1.x` still includes `cleveldb` and `boltdb` which might include them in the manifests generated when running the command:

```
./build/generator -g 5 -d networks/nightly/ -p
```

which will make the workflow fail to run with the error mentioned above because we've upgraded the image in the Dockerfile in `v1.x`

```
FROM cometbft/cometbft-db-testing:v0.13.0
```

We'd need to cherry-pick the changes from [this PR](https://github.com/cometbft/cometbft/commit/81d8d0787e7d5c838f57b50aef126de43c8abe0e#diff-40ef656313ea7873bfaf38026d93c96559340552d918492dd3f68c723c04addf) that ~~deprecated~~ removed these two databases on `main` or try to backport the changes to `v1.x`. 

At least the changes in the `generate.go` need to be implemented in `v1.x` in order to allow the `e2e nightly v1.x` workflow to run properly again.

**Comment by cason** [comment]
> We'd need to cherry-pick the changes from [this PR](https://github.com/cometbft/cometbft/commit/81d8d0787e7d5c838f57b50aef126de43c8abe0e#diff-40ef656313ea7873bfaf38026d93c96559340552d918492dd3f68c723c04addf) that deprecated these two databases on main or try to backport the changes to v1.x.

From the PR description, we are deprecating these DBs on v1.x, but not removing them.

**Comment by cason** [comment]
The simplest approach here is to downgrade the version of `cometbft-db` on `v1.x` branch.

**Comment by andynog** [comment]
> > We'd need to cherry-pick the changes .....that deprecated these two databases on main or try to backport the changes to v1.x.
> 
> From the PR description, we are deprecating these DBs on v1.x, but not removing them.

Actually we removed them, not deprecated. Just corrected that in the PR description.

**Comment by andynog** [comment]
To clarify here:

In `comtebft-db` release `v0.12.0` the `cleveldb` and `boltdb` were deprecated, and in release `v0.13.0` they were removed (but the [entry is changelog was missing](https://github.com/cometbft/cometbft-db/issues/175)). 

Since the `combetbft-db` dependency was bumped in `v1.x` that triggered failures in nightly. So the team is evaluating if the cometbft bump should be reverted on v1.x or we should leave it there and add the changes required to make nightly work.
