### ISSUE TITLE
Release 0.38 branch for upcoming gaia cosmos hub release

### ISSUE THREAD

**Issue by chillyvee** [cometbft/cometbft#3664]
Is it possible to tag a release of the v0.38 branch to include the #3565 fix?

v0.38 will be used in the v19 gaiad for cosmos hub in less than a week

https://www.mintscan.io/cosmos/proposals/948

https://github.com/cosmos/gaia/blob/v19.0.0/go.mod#L21

**Comment by sergio-mena** [comment]
Closed by #3684 and accompanying release (`v0.38.11`)
