### ISSUE TITLE
doc/spec/core/encoding: secp256k1 encoding is inconsistent with the documentation

### ISSUE THREAD

**Issue by islishude** [cometbft/cometbft#3727]
We can see that the address of secp256k1 pubkey is the same with bitcoin and cosmos sdk.

It's derived from sha256 and then ripemd160

https://github.com/cometbft/cometbft/blob/fe696a4757c908415dd210ae241298b86dea5a3e/crypto/secp256k1/secp256k1.go#L146-L158

But the documentation 

> The address is the first 20-bytes of the SHA256 hash of the raw 32-byte public key

**Comment by cason** [comment]
The referred documentation was updated by https://github.com/cometbft/cometbft/pull/3258, @melekes can you have a look?

**Comment by cason** [comment]
In any case, I think we need the test units of the package to relate to its documentation.
