### ISSUE TITLE
A redelegate all staked tokens from your validator function

### ISSUE THREAD

**Issue by Kwaskoff** [cometbft/cometbft#3729]
### Summary

[A redelegate all staked tokens from your validator function](https://forum.cosmos.network/t/a-redelegate-all-staked-tokens-from-your-validator-function/14286)

### Problem Definition

We have such validators in many networks “redelegate, pls!”. For example in cosmos hub:

1. [Mintscan](https://www.mintscan.io/cosmos/validators/cosmosvaloper1jknayw5aejl5l2lctpxw8uy7x0xmc5vmu4q2zr)
2. [Mintscan](https://www.mintscan.io/cosmos/validators/cosmosvaloper1z66j0z75a9flwnez7sa8jxx46cqu4rfhd9q82w)
3. [Mintscan](https://www.mintscan.io/cosmos/validators/cosmosvaloper14r7kzdf6gfh3t9v2c7efdp2fn5apsl93qga2ed)
4. [Mintscan](https://www.mintscan.io/cosmos/validators/cosmosvaloper1nths3ruxgdthfxx3y8d4a9wfq5a2mkwhvc3k8g)

Any validator would not want to punish its inattentive stakers, and users who spend time on family and agriculture would not lose their pennies and would tell how much care they are treated in our ecosystem!

### Proposal

 add to tendermint a function to redelegate all staked tokens from your validator to any of the last 10 in the active set. This is necessary in case of termination of activity.

**Comment by 80an** [comment]
I support this idea 100%.

**Comment by pas1g** [comment]
yes, it is useful

**Comment by SergeyMagic** [comment]
Very nice idea!

**Comment by m1amgn** [comment]
Great idea. Very useful for delegators.

**Comment by cason** [comment]
CometBFT, and Tendermint consensus, does not handle validator sets. It is the application, or a framework such as Cosmos SDK, that does that. There is no definition of delegation on CometBFT. There is not even the concept of stake. What matters for CometBFT is the validator set (signing keys) and the associated voting power. And it is passed to Comet by the application, in the sense that Comet does not have any role on that.

**Comment by andynog** [comment]
As @cason mentioned, this is an application's concern. You can open this issue on the https://github.com/cosmos/cosmos-sdk repository. 

The SDK has the staking module https://docs.cosmos.network/v0.50/build/modules/staking

@Kwaskoff I'll be closing this issue since it's not related to CometBFT but I've provided some directions above that you can follow-up. Thanks !
