### ISSUE TITLE
Concerns regarding Cometbft v1.0 upgrade

### ISSUE THREAD

**Issue by charithabandi** [cometbft/cometbft#3834]
@adizere, @andynog I tried rolling updates to comet1.0 build, here are my first set of observations:

Repo: https://github.com/kwilteam/kwil-db/pull/760

### Consensus:

No consensus breakage with a rolling upgrades.

### P2P panics: 

nodes on older versions panic as they receive messages from the nodes on newer versions, potentially due to the changes in this [PR](https://github.com/cometbft/cometbft/pull/904) which introduces this new message (`HasProposalBlockPartMessage`), that the old nodes are not aware of. The panic closes the connection to the peer and reestablish it with every block. So there is significant p2p connection activity happening with every block.

> - Is panic necessary here? **can the protocol be changed to ignore these messages and not cause the old nodes to panic?** 

> - What are the consequences of not consuming these `HasProposalBlockPartMessage` messages? Are there any liveness issues? I have not noticed any, but want to confirm. Also, Is coordinated upgrades the recommended approach for this?

> - [Upgrade guidelines doc](https://github.com/cometbft/cometbft/blob/main/UPGRADING.md) doesn't mention about this breaking nature in P2P layer, you might wanna add it there. 

Node with older versions: Panicking
![image](https://github.com/user-attachments/assets/a9a4fbeb-e6da-4cb7-8a8e-c718ef655bf8)

Peer disconnects with every block: 
![Screenshot 2024-08-20 at 12 06 10 PM](https://github.com/user-attachments/assets/39ea9328-cf3f-4741-af01-e9c9c839e555)

###  Logging issues:

There are lots of noise from the mempool, which I don't think is necessary. Below are the screenshots
![Screenshot 2024-08-20 at 12 06 31 PM](https://github.com/user-attachments/assets/0779b48a-5a07-4220-95a0-d425d003f0b9)

This is one other log message I used to observe a lot while doing stress test and even on smaller loads. But I haven't observed this anymore on comet1.0, looks like u guys fixed it. But I want to bring it up. 
![Screenshot 2024-08-20 at 2 28 10 PM](https://github.com/user-attachments/assets/2c401f92-4a0c-482e-8834-257d3f95b9e8)

**Comment by andynog** [comment]
Thanks for the feedback @charithabandi. I'll evaluate your feedback and use the information as part of an upgrade guide to v1 that I'm working on as part of https://github.com/cometbft/cometbft/issues/3416.

**Comment by jchappelow** [comment]
Thanks, @andynog.  Initially it seemed like 0.38->1.0 would be a rolling upgrade, not even requiring coordination among validators, but the P2P version bump and the addition of a new message makes that trickier.  No consensus breakers, however, which is a relief.  Thanks! :pray: 

I suspect the following is not possible, but is there any way to update 0.38.x so that an unknown message type does not cause the panic and subsequent disconnect?  Or perhaps `consensus.(*Message).Unwrap` (or consumer) could recognize but ignore `HasProposalBlockPart`?

**Comment by melekes** [comment]
I think we should change the past releases so that we do not panic when we encounter an unknown message but simply ignore it.

Thanks for bringing this up @charithabandi ❤️

**Comment by andynog** [comment]
> @andynog do you want to work on this?

Hi @melekes, I'm not working on the solution to this problem at the moment, mostly the guide for now. If you want to take a stab in the solution I'm good with that.

**Comment by sergio-mena** [comment]
Sorry for chiming late here. @charithabandi bear in mind that a rolling upgrade from `v0.38.x` to `v1.0.0` (two different major versions) is _not_ supported, as stated in our [documentation](https://github.com/cometbft/cometbft/blob/main/README.md#versioning). In other words, we don't support mixed networks with `v0.38.x` and `v1.0.0` nodes. Chains must undergo a coordinated upgrade.

This also applies for `v0.34.x`--> `v0.37.x`, `v0.37.x`--> `v0.38.x`.

**Comment by charithabandi** [comment]
Just wanted to follow up on the discussion about the network upgrades and the P2P version bump. From what we've seen, the main thing holding back a rolling upgrade is the P2P changes, not any consensus issues. While we get that breaking compatibility is allowed in major releases, we’d really appreciate it if there’s any way to prevent old nodes from disconnecting during these upgrades. If it's just the P2P layer causing the break, a simple workaround could make a big difference with the upgrade process.

We know the versioning policy allows for these breaks, but fixing this would make it much easier for users like us to upgrade to 1.x without running into major issues. Of course, if there are other breaking changes and you’re not comfortable calling it a rolling upgrade, we totally get that too. But we’re happy to help test if P2P is the only problem affecting our setup.

Thanks for considering this – it would really help smooth out the upgrade process for your user base, including us!

**Comment by andynog** [comment]
Thanks for the feedback, I will revisit this again soon

**Comment by andynog** [comment]
Hi @charithabandi, We just pushed a PR (https://github.com/cometbft/cometbft/pull/4184) with a guide for upgrading from v0.38.x to v1.0. It is currently under review, but if you have any feedback or think anything important is missing, please let me know. 

I still need to review the P2P feedback and see if we need to clarify anything.

**Comment by charithabandi** [comment]
P2P breakages are not mentioned anywhere in the doc, I am guessing they are still in review. The rest looks good to me. 

Quick question: Is there a reason why ABCI's Commit() method doesn't pass height and the app hash as it's arguments and expects application to keep track of it? It's the data cometbft already persists after the FinalizeBlock(), why not pass this info in the Commit() call?

**Comment by sergio-mena** [comment]
`CommitRequest` could indeed be passing height as other ABCI calls are. However, after the initial handshake (and as long as it doesn't crash) the app is supposed to know/remember its own height at every moment, so the app's handlers of other ABCI calls typically use the height passed for sanity checks. Bear in mind that `CommitRequest` (or `RequestCommit`) has not changed in `v1.x`, this has been like this for years. Having said all that, if there's a use case requiring the addition of the current height to `CommitRequest` we can still do it in `v1.x` (as long as it isn't cut yet), or in future versions.

As for the app hash, it's the same one the app is passing to CometBFT as part of `FinalizeBlockResponse`, so I don't see why CometBFT would need to give that same info back to the app in the subsequent call.

**Comment by charithabandi** [comment]
Well, I completely agree with you. But the 2-phase is commit is so hard with many edge cases, it's just easy on application if the hash and height information is sent back with the commits as cometbft has that info persisted.

It's especially important in the crash recovery scenario's where the crash occurs after the FinalizeBlock and before completely finishing the Commit() and app is in this weird half committed state. Also, Cometbft doesn't replay the FinalizeBlock if it has the results persisted and instead directly calls the Commit(), in this case application needs to persist the hash and height (and also where in the block stage we are). We are dealing with this in our App, but just letting you know that, our solution would be way simpler if we have this information passed in the Commit() call.

**Comment by andynog** [comment]
As mentioned in this [comment](https://github.com/cometbft/cometbft/issues/3834#issuecomment-2331001811) rolling upgrades are not supported. 

I will close this issue but the information can be used in a new issue for historical context. This should not be preventing the v1 release cut since what is discussed in this issue is not in scope for the v1 release.
