### ISSUE TITLE
Upgrade to use go 1.20

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#385]
As asked in #174, in general, what are our criteria for updating to support a new version of Go?

**Comment by sergio-mena** [comment]
In abstract, I would tend to be more conservative overall. However, with the (über-strict IMO) policy of only supporting the last to versions of golang, I don't think we can afford to be that conservative.
So I support upgrading `main` to the latest version as soon as it is out.

**Comment by cason** [comment]
Yes, I don't think Golang gives us much choice here. We had 3 versions (1.18 - 1.20) in less than one year. We should hope this doesn't become the norm.

**Comment by thanethomson** [comment]
Yes, the longer we wait to update to the latest version of Go on `main`, the more likely our releases' minimum Go versions are going to end up being unsupported, potentially _increasing_ the likelihood of issues for networks upgrading to new versions (i.e. being more conservative in this case potentially _increases_ risk overall).

**Comment by lasarojc** [comment]
I also like the idea of keeping up with Go and giving the comments above we should move HEAD to Go 1.20. I guess the sooner the better, so people are well warned about it.

What about 0.37? Should we start coordinating with our customers to update to 1.20? Some of them are already there.

**Comment by thanethomson** [comment]
In general we should upgrade to the latest release of Go as soon as pragmatically feasible after it comes out to maximize the lifespan of a release using a single version of Go.

What would dramatically reduce any risks there is if we had some way of testing mixed networks of app chains (e.g. with Gaia) where some binaries are built using one version of Go and other are built using a different version. That's where the real risk comes in. Not during coordinated upgrades.

**Comment by cason** [comment]
An important point to consider is that go 1.20 is not available as a package in some important Linux distros:

- Debian offers 1.19, even for the for the unstable/sid suite: https://packages.debian.org/search?keywords=golang&searchon=names&exact=1&suite=all&section=all
- Ubuntu 22.04 and 22.10 offers 1.19, only the development `lunar` suite, which will become 23.04, offers 1.20: https://packages.ubuntu.com/search?keywords=golang&searchon=names&exact=1&suite=all&section=all

**Comment by thanethomson** [comment]
Does anyone exclusively use the standard versions of Go provided by specific distros? Personally, I either manually download and symlink the latest version of Go, or use Homebrew/Linuxbrew.

Some users only use the Docker images we build, and some will build their own Docker images using the Go 1.20 base images.

**Comment by sergio-mena** [comment]
As an OSX prisoner, I'm a fervent user of Homebrew. A distro not having a version of go available (e.g., via apt) is a _hindrance_. IMO, this should not prevail over the need to keep go as up to date as possible, as that is a _risk_.

**Comment by cason** [comment]
I would say that Golang not supporting a major version for one year is the real issue here. I would not blame the Linux distributions for that.

**Comment by lasarojc** [comment]
PR #419 updated go on the 0.37 branch as well, so closing this.
We shall meet again, once go 1.21 is released!
