### ISSUE TITLE
node cannot sync if network has no snapshots

### ISSUE THREAD

**Issue by charithabandi** [cometbft/cometbft#3878]
Currently, If node has statesync enabled and if there are no snapshots in the network, the node just hangs there in the discovery phase. 

Can the behavior be changed to switch to blocksync mode if snapshots are not discovered after an extended period of time(configurable)?

**Comment by cason** [comment]
> Can the behavior be changed to switch to blocksync mode if snapshots are not discovered after an extended period of time(configurable)?

Yes, this is a good to have. But notice that this will only work if there is a valid initial state.

**Comment by melekes** [comment]
@charithabandi, what would be a good default value for `an extended period of time(configurable)`?
