### ISSUE TITLE
Varying versions of golang

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#3903]
## Bug Report

Comet should only use one version of go. 

To avoid any debate as to what that should be, we should use the latest version of go. 

Currently just making a single pull request, I observed three separate versions of go. That is two too many.

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):

**Have you tried the latest version**: yes/no

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**node command runtime flags**:

**Comment by melekes** [comment]
> Currently just making a single pull request, I observed three separate versions of go. That is two too many.

Could you point to specific places? I can only find differences between CI and docs.
