### ISSUE TITLE
Remove `testnet` command

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft#4002]
`testnet` command, and the companion Makefile infra and Docker files is superseded by `e2e`. `e2e` is able to do everything `testinet` can do and much more (including your example).

I was recently using `testnet`, together with `make localnet-start`. I was doing that for repro purposes. And it's unusable unless you tweak the code, Makefile, and Docker files here and there (or you just use the default settings if they're good enough).

I think we should remove it from newer versions.

_Originally posted by @sergio-mena in https://github.com/cometbft/cometbft/discussions/3566#discussioncomment-10328626_

**Comment by cason** [comment]
In my opinion, we should replace it by a new `e2e.Provider` that allows running Comet in a cluster (or even a single machine).

**Comment by cason** [comment]
At the moment, if you want to run Comet in a cluster, the `testnet` command is helpful. The problem is that you still need to manually edit a lot of config files, what we could optimize by using the end-to-end test infra.
