### ISSUE TITLE
mempool/lanes: add lanes to e2e tests

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4005]
The e2e application now takes the lane from the transaction's payload. All e2e tests have lanes enabled by default.

We need some e2e tests with an app that don't implement lanes, that is, it returns nil lane values on Info and CheckTx requests.

Tasks:
- [x] Extend manifest to support `no_lanes = true`, so that the app does not implement lanes.
- [x] Add the `no_lanes` option to the e2e generator, so that nightly tests run also with no lanes (in particular, combined with `abci_protocol = "tcp"`).
- [x] Add a `lanes=[..]` option to allow for custom lanes to be added to the manifest.

**Comment by jmalicevic** [comment]
Closed by #3993
