### ISSUE TITLE
mempool/lanes: Validate that app versions match on P2P handshake

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4043]
From the [ADR](https://github.com/cometbft/cometbft/blob/main/docs/references/architecture/adr-118-mempool-lanes.md#initialization):

> Different nodes also need to agree on the lanes they use. When a node connects to a peer, they both
perform a handshake to agree on some basic information (see `DefaultNodeInfo`). Since the
application includes the lane definitions, it suffices to ensure that both nodes agree on the
version of the application. Although the application version is included in `DefaultNodeInfo`, there
is currently no check for compatibility between the versions. To address this, we would need to
modify the P2P handshake process to validate that the application versions are compatible.

**Comment by jmalicevic** [comment]
This will not go into the MVP, right? Should we mark it as such somehow?

**Comment by hvanz** [comment]
Right, we don't want to put a restriction on which app version the nodes must have. We will allow different app versions in the network, even if we know that transactions will not be disseminated and reaped in the same way as if all the nodes use the same app version.

Closing this issue as we won't implement this requirement.
