### ISSUE TITLE
libs/metrics: test failures

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#4133]
Ok, the test units on this copied library are producing super random errors:

https://github.com/cometbft/cometbft/actions/runs/10944499019/job/30386514771?pr=4129

https://github.com/cometbft/cometbft/actions/runs/10944445079/job/30386330921?pr=4104

_Originally posted by @cason in https://github.com/cometbft/cometbft/issues/3989#issuecomment-2361405133_

**Comment by andynog** [comment]
For this test https://github.com/cometbft/cometbft/actions/runs/10944499019/job/30386514771?pr=4129

Looks like the test has to spin up a prometheus server and use the response to execute the tests, I'm assuming that for some reason if the prometheus cannot be started the test should fail.
```
	s := httptest.NewServer(promhttp.HandlerFor(stdprometheus.DefaultGatherer, promhttp.HandlerOpts{}))
	defer s.Close()

	scrape := func() string {
		resp, _ := http.Get(s.URL)
		buf, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		return string(buf)
	}
```

I'll improve the test

**Comment by andynog** [comment]
reopening, since I believe #4140 also contributes to fixing these problems
