### ISSUE TITLE
mempool: `log.NewLazySprintf("%X", entry.Tx().Hash())` does not improve performance

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#4167]
The idea of using `log.NewLazySprintf` is to only parse the arguments if the debug message is produced, depending of the debug level. It works as long as the entries have a `String()` implementation that is only invoked when the log message is produced.

However, in this case, we are calling `tx.Hash()`, which expensive, even when debug level > debug.

              However, we are still paying the cost of `tx.Hash()` even without debug.

This is the same as in the rest of this code. Namely, we aren't saving anything here.

_Originally posted by @cason in https://github.com/cometbft/cometbft/pull/4127#discussion_r1772861533_

**Comment by cason** [comment]
A solution here is to change the `String()` method of type `Tx` so that it calls `Tx.Hash()` instead.

Currently it prints the full transaction encoded, hexa-encoded.

**Comment by cason** [comment]
The goal of using `log.NewLazySprintf("%X", entry.Tx().Hash())` is to print the transaction hash (fixed-size), hex-encoded, not the full transaction (with arbitrary size).

**Comment by andynog** [comment]
> A solution here is to change the `String()` method of type `Tx` so that it calls `Tx.Hash()` instead.

I'd not change the `String()` implementation since this is a public method and might break implementations that rely on the current logic, maybe add a new method e.g. `HashString()` (or something like that). 

I think the final solution to the debug problem affecting performance is related to https://github.com/cometbft/cometbft/pull/2989

**Comment by cason** [comment]
Another, non-breaking, option is to implement something like this:

https://github.com/cometbft/cometbft/blob/17c77264a5ce2cd94f5d702abc9d3a726e214536/libs/log/lazy.go#L25-L31

or adapt it to also handles transactions. In other words, this allows you to pass a block and the hash is only computed in a lazy way, in the case the logger is actually executed.
