### ISSUE TITLE
CometBFT reports "Tx not found" for a mined transaction

### ISSUE THREAD

**Issue by charithabandi** [cometbft/cometbft#4236]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
```
cometbft version
0.38.6
```

**Have you tried the latest version**: yes

**ABCI app**:  both example/kvstore and [Kwil](https://github.com/kwilteam/kwil-db)

**node command runtime flags**:        no extra flags

### Config
default config generated using `cometbft init`

### What happened?
I broadcasted a transaction using BroadcastTxCommit endpoint, once the transaction is included in a block, I then repeatedly query for Tx using `Tx` and `UnconfirmedTxs`, it's not found either in the blockchain or in the mempool. 

Same behavior with the BroadcastTxSync.

### What did you expect to happen?

I would expect the clt.Tx query should always return transaction details especially after the tx is included in the block. The root cause is because the clt.Tx() query uses TxIndexer and the indexer is running in a go routine listening to the block events. So there is this latency where the tx is not in the mempool and not yet included in the indexer, resulting in this inconsistent behavior.  
This is confusing for end client to see `Transaction not found` error when instead the tx is already included in the block and affected the application state and also makes this query endpoint unreliable to build applications around. 

### How to reproduce it

Here is a [Toy application](https://github.com/jchappelow/comettest/tree/main) which uses persistent kv store (socket abci app)

1.  Generate cometbft specific config:
```
cometbft init
```

2. Run ABCI application
```sh
mkdir .node

# This runs the kv store on localhost:8080 or pick your own port
go run main.go .node 8080
```

3. Lauch cometbft
```
cometbft start --proxy_app tcp://localhost:8080  
```

4. Issue transactions
```
cd client

go run main.go
```
you should see `tx not found in mempool or block` in the logs on the stdout. 

`client/main.go`  there is code for both BroadcastTxSync and BroadcastTxCommit, you should be able to see this logs after the tx is mined, pretty consistently after every run.

### Logs

```
$ go run main.go

broadcast tx commit :  6840 9D7D74EE2BCEF9280D2042EA36B5C6A676E8EA7CAB3E1FC77334EF7ABD64B570
tx not found in mempool or block
Tx result:  6840 {0 []   0 0 [{app [{creator Cosmoshi Netowoko true} {key key true} {index_key index is working true} {noindex_key index is working false}]} {app [{creator Cosmoshi true} {key 5zdlPqmZ true} {index_key index is working true} {noindex_key index is working false}]}] } Tx{6B65793D357A646C50716D5A}
```

**Comment by andynog** [comment]
Hi @charithabandi, what you describe is right about the `tx` search that it relies on the tx indexer. There might be a minimum delay because like you said the latency between a block committed and when the transactions are indexed but I'd imagine this latency to be minimal. 

What latency numbers are you talking about ? I'd imagine in the range of a couple of milliseconds maximum no? 

If you are polling for transaction results right away, you might need to account for this minimal latency (pull mode). 

Or in a push mode, you can subscribe to the endpoint that emits events, like a new Block or new Tx

```
ws://127.0.0.1:26657/websocket

{
    "jsonrpc": "2.0",
    "method": "subscribe",
    "id": 0,
    "params": {
        "query": "tm.event='Tx'"
    }
}
```

so when a new tx event is emitted, you get the tx result (there still might be a very minimal delay until txs indexing is finalized via a batch).

I'm just wondering if your blocks have many transactions that could also be adding to the latency since the indexer does the txs in batch.

**Comment by charithabandi** [comment]
I had tested out with just a single transaction and the delay for indexing that is a couple of hundred milliseconds.

Is this TxIndexer used for any other purposes internal to the blockchain (like by mempool for rejecting duplicate txns etc.) or is it used just to serve the RPC queries? And, is this latency limited to one block or can it extend over multiple blocks?

**Comment by andynog** [comment]
Hi @charithabandi, the Tx indexer is used mostly by the RPC layer. The mempool has its own internal structure to keep track of transactions.

**Comment by andynog** [comment]
Hi @charithabandi, Can we proceed to close this issue? I believe we’ve addressed all your questions and provided the necessary guidance for coding your app to retrieve the information. If you have any suggestions for improvements to the current behavior, please feel free to share them. Thank you!

**Comment by charithabandi** [comment]
@andynog sure. Thanks for the info, we can close this issue.
