### ISSUE TITLE
incompatiblity: tx_search is reset to a single entry when using goleveldb with cometbft v0.38.x

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#4295]
Goleveldb (not pebble) is broken when using tx_search with cometbft v0.38.12 and cometbft-db v0.13.0+

I don't know if this happens in `main` or not.

If users should not use cometbft-db > 0.12.x with cometbft v0.38.x, we should probably say that.  

I think it is more likely that this breakage was unintentional, related to the contract changes mentioned in the release nodes for cometbft-db:

* https://github.com/cometbft/cometbft-db/blob/v1.0.1/CHANGELOG.md#v0130

Note that users of cometbft v0.38.x may wish to use:

* the latest pebble
* the latest rocksdb
* goleveldb

....all in one place, and that the only way to do that is to either fork cometbft-db or just use the latest version.

This PR:

* https://github.com/cometbft/cometbft/pull/4297

fixes the dependency versioning only.  I think that there are additional issues here in cometbft that prevent goleveldb from working correctly when used with cometbft v0.38.x and cometbft-db v0.13.0+

**Comment by faddat** [comment]
Notably, our "root cause" came from dependabot:

* https://github.com/cometbft/cometbft/pull/4214

**Comment by andynog** [comment]
Hi @faddat, thanks for reporting this. In order for us to reproduce the problem, could you please provide a few more details on the `tx_search is reset to a single entry` statement? 

From what I understand is that when using `tx_search` you would expect to get multiple search results but only one entry is returned. Is that correct ? 

Is the tested performed using ComettBFT only or using a Cosmos-SDK binary pointing to a specific CometBFT release? (from what you said seems that anything that uses `cometbft-db v0.13.0+`)

**Comment by andynog** [comment]
we are doing some extra tests too to try to reproduce the error, just FYI.

**Comment by andynog** [comment]
Fixed in #4321
