### ISSUE TITLE
Use case: Consensus engine developers

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#43]
This is a general tracking issue for efforts towards to refactor Comet so as to be more amenable to being used by consensus engine developers.

At present, many such developers have to fork Comet to accomplish their aims.

- [ ] Ideal Go API boundaries for consensus engine developers
- [ ] #342 

Originally tendermint/tendermint#9878

**Comment by adizere** [comment]
Closing to simplify tracking of major priorities. See instead: 
- https://github.com/cometbft/cometbft/issues/42 and 
- https://github.com/cometbft/cometbft/labels/P%3Aconsensus-engine-devs
