### ISSUE TITLE
mempool/dog: Design and implement tests for potential attacks

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4320]
Design and implement the set of tests (together with acceptable KPIs) that the final algorithm should be passing.

Tests should include typical scenarios (perturbations) and known issues (same tx to multiple nodes) and possible attacks.

Timeboxed (risk of rabbit hole).

**Comment by jmalicevic** [comment]
We tested: 
- [x]  Using number of transactions to trigger the redundancy controller. Experiments suggest it was too volatile and can be used as an attack (sending too many small txs just to trigger a node to send too many `HaveTx` transactions). 
- [x] Varying the `adjustmentInterval` .
- [x] Varying the `adjustmentInterval` for different load and different .

**Comment by hvanz** [comment]
We have two possible adversarial scenarios where the DOG protocol may not work as expected and even isolate nodes from transaction messages:
1. Node perturbations, where a node disconnecting from the network may leave the routing tables of other nodes in an inconsistent state. Also, peers of that node may heavily depend on the transactions sent through that connection. [This scenario](https://github.com/cometbft/cometbft/blob/13d852b43068d2e19de0f307d2bc399b30c0ae68/spec/mempool/gossip/dog.md#nodes-disconnecting-from-the-network) was already covered during the design of the protocol.
2. Two different nodes (that are not peers) receiving the same transaction. The transaction will be propagated in the network and it may happen that two other connected nodes receive it and then send it to each other at the same time. They could end up in a situation where they cut each other routes, cutting all transaction communication between them.

Both scenarios have been tested in #4606.
