### ISSUE TITLE
e2e: Support sending tx load to multiple nodes simultaneously

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4430]
For [the DOG protocol](https://github.com/cometbft/cometbft/issues/3297) we need test scenarios that send the same transaction to the RPC endpoints of multiple nodes. This may occur, for example, when a user wants her transaction to be committed to the chain as fast as possible. The problem is that this could destabilise the gossip protocol. 

Currently the e2e's `runner load` command, when sending transactions, it picks nodes in the testnet, one by one, in a round-robin fashion. Note that the `load` command has a flag `--nodes` that is used to list the target nodes to send the transaction load.

One way to add support to e2e for sending transactions to multiple nodes simultaneously is to add to the `load` command a new flag `--send-all-nodes` (or a better name), or a new option `--strategy=...`, where the current strategy is `"round-robin"` and the new option would be `"all-target-nodes"`.

**Comment by cason** [comment]
> Currently the e2e's runner load command, when sending transactions, it picks nodes in the testnet, one by one, in a round-robin fashion.

This is probably not accurate. We have `num_connections` x number of potential destination nodes threads competing for the same input, a single channel to which produced transactions are added (if I am not wrong, this is an unbuffered channel, meaning that it is blocking...).

So in practice it is the scheduler that defines to which node and via which connection to a node each transaction is sent. If some destination node is slow and still broadcasting the previously consumed transaction, it will be "skipped". If some of the routines is faster than the others, it will potentially consume all produced transactions.

There is an important design problem here, that is not really the main point of this issue...

**Comment by hvanz** [comment]
you are correct, @cason 

In #4561 I propose to create one channel per node to send the generated transactions. When the load generator creates a transaction, it will randomly pick `num-nodes-per-tx` channels (or just one random channel in the default case) to send the transaction. Then, for each node there is one `loadProcess` goroutine per connection reading on the channel corresponding to that node.
