### ISSUE TITLE
p2p: restore the type `p2p.ID`

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#4549]
This change was introduced by https://github.com/cometbft/cometbft/pull/4148, where `p2p.ID` has become `p2p/nodekey.ID`.

Sorry, but this does not make sense.

**Comment by cason** [comment]
In fact, in more general terms, any package that uses the p2p layer to implement a reactor should be able to do so by only importing the `p2p` package.

Now it has to import a bunch of packages, this is not great.

**Comment by melekes** [comment]
Good point 👍 Will revert
