### ISSUE TITLE
mempool/dog: Default value for TargetRedundancyDeltaPercent parameter

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4596]
# Finding a default value for `mempool.dog_target_redundancy_delta_percent`

In these experiments the goal is to find a default value for the parameter
`dog_target_redundancy_delta_percent` (see description in the [DOG protocol spec](https://github.com/cometbft/cometbft/blob/27f062f70e5d6679c458febeae78127764fca829/spec/mempool/gossip/dog.md#parameters)). 
- Possible values are `0, 5, 10, 20, 30`. 
- We set `dog_target_redundancy` and `dog_adjust_interval` to fixed values that we have found to be
good, average, safe values in previous experiments.

## Experiments settings

- 200 nodes with Latency Emulation.
- Constant load of 500 tx/s split in 5 connections.
  - Each transaction is sent to a random single node.
- Duration of each run: 15 min.
- Node config when DOG is enabled:
  - `mempool.dog_target_redundancy = 1`
  - `mempool.dog_target_redundancy_delta_percent` in `(0 5 10 20 30)`
  - `mempool.dog_adjust_interval = "1000ms"`
- Default values of `p2p.max_num_inbound_peers` and `p2p.max_num_outbound_peers`.
- No perturbations.

## Results

The first experiment run is the current mempool wit DOG disabled, which we use as a baseline.

The following instances are with DOG enabled and values `0, 5, 10, 20, 30` of `dog_target_redundancy_delta_percent`.

![delta-screenshot](https://github.com/user-attachments/assets/de75ec39-14d5-479c-8a3c-ab4ff1ee8ecd)

### Observations

- At the end of each run (15 minutes after initializing the testnet), DOG have used in total between
  2.45 and 2.66 times less bandwidth than the current mempool. At this moment the number of disabled
  routes is more stable.

    | | Total Gb sent of `Txs` messages |
    |------|------|
    | No DOG         | 1367 | 
    | DOG, delta=0%  |  536 | 
    | DOG, delta=5%  |  545 |
    | DOG, delta=10% |  531 |
    | DOG, delta=20% |  558 | 
    | DOG, delta=30% |  513 |

- After 15 minutes, these are the latest chain height and the total number of transactions in the chain:

    |                | latest height | txs in chain |
    |----------------|------|------|
    | No DOG         | 506 | 445499
    | DOG, delta=0%  | 606 | 450489
    | DOG, delta=5%  | 619 | 449617
    | DOG, delta=10% | 631 | 448111
    | DOG, delta=20% | 625 | 445970
    | DOG, delta=30% | 622 | 450598

    Here we note that:
    - DOG creates more blocks on the same amount of time.
    - The final number of transactions in chain are similar in all instances, but DOG produces 24%
      more blocks in the same amount of time.

- The total number of bytes sent of `Txs` messages drops from 48% to 29% of the total number of
  bytes sent (all messages).
- The mempool is less busy: its size is lower, and it's less saturated.
- With a transaction load 500tx/s (near the saturation point), without DOG, the mempool is full
  sometimes resulting in rejected transactions. With DOG, the mempool never gets to be full, thus no
  user transaction is rejected.

All this has a positive effect on the whole system. With DOG enabled, we observed:
- 35% less CPU usage (after routes stabilization) and about 5% less memory usage.
- Validators need a second consensus round less often. As a result, `BlockPart` messages uses 10%
  less bandwidth.
- Missing validators: 8 times less missing validators during voting with DOG.
- Missed blocks: about 2.7 times less missed blocks with DOG.
- The total time of ABCI CheckTx requests (that is, new transactions plus rechecks) to the
  application is now 15% lower, even when reCheckTx requests are about 15% higher with DOG.

## Conclusion

There are no significant differences in the results of the different
`dog_target_redundancy_delta_percent`. We see slightly better metrics in the 10% instance,
therefore we decided to set the parameter to this value. Also, it will not be an option in the node
configuration, but a fixed value, hard-coded as a constant in the code.

**Comment by jmalicevic** [comment]
Nothing to add here, we can mark this issue as closed and resolved.
