### ISSUE TITLE
mempool/dog: Default value for TargetRedundancy parameter

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4597]
# Finding a default value for `mempool.dog_target_redundancy`

In these experiments the goal is to find a default value for the parameter `dog_target_redundancy` (see description in the [DOG protocol spec](https://github.com/cometbft/cometbft/blob/27f062f70e5d6679c458febeae78127764fca829/spec/mempool/gossip/dog.md#parameters)).
- Possible values are `0.01, 0.1, 0.5, 1, 2`. 
- We fix the parameter `dog_target_redundancy_delta_percent` to 10% (as per #4596) and `dog_adjust_interval` to `1000ms` .

## Experiments settings

- 200 nodes with Latency Emulation.
- Constant load of 500 tx/s split in 5 connections.
  - Each transaction is sent to a random single node.
- Duration of each run: 15 min.
- Node config when DOG is enabled:
  - `mempool.dog_target_redundancy` in `0.01, 0.1, 0.5, 1, 2`
  - `mempool.dog_target_redundancy_delta_percent = 10`
  - `mempool.dog_adjust_interval = "1000ms"`
- Default values of `p2p.max_num_inbound_peers` and `p2p.max_num_outbound_peers`.
- No perturbations.

## Results

The first experiment run is the current mempool wit DOG disabled, which we use as a baseline.

The following instances are with DOG enabled and values `0.01, 0.1, 0.5, 1, 2` of `dog_target_redundancy`.

![target-screenshot](https://github.com/user-attachments/assets/9e8cf64f-581a-4628-8802-2528dc351e44)

### Observations

- At the end of each run (15 minutes after initializing the testnet), DOG have used in total between 2.38 and
  3.07 times less bandwidth than the current mempool.

    | | Total Gb sent of `Txs` messages |
    |------|------|
    | No DOG           | 1357 | 
    | DOG, target=0.01 |  442 | 
    | DOG, target=0.1  |  443 | 
    | DOG, target=0.5  |  501 | 
    | DOG, target=1    |  538 | 
    | DOG, target=2    |  569 | 

- After 15 minutes, these are the latest chain heights and the total number of transactions in the chain:
  
    |                | latest height | txs in chain |
    |----------------|------|------|
    | No DOG           |  537 | 446534
    | DOG, target=0.01 |  631 | 445089
    | DOG, target=0.1  |  628 | 449579
    | DOG, target=0.5  |  629 | 450192
    | DOG, target=1    |  615 | 450080
    | DOG, target=2    |  606 | 448163

    - The highest number of transactions in chain is observed at around 0.5 of target radundancy.
    - In all DOG instances, the number of blocks produced is between 13% and 17% higher.

- Number of disabled routes at the end of each run:

    |        | Average | Median |
    |----------------|------|------|
    | No DOG           | - | -
    | DOG, target=0.01 |  382 | 193
    | DOG, target=0.1  |  369 | 195
    | DOG, target=0.5  |  327 | 200
    | DOG, target=1    |  313 | 189
    | DOG, target=2    |  211 | 127

    - After 15 minutes, in all cases, all routes seem to have stabilized. 
    - With target=2 the number of disabled routes is much less than with other targets.

# Conclusion

Our experiments confirm that the number of bytes sent of `Txs` messages decreases as the target
redundancy is lowered. Even in the worst-case scenario (target = 2), the DOG protocol achieves a
2.38x reduction in bandwidth usage compared to when DOG is disabled.

However, target redundancies of 0.01 and 0.1 often lead nodes to zero redundancy levels. These are
too low to ensure network safety and resilience, thus we do not recommend to use them. As
anticipated, the results highlight a trade-off between resilience to Byzantine attacks and bandwidth
efficiency.

Interestingly, our findings show minimal differences in performance when the target redundancy is
set to 0.5 versus 1, making both values viable options. Based on these results, we have chosen 1 as
the default target redundancy.

Going forward, we plan to conduct additional experiments to further fine-tune the protocol with 0.5
and 1 as target. These will explore variations in other parameters, such as `dog_adjust_interval`
and the maximum number of peers, to better understand their impact on both bandwidth efficiency and
network resilience.

**Comment by jmalicevic** [comment]
Completed ,we can close it.
