### ISSUE TITLE
chore(e2e): Make `pebbledb` the default DB for testnets

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#4600]
#4122  made `pebbledb` the default database backend of CometBFT. Our e2e infrastructure should be updated accordingly. 
AT the moment it is still defaulting to `goleveldb` .

In `test/loadtime` we are also using `goleveldb` in all examples although there is no default database there so it is less of a problem.

**Comment by DioBr4nd0** [comment]
hey @jmalicevic I would like to work on this issue

**Comment by jmalicevic** [comment]
Yes please go ahead, sorry for the late reply. @DioBr4nd0

**Comment by DioBr4nd0** [comment]
Hii @jmalicevic I have changed the default database to pebbledb in e2e, and also using pebbledb in the loadtime in test in this pr. 
https://github.com/cometbft/cometbft/pull/4691
Please check once and let me know if there's any issue that needs to be handled as this is my first open source contribution, 
Thanks

**Comment by jmalicevic** [comment]
Closed with #4691
