### ISSUE TITLE
mempool/dog: Evaluating resilience and performance under extreme scenarios

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#4606]
# Evaluating the resilience and performance of the DOG Protocol under extreme scenarios

The goal of these experiments is to evaluate the robustness of the DOG protocol in adverse
scenarios, namely when there are perturbations to the nodes and when the same transaction is sent to
multiple nodes simultaneously.

## Experiment settings

- 200 nodes with Latency Emulation.
- Total load of 500 tx/s (details below). This value is higher than the [last measured saturation point](https://github.com/cometbft/cometbft/blob/13d852b43068d2e19de0f307d2bc399b30c0ae68/docs/references/qa/CometBFT-QA-v1.md#saturation-point) of the system (400 tx/s).
- Duration of each run: 15 min.
- Default configuration values for nodes with DOG:
  - `mempool.dog_target_redundancy = 0.5`
  - `mempool.dog_target_redundancy_delta_percent = 10`
  - `mempool.dog_adjust_interval = 1000ms`
- Default configuration values of maximum number of peers:
  - `p2p.max_num_inbound_peers = 40`
  - `p2p.max_num_outbound_peers = 10`

## Test scenarios

We evaluate three scenarios:
1. **Scenario A**. No perturbations and with a constant load of 500tx/s, where each transaction is
   sent to a random single node.
2. **Scenario B.** With perturbations and the same load as A.
3. **Scenario C.** With perturbations while sending:
    - 300tx/s, with each transaction sent to a single random node.
    - 200tx/s, with each transaction sent to 100 random nodes.

Running the testnet with perturbations means that we iteratate on all nodes, and one by one, kill a
node and wait for it to restart, waiting 10 seconds between each perturbation.

## Results

For each of the three scenarios we run first an instance of Flood (the current mempool) and then one
with DOG enabled.

### P2P metrics

![screenshot-compact-part1](https://github.com/user-attachments/assets/cfa8a4b4-fb7d-497f-96e7-6c58d8e29488)

- The bandwidth usage of `Txs` messages is between 1.82 and 2.73 times less with DOG than with the
  current mempool. This is observed after 15 minutes, when the number of disabled routes is more
  stable:

    |                    | Total Gb sent of `Txs` messages | factor |
    | ------------------ | ------------------------------- | ------ |
    | Scenario A - Flood | 1358                            |
    | Scenario A - DOG   | 496                             | 2.73   |
    | Scenario B - Flood | 983                             |
    | Scenario B - DOG   | 446                             | 2.2    |
    | Scenario C - Flood | 992                             |
    | Scenario C - DOG   | 545                             | 1.82   |

- The bandwidth usage of `BlockPart` messages is also lower with DOG, especially in Scenario A with
  a 15% decrease.

### Mempool metrics

![screenshot-compact-part2](https://github.com/user-attachments/assets/6d8cfd8e-3a5d-412d-aeed-594675724321)

With DOG we observe that:
- The number of cache hits is lower because nodes receive less duplicate transactions.
- The mempool contains less transactions at any given time, thus is less saturated.
- The mempool does not become full, at least in these experiments. Without DOG, in some occassions
  the mempool is full and many transactions get rejected as a result.
- In Scenario A, the number of transaction rechecks is higher with DOG (after about 5 minutes)
  because blocks are produced faster, thus triggering more updates on the mempool. 
- The mempool blocks the ABCI lock less often. The total time of ABCI `CheckTx` requests to the
  application (this includes new transactions and rechecks) is now about 10% lower (Scenario A) and
  5% lower (B and C), even when recheck requests are higher (A).

Comparing the DOG metrics, we see that Scenarios B and C reach a lower number of disabled routes
than A, because of the perturbations. Therefore the redundancy level is a bit higher in those cases.

### Runtime and Consensus metrics

![screenshot-compact-part3](https://github.com/user-attachments/assets/ee1e260e-f715-4575-9007-eaff1a2e3447)

With DOG enabled, we observe:
- After routes stabilized, CPU usage is 43% lower (Scenario A), 28% lower (B), and 18% lower (C). 
- Memory usage is about 10% lower.
- Validators need a second consensus round less often.
- 8 times less missing validators during voting.
- About 2.7 times less missed blocks.
- More blocks produced and more transactions in the chain in the same amount of time, as observed after 15 minutes:
  
    |                    | latest height | txs in chain |
    | ------------------ | ------------- | ------------ |
    | Scenario A - Flood | 503           | 448723       |
    | Scenario A - DOG   | 632           | 450627       |
    | Scenario B - Flood | 566           | 447349       |
    | Scenario B - DOG   | 624           | 450270       |
    | Scenario C - Flood | 555           | 439982       |
    | Scenario C - DOG   | 588           | 445977       |

- Block sizes are lower on average leading validators to better processing times and
  resource usage during consensus.
- `BlockPart` messages account for about 10% less bandwidth, as a consequence of all of the above.

## Latency vs Throughput

We [measured](https://github.com/cometbft/cometbft/tree/main/scripts/qa/reporting) the latency of each transaction in all experiments, where latency is the time since the transaction is created until it is included in a block.

| Scenario A | throughput | average latency |
| ---------- | ---------- | --------------- |
| Flood      | 496.9 tx/s | 3.63s           |
| DOG        | 496.6 tx/s | 3.14s           |

In Scenario A, transactions have on average 15% lower latency with DOG, and the same throughput with
both protocols.

| Scenario B | throughput | average latency |
| ---------- | ---------- | --------------- |
| Flood      | 495.1 tx/s | 3.19s           |
| DOG        | 498.6 tx/s | 2.69s           |

In Scenario B, transactions have on average 18% lower latency and slightly better throughput with DOG.

| Scenario C | transaction load    | throughput     | average latency |
| ---------- | ------------------- | -------------- | --------------- |
| Flood      | sent to single node | 298.3 tx/s     | 3.05s           |
| Flood      | sent to 100 nodes   | 188.7 tx/s     | 3.00s           |
| Flood      | total               | **487.0 tx/s** | **3.03s**       |
| DOG        | sent to single node | 299.0 tx/s     | 2.92s           |
| DOG        | sent to 100 nodes   | 194.7 tx/s     | 2.80s           |
| DOG        | total               | **493.7 tx/s** | **2.87s**       |

In Scenario C, transactions have on average 5% lower latency and slightly better throughput with DOG.

## Conclusion

In every evaluated scenario, enabling the GOD protocol consistently results in improvements across
most metrics, with no observed degradation in any area. Moreover, the reduction in redundant
messages has a system-wide positive impact, contributing to faster consensus, lower transaction
latency, and more efficient resource utilization across the network.

The experiments show no evidence that perturbations to the nodes or sending the same transaction to
multiple nodes impact the effectiveness of the DOG protocol, at least in a significant way. It is worth noting that
scenarios B and C represent extreme cases that are unlikely to occur in typical network conditions.
Although sending the same transaction to multiple nodes could slightly degrade system performance,
doing so would come at a substantial cost, making it an impractical attack vector.

**Comment by hvanz** [comment]
| test | test |
|----|-----|
| test | test |

**Comment by jmalicevic** [comment]
### DOG in an overloaded system

The goal of these experiments is to observe the behaviour of CometBFT with DOG enabled and disabled under a very high transaction load (above the saturation point).


### Experiment settings

200 nodes with Latency Emulation.
Varying transaction load: 400tx/s 600tx/s 800tx/s.
Duration of each run: 30 min.
Default configuration values for nodes with DOG:
```
mempool.dog_target_redundancy = 1
mempool.dog_target_redundancy_delta_percent = 20
mempool.dog_adjust_interval = 1000ms
```
Default configuration values of maximum number of peers:
`p2p.max_num_inbound_peers = 40`
`p2p.max_num_outbound_peers = 10`

  DOG was tested with a higher delta in these runs which should increase the number of duplicates in the system.

First, we look at the number of duplicate transactions and the number of bytes sent per message in these scenarios:

 
<img width="1149" alt="duplicate_avg" src="https://github.com/user-attachments/assets/826a7146-1613-4754-9669-c88652b19051">

![sent_msgs_load](https://github.com/user-attachments/assets/de55e1b1-b914-4453-97a6-7f465eb3a188)


Note that 800tx/s and even 600tx/s is considered above the saturation point of the system, and the system is overloaded. However, even in this setting, DOG is able to reduce the bandwidth consumed by the transactions and reduce the number of duplicate transactions received. 

The table below gives an overview of the total number of GBs consumed by transactions. 
During the 30minutes, the number of GB transmitted by Flood is more than 3X the number of GB transmitted when using DOG. 

| | Total Gb sent of `Txs` messsages | factor |
| ---------------|------------------|---------|
| 400tx/s - Flood |                   2382 |                |
| 400tx/s  - DOG | 661| 3.6|
| 600tx/s  - Flood  | 3095 | |  
| 600tx/s - DOG  | 947| 3.3|
| 800tx/s - Flood | 3520| |
| 800tx/s - DOG  | 1083| 3.2|

| | Total Gb sent of `Txs` messsages | % saving |
| ---------------|------------------|---------|
| 400tx/s - Flood |                   1939 |                |
| 400tx/s  - DOG | 1826 | 5|
| 600tx/s  - Flood  | 3611 | |  
| 600tx/s - DOG  | 2981 | 17|
| 800tx/s - Flood | 4507 | |
| 800tx/s - DOG  | 4010 | 11|


The bandwidth consumed by `BlockParts` is also reduced by 5-17%.

While the fact that even with DOG the system is overloaded, we can show that the overall system performance is still better compared to CometBFT with the Flood mempool. 

<img width="1149" alt="txs_load" src="https://github.com/user-attachments/assets/c8297df2-afc9-4d81-8d92-0d5f22ecc307">

<img width="1246" alt="txs_in_chain_load" src="https://github.com/user-attachments/assets/21fbd381-4c83-4fbd-9662-55b9b6385b32">
![blocks_min_load](https://github.com/user-attachments/assets/8f653fdd-e3d8-42b5-8ae1-c05725b198cd)

Under a high load, when using DOG, CometBFT is able to process ~100000 transactions more than when DOG is disabled. 

Metrics for transactions per second and number of blocks per minute all show that when DOG is enabled, the chain is able make progress faster. 

This is also reflected in the number of missing validators, missed rounds and rejected transactions. We can see that the number of validators going into round 1 under high load is much higher when DOG is not used. 
It also worth noting that transactions are  rejected when using DOG as well, but not at the rate at which they are rejected when it is disabled. 

![missed_rounds_load](https://github.com/user-attachments/assets/38a1b148-5bf9-4aa3-aa56-d5ec7162818c)

![missing_validators_load](https://github.com/user-attachments/assets/e6a5c433-2080-408a-9ebf-3e10c2713922)

![rejected_tx_load](https://github.com/user-attachments/assets/6c6a36e3-b65b-4a0c-a2af-f2ec9abc44fe)

Finally, we showcase the parameters showing system utilization when using DOG. 

![cpu_load](https://github.com/user-attachments/assets/051454a7-d312-4a28-aeb5-d952834208d8)
![ram_load](https://github.com/user-attachments/assets/4304567f-1d3f-4770-ab95-73b18f56aa4c)

The experiments show that, when the system is overloaded, DOG outperforms the existing implementation.
