### ISSUE TITLE
Unable to access CometBFT official documentation

### ISSUE THREAD

**Issue by nidhi-singh02** [cometbft/cometbft#4619]
### Setup

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac

### How to reproduce it
Unable to access CometBFT official documentation, it shows domain has expired.
<img width="1467" alt="Screenshot 2024-12-06 at 10 40 05 PM" src="https://github.com/user-attachments/assets/0b1e50a0-1c62-4beb-b42c-4631a1e31abc">

**Comment by jmalicevic** [comment]
I was able to open the link. Let us know if you still have problems. https://docs.cometbft.com/v0.38/   but closing this for now.
