### ISSUE TITLE
QA: Improvements to the result extraction process

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#47]
Tasks:

  - [x] Turn (exploratory) octave scripts into python for automatic plotting    
  - [x] Find a better way to extract Prometheus graphs. By "better", I mean   
    - a) less manual than Firefox snapshot feature
    - b) allowing for customizing things like labels, legend, axes setup, title
  - [x] #799
  - [x] #55
  - [x] #58

DoD:

  - [x] No existing octave scripts no longer there (new, exploratory ones accepted)
  - [x] `loadtime` outputs sorted results
  - [x] There is an automatic process to extract Prometheus graphs

Original issue: tendermint/tendermint#9919

**Comment by lasarojc** [comment]
Some concerns have been addressed by #297 and related PRs
