### ISSUE TITLE
Upgrade go-schnorrkel

### ISSUE THREAD

**Issue by Pitasi** [cometbft/cometbft#475]
### Summary

Upgrade `github.com/ChainSafe/go-schnorrkel` dependency to v1.0.0. This change can be backported to CometBFT 0.34 and 0.37.

### Problem Definition

Tendermint/Comet uses a very old version of the go-schnorrkel library, which in the meanwhile was audited and fixed minor issues.

Personally, I'm asking to upgrade to solve some dependencies conflict I'm currently facing with other modules depending on go-schnorrkel v1.0.0.

### Proposal

Upgrading it's a one-line change:

```diff
diff --git a/crypto/sr25519/pubkey.go b/crypto/sr25519/pubkey.go
index 87805cacb..7fc954fc9 100644
--- a/crypto/sr25519/pubkey.go
+++ b/crypto/sr25519/pubkey.go
@@ -55,7 +55,8 @@ func (pubKey PubKey) VerifySignature(msg []byte, sig []byte) bool {
                return false
        }

-       return publicKey.Verify(signature, signingContext)
+       ok, err := publicKey.Verify(signature, signingContext)
+       return ok && err == nil
 }

 func (pubKey PubKey) String() string {
```

since a little breaking change in the library happened here: https://github.com/ChainSafe/go-schnorrkel/pull/39/files#diff-97ff11627e37ed3ab3988312863fba450e3989219633938dcd82c8ca606455f7.

**Comment by Pitasi** [comment]
Maybe also worth mentioning that on `main` branch go-schnorrkel has been replaced with `github.com/oasisprotocol/curve25519-voi/primitives/sr25519 ` (src: https://github.com/cometbft/cometbft/blob/main/crypto/sr25519/pubkey.go#L7)

**Comment by thanethomson** [comment]
Hey @Pitasi! Thanks for the issue. Feel free to submit a PR making the change, targeting the `v0.34.x` branch!

**Comment by Pitasi** [comment]
Thanks @thanethomson, happy to do it :)

See #643

**Comment by thanethomson** [comment]
Done in #643.
