### ISSUE TITLE
A proposer needs to forward vote extension information to be verified in `ProcessProposal`

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#485]
We need to modify the ABCI interface (`PrepareProposal`) to be able to deliver extra information the the App can use to prove to other nodes that it behaved correctly when preparing the proposal.

- [x] #489 
- [x] #509 
- [x] #540

**Comment by jmalicevic** [comment]
Changes to `ExtendedVoteInfo` reflected in spec by #4460
