### ISSUE TITLE
p2p: dialing addresses provided by a seed node disregards `MaxNumOutboundPeers` parameter 

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#486]
Migrated from tendermint/tendermint#9548.

The method [`ensurePeers`](https://github.com/cometbft/cometbft/blob/main/p2p/pex/pex_reactor.go#L453) defines when a node should dial peer addresses in order to establish outbound peer connections. It dials new peers when the number of outbound peers plus the number of ongoing connections attempts is lower than the configured `MaxNumOutboundPeers` parameter. If the node defines it has to dial peers but it cannot find, in its address book, any suitable peer to dial, this method will submit a PEX request to the configured seed nodes in order to retrieve candidate peer addresses.

The `ensurePeers` method is invoked periodically, every `ensurePeersPeriod = 30s`. This means that between requesting peer addresses to a seed node and actually attempting to dial them, a node will wait for this interval, which was considered too long (tendermint/tendermint#2093). A fix was proposed in tendermint/tendermint#2115, where `ensurePeers` was immediately invoked when a node receives peer addresses provided by a seed node. This solution introduced another issue (tendermint/tendermint#3338): by executing `ensurePeers` in intervals below `ensurePeersPeriod`, a node could end up submitting PEX requests too often, which consists on a misbehavior.

To solve this issue, tendermint/tendermint#3762 replaced the invocation of `ensurePeers`, when receiving addresses from a seed node, by go routines that attempt connecting to _all_ peer addresses received from a seed node. The introduced code [excerpt](https://github.com/cometbft/cometbft/blob/main/p2p/pex/pex_reactor.go#L385), however, does not takes into consideration the number of connected peers or of connection attempts, nor the `MaxNumOutboundPeers` parameter. In other words, the logic implemented in `ensurePeers` to limit the number of outbound peers is ignored. As a result, upon resorting on a seed node to retrieve candidate peers to dial, a node may end up connected to _all_ peers informed by the seed node, which tends to be more than the configured `MaxNumOutboundPeers`, with default value of 10.

This breach in the limits of outbound peers was identified when writing the spec of the p2p layer (tendermint/tendermint#9089). In testnet experiments (tendermint/tendermint#9499), it was observed that nodes had more peers than the maximum configured number (`MaxNumOutboundPeers + MaxNumInboundPeers`, 50 by default). This issue represents the suspect that the reason for this is the breach above detailed. Reinforces this suspect the fact that nodes in the testnet resort by default to seed nodes to learn addresses of potential peers.

Suggested fix: restore the solution introduced by tendermint/tendermint#2115, while creating another way to prevent sending PEX requests to often to connected peers or seed nodes.

**Comment by gaia** [comment]
On osmosisd 18.0.0., I removed all seeds from the config file and deleted addrbook.json. Restarted the daemon. 92 peers, despite

```cat config.toml | grep _num_ && curl -s http://localhost:26657/net_info | jq -r .result.n_peers && /home/ubuntu/bin/osmosisd version
 && systemctl status osmosisd | grep 'Active:' &&  ps aux | grep [o]smosisd && ll config.toml
max_num_inbound_peers = 40
max_num_outbound_peers = 20
109
18.0.0
     Active: active (running) since Tue 2023-08-29 16:25:20 UTC; 4min 18s ago
ubuntu     43320  0.0  7.7 5585304 3013036 ?     Ssl  16:25   5:15 /home/ubuntu/bin/osmosisd start
-rw-rw-r-- 1 ubuntu ubuntu 24K Aug 29 16:23 config.toml```

if peers from the seeds are to blame, how do they remain after clearing the addrbook? and how do I remove them?

**Comment by cason** [comment]
Hey, can you share the content of the config file, specially the p2p section? It would also be useful to have access to the log produced by the node. If you prefer, you can reach us through Slack.

**Comment by cason** [comment]
Regarding the question itself: if there are no seed nodes configured nor addresses in the address book, the node, a priori, would be unable to dial any other node in the network. Because it just does not know any address to dial. It is possible, however, that other nodes know the node's addresses (maybe from previous executions) and would dial it. Once establishing these inbound connections, the node would learn peer addresses from them via PEX protocol, being from this point able to dial some of the provided addresses. Another possibility is that addresses are manually provided to the node. This can be done using the persistent peers configuration flag or via RPC calls instructing the node to dial some specific addresses.

To understand better what is happening to the node, it would be particularly valuable to get the evolution of the log entries produced by the ensure peers routine. Those entries are produced every 30s, by default:

```
r.Logger.Info(
                "Ensure peers",
                "numOutPeers", out,
                "numInPeers", in, 
                "numDialing", dial,
                "numToDial", numToDial,
        )
```

As observed above, they report the number of peers, with distinction between inbound and outbound peers, plus the number of peers the node is currently dialing or will attempt dialing at each call of this method.

**Comment by gaia** [comment]
> Hey, can you share the content of the config file, specially the p2p section? It would also be useful to have access to the log produced by the node. If you prefer, you can reach us through Slack.

best privately via slack/discord/telegram. pls send link.

**Comment by cason** [comment]
Your config file contains 136 persistent peers, is that correct?

```
% grep 'persistent_peers' /tmp/config | tr , '\n' | wc -l
     136
```

**Comment by gaia** [comment]
> Your config file contains 136 persistent peers, is that correct?
> 
> ```
> % grep 'persistent_peers' /tmp/config | tr , '\n' | wc -l
>      136
> ```

yes. 60 max should be respected. i can try removing all of them and see how many peers I end up with (known id@address will get inbound connections any way)

**Comment by gaia** [comment]
our explanation makes sense.

but MaxNumOutboundPeers + MaxNumInboundPeers should be respected and agnostic to where the peers were sourced from. UnconditionalPeers should be the only exception.

More peers than necessary taxes the HW (CPU + Disk) and the uplink. We run our own HW, we use virtualization (need to share CPU+Disk+Uplink) and the limit not being respected becomes an unnecessary burden to our infrastructure (must be noted, without advantages, even for the rest of the network. there is a law of diminishing returns after you add a certain amount of peers)

**Comment by cason** [comment]
I agree with you in general terms. Would you mind to open an issue describing your request? I can follow up and provide context.

The only issue that I have regarding your observation is more conceptual. When you configure a node (address) as _persistent peer_, you are telling Comet that you want to keep a connection with this peer, no matter what is the connection policy configured. You are manually instructing the node to connect to that address. So the node will dial the peer, continue dialing when attempts fails (there is a limit for that, but we are talking about days), and re-dial the peer if the connection, for any reason, is lost.

If you provide `X` persistent peers, you manually instructing the node to maintain connections to those `X` peers. If at the same time you set `MaxNumOutboundPeers < X`, you are definitely providing contradictory instructions to the node.

My main point here is that some users, and maybe this is also your case, are not using the persistent peers manual configuration properly. The point here is to understand what you wanted from this configuration and see whether a different configuration key could be adopted instead. Because if we say that persistent peers are optional connections, what is the point of it? If you say that manual commands should respect the configured bounds, how can we provide a way to overcome the configure bounds by manual action of the operators?

**Comment by cason** [comment]
I am referencing this issue here because I believe that part of the behavior you expect by setting a large number of persistent peers would be achieved with the introduction of the following configuration flag:

https://github.com/cometbft/cometbft/issues/1016

**Comment by cason** [comment]
> If you rename persistent_peers to preferred_peers, all of a sudden my explanation above becomes obvious.

Actually, if we add this new category. Persistent peers are nodes with which I always want to maintain a connection with. The main use case considered for them is, for instance, to connect a validator node to its sentries, or vice-versa. The point here is that sentries can go on or off for arbitrary reasons, but whenever they are online we want to be connected to them.

Regarding the need of adding more persistent peers as previous ones become unavailable, recall that it is possible, via RPC, to configure additional persistent peers at runtime.

**Comment by gaia** [comment]
I'm confused now. Your answer is not making sense to me. I suggested renaming, not adding a new category. To connect to sentries one should use unconditional (possibly in addition to persistent_peers), which is the exception to the maximum number.

For the 2nd paragraph, the point is to make persistent_peers maintenance a task required only every few years, the opposite of adding more peers at runtime.

One last attempt: a maximum is a maximum. persistent are the ones I want to give priority to, **up to the maximum**. The downside of interpreting this differently is wasted hardware and bandwidth. The upside is none, since I can just up the maximum to a number above the number of entries in my desired persistent_peers list.

**Comment by cason** [comment]
The discussion of solutions for this problem should proceed on #1304.

**Comment by gaia** [comment]
> We added this topic to the agenda for the next CometBFT Community call, this Thursday 7th.

I sent a request to join. mostly to listen in, I think my PoV is already well explained.

**Comment by cason** [comment]
https://github.com/cometbft/cometbft/issues/1304#issuecomment-1710460384

**Comment by 0xHansLee** [comment]
Hello, @cason. 

After fixing this issue (#3397), I guess the `sent next PEX request too soon` issue (https://github.com/tendermint/tendermint/issues/3338) occurs again. 

As I understand, this has been fixed in tenermint by just dialing to peer instead of calling `ensurePeers()` (https://github.com/tendermint/tendermint/pull/3762). 
But #3397 calls `ensurePeers()`, so that the PEX request happens too frequently. What do you think of this?
