### ISSUE TITLE
Bug: losing all peers with `peer switch stopped` error

### ISSUE THREAD

**Issue by czarcas7ic** [cometbft/cometbft#521]
# CometBFT peer issue

## Bug Report

For the last two months, nodes on Osmosis are frequently halting with:
```
ERR Won’t start a peer – switch is not running module=p2p peer={“Data”:{}, “Logger”:{}}
```
(presumably coming from: https://github.com/cometbft/cometbft/blob/877b0629578c7695dec77b16cf0021563e060d82/p2p/switch.go#L817-L821C3 )

Validators are saying that they are having issues such as:
```
We have a working node, that then stops progressing and faces the same error every 2hrs. Node is getting stuck connecting to peers.
Updating live peers and restarting is working, but have to keep doing it often to keep the node alive.
```

### Setup

**CometBFT version** Tendermint v0.44.22

**Have you tried the latest version**: no (trying to upgrade to it, working through some SDK dependency issues)

**ABCI app**: Osmosis

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Install tools**: 
- **Others**:

**node command runtime flags**:

### Config

https://pastebin.com/Xs6nKUku

### What happened?

Nodes halt frequently facing peer issues. They appear to be working fine with peers prior to this halt point. They halt with the error previously explained.

Some interestings notes:

* Validators / node operators seem to experience it together (i.e. for an unknown reason, the last couple days validators / node operators have not experienced the issue)
* I have not experienced this issue on our testnet despite utilizing the same binary

### What did you expect to happen?

Node to continue running.

### How to reproduce it

Run a node on mainnet Osmosis (I have been told it happens on other networks as well, but can not personally confirm).

The current "fix" is to continuously restart the node at regular intervals to prevent this error, which is not ideal.

### Logs

```
ERR Won’t start a peer – switch is not running module=p2p peer={“Data”:{}, “Logger”:{}}
```

### `dump_consensus_state` output

Not a consensus bug

**Comment by cason** [comment]
Hi, can you provide a full log of the problematic node for our analysis? The error is very likely produced where you pointed out, but I couldn't understand why the `Switch` would not be running (i.e., why it was stopped) on the reported situation.

Moreover, can you confirm the adopted CometBFT/Tendermin version?

**Comment by andynog** [comment]
another useful information that might be helpful for troubleshooting is the P2P configuration under:
```
#######################################################
###           P2P Configuration Options             ###
#######################################################
[p2p]
```
in the `/.osmosis/config/config.toml` file

**Comment by cason** [comment]
It was not possible to further investigate this issue because we couldn't caught the exact instant where this has happened (on logs or other monitoring interfaces).

Having said so, the issue was not observed once the operators had reduced the maximum inbound and outbound peers parameters. The suspect is that the Switch was overloaded, due to an excessive number of concurrent peers, causing it to be somehow "killed". This is not really expected, but it could happen in an overloaded process, leading the node to crash.
