### ISSUE TITLE
ADR 101: Data companion pull API

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#574]
Tracking issue for implementation of ADR 101 (#82), since it appears as though it is the better of the two solutions between the "push" companion (#73) and the "pull" companion.

All implementations will take place on feature branches so we can choose when to release them. Ideally we would release all major versions' pull companions simultaneously across all major release branches, if we choose to release them as new features for pre-existing releases.

- [x] #816
- [x] Decide whether to implement the pruning API via the existing JSON-RPC or gRPC interfaces on the `v0.38.x` and `v0.37.x` branches -  We will implement the ADR via gRPC in experimental branches for both versions
- [x] #1419
- [x] #1420

Additional PRs that would make this work easier to implement and/or review:

- [x] #650

**Comment by adizere** [comment]
Marking this as done since all sub-issues are closed. Please let me know if this is incorrect.
