### ISSUE TITLE
light client: Empty RPC commit response triggers panic in E2E tests

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#575]
### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source): `v0.34.x`

**Have you tried the latest version**: yes

**ABCI app** (name for built-in, URL for self-written if it's publicly available): E2E

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS

### What happened?

Running our E2E tests locally on my ThinkPad running Ubuntu 22.04 LTS from the `v0.34.x` branch causes the light client to panic and the E2E tests to fail. This was not reproducible on other team members' Macbooks, but @andynog could reproduce this on his Ubuntu machine too.

```bash
cd test/e2e
make -j2 docker runner generator
./run-multiple.sh ./networks/ci.toml
```

The light client's logs: https://gist.github.com/thanethomson/7a3eeddff839adb33bf87af275b2c338#file-light01-log

`validator02`'s logs: https://gist.github.com/thanethomson/7a3eeddff839adb33bf87af275b2c338#file-validator02-log

It appears as though this is due to the fact that, for some unknown reason, `validator02` is not connecting to the rest of the network, and therefore has no blocks. This results in the `/commit` RPC endpoint returning a nil signed header because there's no block metadata for the latest block: https://github.com/cometbft/cometbft/blob/4a9076f8a95cde44b8a5071f13ed02b413aa7cc0/rpc/core/blocks.go#L125

The light client simply accepts this, because there's no error response from the RPC server: https://github.com/cometbft/cometbft/blob/4a9076f8a95cde44b8a5071f13ed02b413aa7cc0/light/provider/http/http.go#L183

It then panics here because the signed header (`sh`) is `nil`: https://github.com/cometbft/cometbft/blob/4a9076f8a95cde44b8a5071f13ed02b413aa7cc0/light/provider/http/http.go#L86

### What did you expect to happen?

For the light client to not panic when it encounters this situation, but instead handle it more gracefully.

Also, does it make sense for the RPC to return a normal, non-error response here? Is it not technically better to return an error indicating that the relevant commit (which happens to be the latest commit) cannot be found?

### How to reproduce it

This is hard to reproduce, and it seems as though it's non-deterministic, since it doesn't always happen.

**Comment by thanethomson** [comment]
Interestingly, I can't reproduce this on the `v0.37.x` or `main` branches. But the relevant code is present on `main` and `v0.37.x`, so it still needs to be fixed.

We also need to separately investigate why the P2P connectivity is failing non-deterministically for the `v0.34.x` branch.

**Comment by jmalicevic** [comment]
By looking at the logs of the light client, it seems that one witness returns information about the block not being there.. it would be interesting to know which one of them causes the first error, whether it is the same one (validator02). While we should definitely add a check in our light client saying that the block is not found, given that an error for non existing blocks already exists,to me also suggests that handling this behaviour is not correct elsewhere. We should have returned `ErrlightBlockNotFound` instead of `nil` to the light client.
