### ISSUE TITLE
Consensus error reported from validator using Gaia v9.0.x

### ISSUE THREAD

**Issue by mmulji-ic** [cometbft/cometbft#580]
## Bug Report
Validator reported the following [consensus error](https://pastebin.com/AjJZUrVP). Currently waiting for additional infomation/logs.
[Issue](https://github.com/informalsystems/tendermint/issues/20) transferred from unsupported Informal System / Tendermint repo.

### Setup

**CometBFT version** (use `cometbft version` or `git rev-parse --verify HEAD` if installed from source):
`Tendermint version 0.34.26` 

**Have you tried the latest version**: yes/no
no

**Gaia version**:
`9.0.x` waiting for exact version, therefore this is `v9.0.0` or `v9.0.1`.

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**node command runtime flags**:
Asked, waiting for input.

### Config

Asked, waiting for input.

### What happened?
Application stopped validating blocks. Validator jailed.

### What did you expect to happen?
No error

### How to reproduce it
Unknown

### Logs

[Stacktrace](https://pastebin.com/AjJZUrVP), waiting for additional logs.

### `dump_consensus_state` output
Asked, waiting for input.

**Comment by sergio-mena** [comment]
Config (`config.toml`) used would also be useful

**Comment by adizere** [comment]
We discussed this internally (I think it was at an onboarding session/office hours). We found out this error should not happen and it's difficult to diagnose without additional context. Closing optimistically as a "can't repro".

For reference, this [was a visual depiction of the call stack](https://link.excalidraw.com/readonly/FaKQfs5mBQKBj2Xq1PqQ).
