### ISSUE TITLE
spec/p2p: Document reactors and the Reactor interface

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#599]
Reactor is the generic name for a component that interacts with the p2p communication layer.

The interaction between a reactor and the p2p layer is in both directions. To become a reactor, the component has to implement the `p2p.Reactor` interface and register with the p2p layer. The p2p layer invokes invokes the reactor to process relevant events, for instance, to deliver incoming messages and to inform when it has established connections to peers. The reactor invokes the p2p layer to send message to peers and to control its operation, for instance, for disconnecting from a peer.

## Definition of Done

This interaction is relatively complex and needs to be properly documented:
- [x] #714
   - Improve the documentation of the `p2p.Reactor` interface methods
   - Describe the interaction p2p layer <-> Reactor using a Grammar
   - Model and formalize the operation of a Reactor using Quint
- [x] #758

**Comment by josef-widder** [comment]
Perhaps in this work, we could figure out how [reactor-survey.md](https://github.com/cometbft/cometbft/pull/80/files#diff-ba2f0f80844a5df01a58e9724d3570ea2b76eca13fdc641a4bf16504e280b040) can be incorporated into the specifications. This document discusses how we can think about the system-level requirements that translate into requirements for p2p. The rest of #80 is less relevant for this issue, and we don't need to merge them soon, so we may close the PR once we have added the survey.

**Comment by cason** [comment]
> Perhaps in this work, we could figure out how [reactor-survey.md](https://github.com/cometbft/cometbft/pull/80/files#diff-ba2f0f80844a5df01a58e9724d3570ea2b76eca13fdc641a4bf16504e280b040) can be incorporated into the specifications. This document discusses how we can think about the system-level requirements that translate into requirements for p2p. The rest of #80 is less relevant for this issue, and we don't need to merge them soon, so we may close the PR once we have added the survey.

https://github.com/cometbft/cometbft/issues/598#issuecomment-1594508348
