### ISSUE TITLE
P2P Stability

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#60]
Was tendermint/tendermint#9055

Tracking issue for Q3 work on stabilizing the P2P layer.

- [x] tendermint/tendermint#9123
- [ ] Stretch goal: go through tendermint/tendermint#5670 to see whether any of the raised issues are applicable to v0.34 and could be addressed in this quarter

**Comment by cason** [comment]
I suggest not tracking #19 at this issue, so that it becomes a tracking issue by itself.

This would also allow closing this issue, since #19 is currently its only document dependency.

**Comment by sergio-mena** [comment]
@cason OK for me
