### ISSUE TITLE
spec/mempool: First version of a formal specification

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#612]
A formal specification of the transaction propagation protocol in the mempool would allow to identify problems in the current implementation, propose optimizations, and help design a future implementation.

### Tasks

- [x] #614
    - When the formal spec is properly documented, there should not be a need of an informal spec.
- [x] #615
     - Checked with Apalache if/when possible

**Comment by sergio-mena** [comment]
Will this be done in collaboration with Pierre? Or is it something you would like to do in preparation before he starts?

**Comment by hvanz** [comment]
I plan to do this one with Pierre. Before, I would just like to experiment a bit with Quint to have a better understanding of the language.
