### ISSUE TITLE
spec/mempool: First formal spec of the transaction propagation protocol

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#614]

**Comment by hvanz** [comment]
We now have two specs of the mempool written in Quint [in the knowledge-base repo](https://github.com/cometbft/knowledge-base/tree/main/quint/mempool). One is a high-level spec, which can apply to any implementation of the mempool. Another is for the v0 implementation, closer to the current code.

**Comment by cason** [comment]
I am afraid that this spec does not cover the _propagation_ of transactions. It is about the mempool as a data structure and how it relates with the other components (application, consensus).

**Comment by hvanz** [comment]
> I am afraid that this spec does not cover the propagation of transactions. It is about the mempool as a data structure and how it relates with the other components (application, consensus).

I changed the title to properly reflect what happened here. The original intention was to spec the implementation (data structures). A new issue will track the work on specifying the propagation protocol (see #1076).
