### ISSUE TITLE
Auto-discovery and Auto-connecting among the peer nodes is not working.

### ISSUE THREAD

**Issue by aramakam3505** [cometbft/cometbft#633]
We have launched network with 3 nodes(Validators), With the following power (n1-->1, n2-->10, n3-->10).
n1 is the first node, n2 is launched by adding n1 as a persistent peer, n3 is launched by adding n1 as a persistent peer.
After few blocks we stopped n1 and n2 was not able to connect with n3.
In cosmos don't we have any auto nodes discovery feature?

What will be the solution for this problem?
Is there any suggestive node topology for the system?
How to use seed node here and does it solve the problem?

**Comment by aramakam3505** [comment]
Can someone comment on this

**Comment by cason** [comment]
Hello, the setup you mentioned should work, namely nodes n2 and n3 should be able to learn each other addresses by having n1 as a common peer. There is no need to setup a seed node in this case, as (regular) nodes should periodically exchanging know peer addresses using the PEX protocol. At the same time, this exchange is only performed when needed, so it is not automatic that n2 and n3 will know each other's address in a short time interval.

For a better diagnosis it would be good to have access to the configuration files adopted by the nodes.

**Comment by thanethomson** [comment]
> Can someone comment on this

Please note that we don't provide real-time support for issues. Also, as @cason says, we at the very least need:

1. The configuration files for your nodes
2. Log outputs showing where the problem occurs

**Comment by aramakam3505** [comment]
@thanethomson I didnt ask any realtime support, the issue I was facing was a basic one and I guess its your responsibility to guide us and take your product to next level. Sorry, if it sounded rude but you just think it is a common feature which is not working, I also have experience with other distributed systems and didnt face this problem till now.

**Comment by aramakam3505** [comment]
@cason Should I provide config.toml for p2p configuration or what configuration files do you exactly mean?

**Comment by cason** [comment]
>  In cosmos don't we have any auto nodes discovery feature?

CometBFT nodes are able to learn the addresses of other nodes running in the same network. So, like I mentioned, nodes n2 and n3 in your setup should eventually know the address of each other. This process is not immediate, though.

> What will be the solution for this problem?

I don't see a problem in your setup. From your description, the 3-node network has an initial topology n2 -> n1 <- n3. Then n1 is killed. In this particular case, there are no guarantees that n2 and n3 will find a way to connect to each other. Notice that the voting power of the validators does not matter here.

> Is there any suggestive node topology for the system?

What are the system requirements? For a small network, manually configuring the addresses of all other nodes at each node would be the recommended setup. This would lead to a fully-connected network topology. While this is not the recommended setup to in production networks, this is the most obvious setup for a 3-node network.

**Comment by adizere** [comment]
Optimistically closing this as "can't repro".

@aramakam3505 please reopen and we'd be glad to continue the conversation here!
