### ISSUE TITLE
RPC server: Long Log Messages

### ISSUE THREAD

**Issue by gaia** [cometbft/cometbft#654]
### Summary

Syslog has trouble handling these long strings (see below). Not sure if they are even needed in logs, but it would surely be great to be able to suppress them, even if syslog gets adjusted to handle them (max message size), just to spare disk IO and reduce log size.

### Problem Definition

https://paste2.org/xbEIvUhb 

### Acceptance criteria

- [ ] truncate the log output in the example above
    - decide if the `txs` raw bytes are useful in the log in the first place (most likely not useful)
        - if useful: keep a truncated version;
        - if not useful: remove the `txs` bytes entirely from the log output

**Comment by adizere** [comment]
Excellent feedback, thanks for logging the issue @gaia !

Will track this under #54, looks like a relatively low-hanging fruit.

**Comment by thanethomson** [comment]
What's a good maximum log length here?

**Comment by gaia** [comment]
> What's a good maximum log length here?

See https://github.com/cometbft/cometbft/pull/829#issuecomment-1546779316
