### ISSUE TITLE
Define external users and use cases for the CometBFT storage layer

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#68]
Original issue: tendermint/tendermint#9943

## Problem definition

We do not have a complete picture on how our users as well as different CometBFT components interact with storage. We therefore need to collect all the relevant use cases for the storage backend. While issue #67 captures internal storage use cases, we need to understand how CometBFT storage is used not including CometBFT itself:
- Who are the main users and how are they using CometBFT storage (validators, sentries, full nodes, relayers, etc., but with specific emphasis on what people are doing with full nodes).

- What are their pain points with regards to storage (usage, querying time, impact from unavailable data) ?
- What types of queries do they typically run agains CometBFT?
- What RPC endpoints are relevant? Are all fields returned by the endpoint of importance?
- How big is their data (block, genesis file)? 
- Do they enable data indexing ?

### DoD
- [ ] A list of different users, their typical usage patterns and issues with regards to CometBFT storage. 
- [ ] Make sure we understand what types of data  they access and whether and how we could allow them to configure individual storage usage.

**Comment by mzabaluev** [comment]
The data access requirements for Hermes are in fact [documented](https://github.com/informalsystems/hermes/blob/master/docs/spec/relayer/Data-Requirements.md) in the repository (subject to being updated, also as part of this work).
 
Brief summary of the request cases with the most impact on storage:

| Endpoint | Parameters | Use of result | Frequency | Notes |
|---------------|------------------|--------------------|-----------------| --------- |
| `/block_search` | Query filtering for a specific IBC channel and sequence number in event data | Block height only | Every _N_ blocks (default _N_ = 100) | The cut-off height is not part of the query, but is used to filter the responses (want blocks older than that). |
| `/block_results` | Height | `{begin,end,finalize}_block_events` fields | For every match from the above query | Also used by CLI, which prints out the whole result. |
|`/tx_search`| Query filtering for a specific IBC channel and sequence number in event data | `height`, `tx_result.events` | Every _N_ blocks (default _N_ = 100) | The cut-off height is not part of the query, but is used to filter the responses (want blocks older than that). |
|`/tx_search`| Tx hash | `height`, `tx_result.events` | Often for packet confirmation, rarely in other cases. | |
|`/tx_search`| Query filtering for client ID and consensus height in `update_client` events | `height`, `tx_result.events` | Rarely except with non-0 delay connections or misbehavior detection | |
| `/header` | Height | Timestamp, consensus state | Frequently | |
| `/block` | Height | TBD | TBD, in some configurations | |

**Comment by romac** [comment]
@mzabaluev FYI I just now updated that document with a couple missing endpoints: https://github.com/informalsystems/hermes/commit/efc9ff502f66cf62e03ddd088af409a1784fd33e

**Comment by jmalicevic** [comment]
For Q3, we can close this issue and expand on new findings as needed. 

- The validator team has shared with us a document explaining their detailed use cases. Their main problem is that the pruning mechanism is not actually freeing storage space on disk. Additionally the response time is slow. 
- Injective has a custom built indexer that extracts data via RPC and is very interested in using our gRPC endpoints to extract the data in that way.
