### ISSUE TITLE
docs: Regenerate configuration file examples

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#702]
In #659 I noticed that the configuration file example in `docs/core/configuration.md` was out of date with the file that's actually generated by running `cometbft init`, so I fixed it for `main`.

We may need to do the same for `v0.38.x`, `v0.37.x` and `v0.34.x`.

**Comment by alijnmerchant21** [comment]
This issue has been resolved with the following PR - #716, #717 and #718
