### ISSUE TITLE
v0.37/v0.38: Changelog should document all API-breaking changes

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#743]
The [changelog](https://github.com/cometbft/cometbft/blob/v0.37.x/CHANGELOG.md) for release v0.37 does not include information/documentation about changes in some publicly exported APIs. This was reported by the SDK team.

These API breaking changes should be included in changelog/upgrading:
- [x] #747 (`v0.38.x`)
- [x] added a boolean parameter (`terminateOnError`) to `NewIndexerService`. The function creates a new indexer service to index events (#228). (`v0.37.x`)

**Comment by cason** [comment]
Is this issue solved?

**Comment by sergio-mena** [comment]
@cason not sure about the second one
