### ISSUE TITLE
bug: Cometbft v0.34.28 breaks ICS downtime slashes

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft#773]
* https://github.com/cosmos/interchain-security/pull/906

Today I made three pull requests to ICS. One of them had a combination of changes to the IBC version and comet. One of them had only comet. The other had only IBC.

IBC v4.4.0 works fine with ICS 

Cometbft causes downtime slashes to fail in ICS

**Comment by thanethomson** [comment]
@faddat do you have any more information here on how to reproduce this without ICS?

In other words, what exactly is causing the failure here? Is the failure consistent, or is it non-deterministic?

**Comment by thanethomson** [comment]
Any updates here?

**Comment by smarshall-spitzbart** [comment]
Hey @thanethomson, as jacob mentioned the ICS e2e tests fail on https://github.com/cosmos/interchain-security/pull/906, where 0.34.28 is used. It seems that when we create the testing scenario of validator downtime, one of the chains in our docker environment seems to halt. That is, [this func](https://github.com/cosmos/interchain-security/blob/7785fa481bcec090f4f556366c6b108a06f4e253/tests/e2e/state.go#L201) panics after a timeout of 2 minutes. In a local docker setup, I've changed the timeout to 30 minutes, and 12 blocks still do not pass after this longer timeout.

**Comment by smarshall-spitzbart** [comment]
I'll also add that the testing scenario of validator downtime does not cause a chain to halt on previous versions of comet. The chain should maintain just over 66% of val power voting

**Comment by MSalopek** [comment]
This is not related to cometBFT. It's due to non-determinism in ICS e2e tests.

Issue: https://github.com/cosmos/interchain-security/issues/967
Fix: https://github.com/cosmos/interchain-security/pull/968

Thanks for pointing this out @faddat 

If there are no objections, I suggest closing this issue since it is not related to comet.
