### ISSUE TITLE
mempool: Reject incoming txs while catching up

### ISSUE THREAD

**Issue by hvanz** [cometbft/cometbft#785]
### Summary

Following the decision taken in [RFC 103](https://github.com/cometbft/cometbft/issues/734), a node that is catching up (that is, performing BlockSync or StateSync) should not accept incoming transactions until it switches to consensus mode.

See #734.

### Proposal

While the node is performing state sync or block sync:
- Disable the RPC endpoints `broadcast_txs_*` by returning an error.
- The mempool reactor should reject incoming transactions and should not send any transaction that may have in the mempool.

There was a proposal for implementing [node phases](https://github.com/tendermint/tendermint/issues/4644), but we won't do that here.

**Comment by cason** [comment]
Possibly related, from Tendermint Core repo: [ mempool: tx gossip cause CheckTx error during the statesync stage #8243 ](https://github.com/tendermint/tendermint/issues/8243)
