### ISSUE TITLE
QA: rotating node test

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#842]
Run the rotating node test as specified in `RELEASES.md` (using the infra existing in `qa-infra`), fix any found issue, compare with `v0.37.0` results. Finally populate the rotating node section of the `v0.38.x` report.

- [x] Set up the DO testbed
- [x] Run the test: loader set up using the saturation point found in the 200 node test
- [x] Obtain the relevant prometheus plots
  - Compare them to those obtained for `v0.37.0`
- [ ] Write corresponding section of the QA report
  - #883

DoD:

* No showstopper bugs found remain unresolved
* Rotating node section of the QA report is merged into `main` and `v0.38.x`
* No unacceptable performance regression detected (usually > 10% degradation w.r.t. `v0.37.0`

**Comment by cason** [comment]
You are referring to this https://github.com/cometbft/cometbft/blob/main/RELEASES.md#rotating-node-testnet, right?

**Comment by sergio-mena** [comment]
@cason yes
