### ISSUE TITLE
Recursive call after rename to (*PeerState).MarshalJSON 

### ISSUE THREAD

**Issue by mmsqe** [cometbft/cometbft#863]
### Setup

CometBFT version: v0.34.28

### What happened? 

No new block when config as debug log_level.

### Anything else we need to know

This issue was introduced in https://github.com/cometbft/cometbft/commit/587bc0b18d281f9949174c2ae9b57a65c3e356bb, when [debug](https://github.com/cometbft/cometbft/blob/587bc0b18d281f9949174c2ae9b57a65c3e356bb/consensus/reactor.go#L1129) logger calls [MarshalJSON](https://github.com/cometbft/cometbft/blob/587bc0b18d281f9949174c2ae9b57a65c3e356bb/consensus/reactor.go#L1059), double lock happens.

**Comment by adizere** [comment]
Thanks for opening the issue and PR! We'll confirm this soon and review your PR. cc @mark-rushakoff

**Comment by cason** [comment]
> This issue was introduced in https://github.com/cometbft/cometbft/commit/587bc0b18d281f9949174c2ae9b57a65c3e356bb, when [debug](https://github.com/cometbft/cometbft/blob/587bc0b18d281f9949174c2ae9b57a65c3e356bb/consensus/reactor.go#L1129) logger calls [MarshalJSON](https://github.com/cometbft/cometbft/blob/587bc0b18d281f9949174c2ae9b57a65c3e356bb/consensus/reactor.go#L1059), double lock happens.

This is actually more than that, as the error is reproduced in test units. It looks more like an infinite loop when marshalling to JSON.

**Comment by mmsqe** [comment]
> This is actually more than that, as the error is reproduced in test units. It looks more like an infinite loop when marshalling to JSON.

Since cmtjson.Marshal inside MarshalJSON of PeerState trigger itself again which implements JSONMarshaler interface, it causes recursive call.
